
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RecordDiagnosis` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RecordDiagnosis
 * 
 */
export type RecordDiagnosisModel = runtime.Types.Result.DefaultSelection<Prisma.$RecordDiagnosisPayload>

export type AggregateRecordDiagnosis = {
  _count: RecordDiagnosisCountAggregateOutputType | null
  _avg: RecordDiagnosisAvgAggregateOutputType | null
  _sum: RecordDiagnosisSumAggregateOutputType | null
  _min: RecordDiagnosisMinAggregateOutputType | null
  _max: RecordDiagnosisMaxAggregateOutputType | null
}

export type RecordDiagnosisAvgAggregateOutputType = {
  diagnosisId: number | null
  recordId: number | null
}

export type RecordDiagnosisSumAggregateOutputType = {
  diagnosisId: number | null
  recordId: number | null
}

export type RecordDiagnosisMinAggregateOutputType = {
  diagnosisId: number | null
  recordId: number | null
  diagnosisName: string | null
  icd10Code: string | null
  diagnosisStatus: string | null
  isPrimary: string | null
  isActive: string | null
  diagnosedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RecordDiagnosisMaxAggregateOutputType = {
  diagnosisId: number | null
  recordId: number | null
  diagnosisName: string | null
  icd10Code: string | null
  diagnosisStatus: string | null
  isPrimary: string | null
  isActive: string | null
  diagnosedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RecordDiagnosisCountAggregateOutputType = {
  diagnosisId: number
  recordId: number
  diagnosisName: number
  icd10Code: number
  diagnosisStatus: number
  isPrimary: number
  isActive: number
  diagnosedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type RecordDiagnosisAvgAggregateInputType = {
  diagnosisId?: true
  recordId?: true
}

export type RecordDiagnosisSumAggregateInputType = {
  diagnosisId?: true
  recordId?: true
}

export type RecordDiagnosisMinAggregateInputType = {
  diagnosisId?: true
  recordId?: true
  diagnosisName?: true
  icd10Code?: true
  diagnosisStatus?: true
  isPrimary?: true
  isActive?: true
  diagnosedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type RecordDiagnosisMaxAggregateInputType = {
  diagnosisId?: true
  recordId?: true
  diagnosisName?: true
  icd10Code?: true
  diagnosisStatus?: true
  isPrimary?: true
  isActive?: true
  diagnosedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type RecordDiagnosisCountAggregateInputType = {
  diagnosisId?: true
  recordId?: true
  diagnosisName?: true
  icd10Code?: true
  diagnosisStatus?: true
  isPrimary?: true
  isActive?: true
  diagnosedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type RecordDiagnosisAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecordDiagnosis to aggregate.
   */
  where?: Prisma.RecordDiagnosisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordDiagnoses to fetch.
   */
  orderBy?: Prisma.RecordDiagnosisOrderByWithRelationInput | Prisma.RecordDiagnosisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RecordDiagnosisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordDiagnoses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordDiagnoses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RecordDiagnoses
  **/
  _count?: true | RecordDiagnosisCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RecordDiagnosisAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RecordDiagnosisSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RecordDiagnosisMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RecordDiagnosisMaxAggregateInputType
}

export type GetRecordDiagnosisAggregateType<T extends RecordDiagnosisAggregateArgs> = {
      [P in keyof T & keyof AggregateRecordDiagnosis]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRecordDiagnosis[P]>
    : Prisma.GetScalarType<T[P], AggregateRecordDiagnosis[P]>
}




export type RecordDiagnosisGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecordDiagnosisWhereInput
  orderBy?: Prisma.RecordDiagnosisOrderByWithAggregationInput | Prisma.RecordDiagnosisOrderByWithAggregationInput[]
  by: Prisma.RecordDiagnosisScalarFieldEnum[] | Prisma.RecordDiagnosisScalarFieldEnum
  having?: Prisma.RecordDiagnosisScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RecordDiagnosisCountAggregateInputType | true
  _avg?: RecordDiagnosisAvgAggregateInputType
  _sum?: RecordDiagnosisSumAggregateInputType
  _min?: RecordDiagnosisMinAggregateInputType
  _max?: RecordDiagnosisMaxAggregateInputType
}

export type RecordDiagnosisGroupByOutputType = {
  diagnosisId: number
  recordId: number
  diagnosisName: string
  icd10Code: string | null
  diagnosisStatus: string
  isPrimary: string
  isActive: string
  diagnosedAt: Date
  createdAt: Date
  updatedAt: Date
  _count: RecordDiagnosisCountAggregateOutputType | null
  _avg: RecordDiagnosisAvgAggregateOutputType | null
  _sum: RecordDiagnosisSumAggregateOutputType | null
  _min: RecordDiagnosisMinAggregateOutputType | null
  _max: RecordDiagnosisMaxAggregateOutputType | null
}

export type GetRecordDiagnosisGroupByPayload<T extends RecordDiagnosisGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RecordDiagnosisGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RecordDiagnosisGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RecordDiagnosisGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RecordDiagnosisGroupByOutputType[P]>
      }
    >
  >



export type RecordDiagnosisWhereInput = {
  AND?: Prisma.RecordDiagnosisWhereInput | Prisma.RecordDiagnosisWhereInput[]
  OR?: Prisma.RecordDiagnosisWhereInput[]
  NOT?: Prisma.RecordDiagnosisWhereInput | Prisma.RecordDiagnosisWhereInput[]
  diagnosisId?: Prisma.IntFilter<"RecordDiagnosis"> | number
  recordId?: Prisma.IntFilter<"RecordDiagnosis"> | number
  diagnosisName?: Prisma.StringFilter<"RecordDiagnosis"> | string
  icd10Code?: Prisma.StringNullableFilter<"RecordDiagnosis"> | string | null
  diagnosisStatus?: Prisma.StringFilter<"RecordDiagnosis"> | string
  isPrimary?: Prisma.StringFilter<"RecordDiagnosis"> | string
  isActive?: Prisma.StringFilter<"RecordDiagnosis"> | string
  diagnosedAt?: Prisma.DateTimeFilter<"RecordDiagnosis"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"RecordDiagnosis"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecordDiagnosis"> | Date | string
  record?: Prisma.XOR<Prisma.MedicalRecordScalarRelationFilter, Prisma.MedicalRecordWhereInput>
}

export type RecordDiagnosisOrderByWithRelationInput = {
  diagnosisId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  diagnosisName?: Prisma.SortOrder
  icd10Code?: Prisma.SortOrderInput | Prisma.SortOrder
  diagnosisStatus?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  diagnosedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  record?: Prisma.MedicalRecordOrderByWithRelationInput
}

export type RecordDiagnosisWhereUniqueInput = Prisma.AtLeast<{
  diagnosisId?: number
  AND?: Prisma.RecordDiagnosisWhereInput | Prisma.RecordDiagnosisWhereInput[]
  OR?: Prisma.RecordDiagnosisWhereInput[]
  NOT?: Prisma.RecordDiagnosisWhereInput | Prisma.RecordDiagnosisWhereInput[]
  recordId?: Prisma.IntFilter<"RecordDiagnosis"> | number
  diagnosisName?: Prisma.StringFilter<"RecordDiagnosis"> | string
  icd10Code?: Prisma.StringNullableFilter<"RecordDiagnosis"> | string | null
  diagnosisStatus?: Prisma.StringFilter<"RecordDiagnosis"> | string
  isPrimary?: Prisma.StringFilter<"RecordDiagnosis"> | string
  isActive?: Prisma.StringFilter<"RecordDiagnosis"> | string
  diagnosedAt?: Prisma.DateTimeFilter<"RecordDiagnosis"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"RecordDiagnosis"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecordDiagnosis"> | Date | string
  record?: Prisma.XOR<Prisma.MedicalRecordScalarRelationFilter, Prisma.MedicalRecordWhereInput>
}, "diagnosisId">

export type RecordDiagnosisOrderByWithAggregationInput = {
  diagnosisId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  diagnosisName?: Prisma.SortOrder
  icd10Code?: Prisma.SortOrderInput | Prisma.SortOrder
  diagnosisStatus?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  diagnosedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.RecordDiagnosisCountOrderByAggregateInput
  _avg?: Prisma.RecordDiagnosisAvgOrderByAggregateInput
  _max?: Prisma.RecordDiagnosisMaxOrderByAggregateInput
  _min?: Prisma.RecordDiagnosisMinOrderByAggregateInput
  _sum?: Prisma.RecordDiagnosisSumOrderByAggregateInput
}

export type RecordDiagnosisScalarWhereWithAggregatesInput = {
  AND?: Prisma.RecordDiagnosisScalarWhereWithAggregatesInput | Prisma.RecordDiagnosisScalarWhereWithAggregatesInput[]
  OR?: Prisma.RecordDiagnosisScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RecordDiagnosisScalarWhereWithAggregatesInput | Prisma.RecordDiagnosisScalarWhereWithAggregatesInput[]
  diagnosisId?: Prisma.IntWithAggregatesFilter<"RecordDiagnosis"> | number
  recordId?: Prisma.IntWithAggregatesFilter<"RecordDiagnosis"> | number
  diagnosisName?: Prisma.StringWithAggregatesFilter<"RecordDiagnosis"> | string
  icd10Code?: Prisma.StringNullableWithAggregatesFilter<"RecordDiagnosis"> | string | null
  diagnosisStatus?: Prisma.StringWithAggregatesFilter<"RecordDiagnosis"> | string
  isPrimary?: Prisma.StringWithAggregatesFilter<"RecordDiagnosis"> | string
  isActive?: Prisma.StringWithAggregatesFilter<"RecordDiagnosis"> | string
  diagnosedAt?: Prisma.DateTimeWithAggregatesFilter<"RecordDiagnosis"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RecordDiagnosis"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RecordDiagnosis"> | Date | string
}

export type RecordDiagnosisCreateInput = {
  diagnosisName: string
  icd10Code?: string | null
  diagnosisStatus?: string
  isPrimary?: string
  isActive?: string
  diagnosedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  record: Prisma.MedicalRecordCreateNestedOneWithoutDiagnosesInput
}

export type RecordDiagnosisUncheckedCreateInput = {
  diagnosisId?: number
  recordId: number
  diagnosisName: string
  icd10Code?: string | null
  diagnosisStatus?: string
  isPrimary?: string
  isActive?: string
  diagnosedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordDiagnosisUpdateInput = {
  diagnosisName?: Prisma.StringFieldUpdateOperationsInput | string
  icd10Code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  diagnosisStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  diagnosedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  record?: Prisma.MedicalRecordUpdateOneRequiredWithoutDiagnosesNestedInput
}

export type RecordDiagnosisUncheckedUpdateInput = {
  diagnosisId?: Prisma.IntFieldUpdateOperationsInput | number
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  diagnosisName?: Prisma.StringFieldUpdateOperationsInput | string
  icd10Code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  diagnosisStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  diagnosedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordDiagnosisCreateManyInput = {
  diagnosisId?: number
  recordId: number
  diagnosisName: string
  icd10Code?: string | null
  diagnosisStatus?: string
  isPrimary?: string
  isActive?: string
  diagnosedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordDiagnosisUpdateManyMutationInput = {
  diagnosisName?: Prisma.StringFieldUpdateOperationsInput | string
  icd10Code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  diagnosisStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  diagnosedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordDiagnosisUncheckedUpdateManyInput = {
  diagnosisId?: Prisma.IntFieldUpdateOperationsInput | number
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  diagnosisName?: Prisma.StringFieldUpdateOperationsInput | string
  icd10Code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  diagnosisStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  diagnosedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordDiagnosisListRelationFilter = {
  every?: Prisma.RecordDiagnosisWhereInput
  some?: Prisma.RecordDiagnosisWhereInput
  none?: Prisma.RecordDiagnosisWhereInput
}

export type RecordDiagnosisOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RecordDiagnosisCountOrderByAggregateInput = {
  diagnosisId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  diagnosisName?: Prisma.SortOrder
  icd10Code?: Prisma.SortOrder
  diagnosisStatus?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  diagnosedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecordDiagnosisAvgOrderByAggregateInput = {
  diagnosisId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
}

export type RecordDiagnosisMaxOrderByAggregateInput = {
  diagnosisId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  diagnosisName?: Prisma.SortOrder
  icd10Code?: Prisma.SortOrder
  diagnosisStatus?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  diagnosedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecordDiagnosisMinOrderByAggregateInput = {
  diagnosisId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  diagnosisName?: Prisma.SortOrder
  icd10Code?: Prisma.SortOrder
  diagnosisStatus?: Prisma.SortOrder
  isPrimary?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  diagnosedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecordDiagnosisSumOrderByAggregateInput = {
  diagnosisId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
}

export type RecordDiagnosisCreateNestedManyWithoutRecordInput = {
  create?: Prisma.XOR<Prisma.RecordDiagnosisCreateWithoutRecordInput, Prisma.RecordDiagnosisUncheckedCreateWithoutRecordInput> | Prisma.RecordDiagnosisCreateWithoutRecordInput[] | Prisma.RecordDiagnosisUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordDiagnosisCreateOrConnectWithoutRecordInput | Prisma.RecordDiagnosisCreateOrConnectWithoutRecordInput[]
  createMany?: Prisma.RecordDiagnosisCreateManyRecordInputEnvelope
  connect?: Prisma.RecordDiagnosisWhereUniqueInput | Prisma.RecordDiagnosisWhereUniqueInput[]
}

export type RecordDiagnosisUncheckedCreateNestedManyWithoutRecordInput = {
  create?: Prisma.XOR<Prisma.RecordDiagnosisCreateWithoutRecordInput, Prisma.RecordDiagnosisUncheckedCreateWithoutRecordInput> | Prisma.RecordDiagnosisCreateWithoutRecordInput[] | Prisma.RecordDiagnosisUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordDiagnosisCreateOrConnectWithoutRecordInput | Prisma.RecordDiagnosisCreateOrConnectWithoutRecordInput[]
  createMany?: Prisma.RecordDiagnosisCreateManyRecordInputEnvelope
  connect?: Prisma.RecordDiagnosisWhereUniqueInput | Prisma.RecordDiagnosisWhereUniqueInput[]
}

export type RecordDiagnosisUpdateManyWithoutRecordNestedInput = {
  create?: Prisma.XOR<Prisma.RecordDiagnosisCreateWithoutRecordInput, Prisma.RecordDiagnosisUncheckedCreateWithoutRecordInput> | Prisma.RecordDiagnosisCreateWithoutRecordInput[] | Prisma.RecordDiagnosisUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordDiagnosisCreateOrConnectWithoutRecordInput | Prisma.RecordDiagnosisCreateOrConnectWithoutRecordInput[]
  upsert?: Prisma.RecordDiagnosisUpsertWithWhereUniqueWithoutRecordInput | Prisma.RecordDiagnosisUpsertWithWhereUniqueWithoutRecordInput[]
  createMany?: Prisma.RecordDiagnosisCreateManyRecordInputEnvelope
  set?: Prisma.RecordDiagnosisWhereUniqueInput | Prisma.RecordDiagnosisWhereUniqueInput[]
  disconnect?: Prisma.RecordDiagnosisWhereUniqueInput | Prisma.RecordDiagnosisWhereUniqueInput[]
  delete?: Prisma.RecordDiagnosisWhereUniqueInput | Prisma.RecordDiagnosisWhereUniqueInput[]
  connect?: Prisma.RecordDiagnosisWhereUniqueInput | Prisma.RecordDiagnosisWhereUniqueInput[]
  update?: Prisma.RecordDiagnosisUpdateWithWhereUniqueWithoutRecordInput | Prisma.RecordDiagnosisUpdateWithWhereUniqueWithoutRecordInput[]
  updateMany?: Prisma.RecordDiagnosisUpdateManyWithWhereWithoutRecordInput | Prisma.RecordDiagnosisUpdateManyWithWhereWithoutRecordInput[]
  deleteMany?: Prisma.RecordDiagnosisScalarWhereInput | Prisma.RecordDiagnosisScalarWhereInput[]
}

export type RecordDiagnosisUncheckedUpdateManyWithoutRecordNestedInput = {
  create?: Prisma.XOR<Prisma.RecordDiagnosisCreateWithoutRecordInput, Prisma.RecordDiagnosisUncheckedCreateWithoutRecordInput> | Prisma.RecordDiagnosisCreateWithoutRecordInput[] | Prisma.RecordDiagnosisUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordDiagnosisCreateOrConnectWithoutRecordInput | Prisma.RecordDiagnosisCreateOrConnectWithoutRecordInput[]
  upsert?: Prisma.RecordDiagnosisUpsertWithWhereUniqueWithoutRecordInput | Prisma.RecordDiagnosisUpsertWithWhereUniqueWithoutRecordInput[]
  createMany?: Prisma.RecordDiagnosisCreateManyRecordInputEnvelope
  set?: Prisma.RecordDiagnosisWhereUniqueInput | Prisma.RecordDiagnosisWhereUniqueInput[]
  disconnect?: Prisma.RecordDiagnosisWhereUniqueInput | Prisma.RecordDiagnosisWhereUniqueInput[]
  delete?: Prisma.RecordDiagnosisWhereUniqueInput | Prisma.RecordDiagnosisWhereUniqueInput[]
  connect?: Prisma.RecordDiagnosisWhereUniqueInput | Prisma.RecordDiagnosisWhereUniqueInput[]
  update?: Prisma.RecordDiagnosisUpdateWithWhereUniqueWithoutRecordInput | Prisma.RecordDiagnosisUpdateWithWhereUniqueWithoutRecordInput[]
  updateMany?: Prisma.RecordDiagnosisUpdateManyWithWhereWithoutRecordInput | Prisma.RecordDiagnosisUpdateManyWithWhereWithoutRecordInput[]
  deleteMany?: Prisma.RecordDiagnosisScalarWhereInput | Prisma.RecordDiagnosisScalarWhereInput[]
}

export type RecordDiagnosisCreateWithoutRecordInput = {
  diagnosisName: string
  icd10Code?: string | null
  diagnosisStatus?: string
  isPrimary?: string
  isActive?: string
  diagnosedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordDiagnosisUncheckedCreateWithoutRecordInput = {
  diagnosisId?: number
  diagnosisName: string
  icd10Code?: string | null
  diagnosisStatus?: string
  isPrimary?: string
  isActive?: string
  diagnosedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordDiagnosisCreateOrConnectWithoutRecordInput = {
  where: Prisma.RecordDiagnosisWhereUniqueInput
  create: Prisma.XOR<Prisma.RecordDiagnosisCreateWithoutRecordInput, Prisma.RecordDiagnosisUncheckedCreateWithoutRecordInput>
}

export type RecordDiagnosisCreateManyRecordInputEnvelope = {
  data: Prisma.RecordDiagnosisCreateManyRecordInput | Prisma.RecordDiagnosisCreateManyRecordInput[]
  skipDuplicates?: boolean
}

export type RecordDiagnosisUpsertWithWhereUniqueWithoutRecordInput = {
  where: Prisma.RecordDiagnosisWhereUniqueInput
  update: Prisma.XOR<Prisma.RecordDiagnosisUpdateWithoutRecordInput, Prisma.RecordDiagnosisUncheckedUpdateWithoutRecordInput>
  create: Prisma.XOR<Prisma.RecordDiagnosisCreateWithoutRecordInput, Prisma.RecordDiagnosisUncheckedCreateWithoutRecordInput>
}

export type RecordDiagnosisUpdateWithWhereUniqueWithoutRecordInput = {
  where: Prisma.RecordDiagnosisWhereUniqueInput
  data: Prisma.XOR<Prisma.RecordDiagnosisUpdateWithoutRecordInput, Prisma.RecordDiagnosisUncheckedUpdateWithoutRecordInput>
}

export type RecordDiagnosisUpdateManyWithWhereWithoutRecordInput = {
  where: Prisma.RecordDiagnosisScalarWhereInput
  data: Prisma.XOR<Prisma.RecordDiagnosisUpdateManyMutationInput, Prisma.RecordDiagnosisUncheckedUpdateManyWithoutRecordInput>
}

export type RecordDiagnosisScalarWhereInput = {
  AND?: Prisma.RecordDiagnosisScalarWhereInput | Prisma.RecordDiagnosisScalarWhereInput[]
  OR?: Prisma.RecordDiagnosisScalarWhereInput[]
  NOT?: Prisma.RecordDiagnosisScalarWhereInput | Prisma.RecordDiagnosisScalarWhereInput[]
  diagnosisId?: Prisma.IntFilter<"RecordDiagnosis"> | number
  recordId?: Prisma.IntFilter<"RecordDiagnosis"> | number
  diagnosisName?: Prisma.StringFilter<"RecordDiagnosis"> | string
  icd10Code?: Prisma.StringNullableFilter<"RecordDiagnosis"> | string | null
  diagnosisStatus?: Prisma.StringFilter<"RecordDiagnosis"> | string
  isPrimary?: Prisma.StringFilter<"RecordDiagnosis"> | string
  isActive?: Prisma.StringFilter<"RecordDiagnosis"> | string
  diagnosedAt?: Prisma.DateTimeFilter<"RecordDiagnosis"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"RecordDiagnosis"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecordDiagnosis"> | Date | string
}

export type RecordDiagnosisCreateManyRecordInput = {
  diagnosisId?: number
  diagnosisName: string
  icd10Code?: string | null
  diagnosisStatus?: string
  isPrimary?: string
  isActive?: string
  diagnosedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordDiagnosisUpdateWithoutRecordInput = {
  diagnosisName?: Prisma.StringFieldUpdateOperationsInput | string
  icd10Code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  diagnosisStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  diagnosedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordDiagnosisUncheckedUpdateWithoutRecordInput = {
  diagnosisId?: Prisma.IntFieldUpdateOperationsInput | number
  diagnosisName?: Prisma.StringFieldUpdateOperationsInput | string
  icd10Code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  diagnosisStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  diagnosedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordDiagnosisUncheckedUpdateManyWithoutRecordInput = {
  diagnosisId?: Prisma.IntFieldUpdateOperationsInput | number
  diagnosisName?: Prisma.StringFieldUpdateOperationsInput | string
  icd10Code?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  diagnosisStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isPrimary?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  diagnosedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RecordDiagnosisSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  diagnosisId?: boolean
  recordId?: boolean
  diagnosisName?: boolean
  icd10Code?: boolean
  diagnosisStatus?: boolean
  isPrimary?: boolean
  isActive?: boolean
  diagnosedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recordDiagnosis"]>

export type RecordDiagnosisSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  diagnosisId?: boolean
  recordId?: boolean
  diagnosisName?: boolean
  icd10Code?: boolean
  diagnosisStatus?: boolean
  isPrimary?: boolean
  isActive?: boolean
  diagnosedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recordDiagnosis"]>

export type RecordDiagnosisSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  diagnosisId?: boolean
  recordId?: boolean
  diagnosisName?: boolean
  icd10Code?: boolean
  diagnosisStatus?: boolean
  isPrimary?: boolean
  isActive?: boolean
  diagnosedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recordDiagnosis"]>

export type RecordDiagnosisSelectScalar = {
  diagnosisId?: boolean
  recordId?: boolean
  diagnosisName?: boolean
  icd10Code?: boolean
  diagnosisStatus?: boolean
  isPrimary?: boolean
  isActive?: boolean
  diagnosedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type RecordDiagnosisOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"diagnosisId" | "recordId" | "diagnosisName" | "icd10Code" | "diagnosisStatus" | "isPrimary" | "isActive" | "diagnosedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["recordDiagnosis"]>
export type RecordDiagnosisInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}
export type RecordDiagnosisIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}
export type RecordDiagnosisIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}

export type $RecordDiagnosisPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RecordDiagnosis"
  objects: {
    record: Prisma.$MedicalRecordPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    diagnosisId: number
    recordId: number
    diagnosisName: string
    icd10Code: string | null
    diagnosisStatus: string
    isPrimary: string
    isActive: string
    diagnosedAt: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["recordDiagnosis"]>
  composites: {}
}

export type RecordDiagnosisGetPayload<S extends boolean | null | undefined | RecordDiagnosisDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload, S>

export type RecordDiagnosisCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RecordDiagnosisFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RecordDiagnosisCountAggregateInputType | true
  }

export interface RecordDiagnosisDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RecordDiagnosis'], meta: { name: 'RecordDiagnosis' } }
  /**
   * Find zero or one RecordDiagnosis that matches the filter.
   * @param {RecordDiagnosisFindUniqueArgs} args - Arguments to find a RecordDiagnosis
   * @example
   * // Get one RecordDiagnosis
   * const recordDiagnosis = await prisma.recordDiagnosis.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RecordDiagnosisFindUniqueArgs>(args: Prisma.SelectSubset<T, RecordDiagnosisFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RecordDiagnosisClient<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RecordDiagnosis that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RecordDiagnosisFindUniqueOrThrowArgs} args - Arguments to find a RecordDiagnosis
   * @example
   * // Get one RecordDiagnosis
   * const recordDiagnosis = await prisma.recordDiagnosis.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RecordDiagnosisFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RecordDiagnosisFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecordDiagnosisClient<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecordDiagnosis that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordDiagnosisFindFirstArgs} args - Arguments to find a RecordDiagnosis
   * @example
   * // Get one RecordDiagnosis
   * const recordDiagnosis = await prisma.recordDiagnosis.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RecordDiagnosisFindFirstArgs>(args?: Prisma.SelectSubset<T, RecordDiagnosisFindFirstArgs<ExtArgs>>): Prisma.Prisma__RecordDiagnosisClient<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecordDiagnosis that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordDiagnosisFindFirstOrThrowArgs} args - Arguments to find a RecordDiagnosis
   * @example
   * // Get one RecordDiagnosis
   * const recordDiagnosis = await prisma.recordDiagnosis.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RecordDiagnosisFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RecordDiagnosisFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecordDiagnosisClient<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RecordDiagnoses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordDiagnosisFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RecordDiagnoses
   * const recordDiagnoses = await prisma.recordDiagnosis.findMany()
   * 
   * // Get first 10 RecordDiagnoses
   * const recordDiagnoses = await prisma.recordDiagnosis.findMany({ take: 10 })
   * 
   * // Only select the `diagnosisId`
   * const recordDiagnosisWithDiagnosisIdOnly = await prisma.recordDiagnosis.findMany({ select: { diagnosisId: true } })
   * 
   */
  findMany<T extends RecordDiagnosisFindManyArgs>(args?: Prisma.SelectSubset<T, RecordDiagnosisFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RecordDiagnosis.
   * @param {RecordDiagnosisCreateArgs} args - Arguments to create a RecordDiagnosis.
   * @example
   * // Create one RecordDiagnosis
   * const RecordDiagnosis = await prisma.recordDiagnosis.create({
   *   data: {
   *     // ... data to create a RecordDiagnosis
   *   }
   * })
   * 
   */
  create<T extends RecordDiagnosisCreateArgs>(args: Prisma.SelectSubset<T, RecordDiagnosisCreateArgs<ExtArgs>>): Prisma.Prisma__RecordDiagnosisClient<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RecordDiagnoses.
   * @param {RecordDiagnosisCreateManyArgs} args - Arguments to create many RecordDiagnoses.
   * @example
   * // Create many RecordDiagnoses
   * const recordDiagnosis = await prisma.recordDiagnosis.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RecordDiagnosisCreateManyArgs>(args?: Prisma.SelectSubset<T, RecordDiagnosisCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RecordDiagnoses and returns the data saved in the database.
   * @param {RecordDiagnosisCreateManyAndReturnArgs} args - Arguments to create many RecordDiagnoses.
   * @example
   * // Create many RecordDiagnoses
   * const recordDiagnosis = await prisma.recordDiagnosis.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RecordDiagnoses and only return the `diagnosisId`
   * const recordDiagnosisWithDiagnosisIdOnly = await prisma.recordDiagnosis.createManyAndReturn({
   *   select: { diagnosisId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RecordDiagnosisCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RecordDiagnosisCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RecordDiagnosis.
   * @param {RecordDiagnosisDeleteArgs} args - Arguments to delete one RecordDiagnosis.
   * @example
   * // Delete one RecordDiagnosis
   * const RecordDiagnosis = await prisma.recordDiagnosis.delete({
   *   where: {
   *     // ... filter to delete one RecordDiagnosis
   *   }
   * })
   * 
   */
  delete<T extends RecordDiagnosisDeleteArgs>(args: Prisma.SelectSubset<T, RecordDiagnosisDeleteArgs<ExtArgs>>): Prisma.Prisma__RecordDiagnosisClient<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RecordDiagnosis.
   * @param {RecordDiagnosisUpdateArgs} args - Arguments to update one RecordDiagnosis.
   * @example
   * // Update one RecordDiagnosis
   * const recordDiagnosis = await prisma.recordDiagnosis.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RecordDiagnosisUpdateArgs>(args: Prisma.SelectSubset<T, RecordDiagnosisUpdateArgs<ExtArgs>>): Prisma.Prisma__RecordDiagnosisClient<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RecordDiagnoses.
   * @param {RecordDiagnosisDeleteManyArgs} args - Arguments to filter RecordDiagnoses to delete.
   * @example
   * // Delete a few RecordDiagnoses
   * const { count } = await prisma.recordDiagnosis.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RecordDiagnosisDeleteManyArgs>(args?: Prisma.SelectSubset<T, RecordDiagnosisDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecordDiagnoses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordDiagnosisUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RecordDiagnoses
   * const recordDiagnosis = await prisma.recordDiagnosis.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RecordDiagnosisUpdateManyArgs>(args: Prisma.SelectSubset<T, RecordDiagnosisUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecordDiagnoses and returns the data updated in the database.
   * @param {RecordDiagnosisUpdateManyAndReturnArgs} args - Arguments to update many RecordDiagnoses.
   * @example
   * // Update many RecordDiagnoses
   * const recordDiagnosis = await prisma.recordDiagnosis.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RecordDiagnoses and only return the `diagnosisId`
   * const recordDiagnosisWithDiagnosisIdOnly = await prisma.recordDiagnosis.updateManyAndReturn({
   *   select: { diagnosisId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RecordDiagnosisUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RecordDiagnosisUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RecordDiagnosis.
   * @param {RecordDiagnosisUpsertArgs} args - Arguments to update or create a RecordDiagnosis.
   * @example
   * // Update or create a RecordDiagnosis
   * const recordDiagnosis = await prisma.recordDiagnosis.upsert({
   *   create: {
   *     // ... data to create a RecordDiagnosis
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RecordDiagnosis we want to update
   *   }
   * })
   */
  upsert<T extends RecordDiagnosisUpsertArgs>(args: Prisma.SelectSubset<T, RecordDiagnosisUpsertArgs<ExtArgs>>): Prisma.Prisma__RecordDiagnosisClient<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RecordDiagnoses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordDiagnosisCountArgs} args - Arguments to filter RecordDiagnoses to count.
   * @example
   * // Count the number of RecordDiagnoses
   * const count = await prisma.recordDiagnosis.count({
   *   where: {
   *     // ... the filter for the RecordDiagnoses we want to count
   *   }
   * })
  **/
  count<T extends RecordDiagnosisCountArgs>(
    args?: Prisma.Subset<T, RecordDiagnosisCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RecordDiagnosisCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RecordDiagnosis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordDiagnosisAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RecordDiagnosisAggregateArgs>(args: Prisma.Subset<T, RecordDiagnosisAggregateArgs>): Prisma.PrismaPromise<GetRecordDiagnosisAggregateType<T>>

  /**
   * Group by RecordDiagnosis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordDiagnosisGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RecordDiagnosisGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RecordDiagnosisGroupByArgs['orderBy'] }
      : { orderBy?: RecordDiagnosisGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RecordDiagnosisGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRecordDiagnosisGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RecordDiagnosis model
 */
readonly fields: RecordDiagnosisFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RecordDiagnosis.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RecordDiagnosisClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  record<T extends Prisma.MedicalRecordDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MedicalRecordDefaultArgs<ExtArgs>>): Prisma.Prisma__MedicalRecordClient<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RecordDiagnosis model
 */
export interface RecordDiagnosisFieldRefs {
  readonly diagnosisId: Prisma.FieldRef<"RecordDiagnosis", 'Int'>
  readonly recordId: Prisma.FieldRef<"RecordDiagnosis", 'Int'>
  readonly diagnosisName: Prisma.FieldRef<"RecordDiagnosis", 'String'>
  readonly icd10Code: Prisma.FieldRef<"RecordDiagnosis", 'String'>
  readonly diagnosisStatus: Prisma.FieldRef<"RecordDiagnosis", 'String'>
  readonly isPrimary: Prisma.FieldRef<"RecordDiagnosis", 'String'>
  readonly isActive: Prisma.FieldRef<"RecordDiagnosis", 'String'>
  readonly diagnosedAt: Prisma.FieldRef<"RecordDiagnosis", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"RecordDiagnosis", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RecordDiagnosis", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RecordDiagnosis findUnique
 */
export type RecordDiagnosisFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisInclude<ExtArgs> | null
  /**
   * Filter, which RecordDiagnosis to fetch.
   */
  where: Prisma.RecordDiagnosisWhereUniqueInput
}

/**
 * RecordDiagnosis findUniqueOrThrow
 */
export type RecordDiagnosisFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisInclude<ExtArgs> | null
  /**
   * Filter, which RecordDiagnosis to fetch.
   */
  where: Prisma.RecordDiagnosisWhereUniqueInput
}

/**
 * RecordDiagnosis findFirst
 */
export type RecordDiagnosisFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisInclude<ExtArgs> | null
  /**
   * Filter, which RecordDiagnosis to fetch.
   */
  where?: Prisma.RecordDiagnosisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordDiagnoses to fetch.
   */
  orderBy?: Prisma.RecordDiagnosisOrderByWithRelationInput | Prisma.RecordDiagnosisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecordDiagnoses.
   */
  cursor?: Prisma.RecordDiagnosisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordDiagnoses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordDiagnoses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecordDiagnoses.
   */
  distinct?: Prisma.RecordDiagnosisScalarFieldEnum | Prisma.RecordDiagnosisScalarFieldEnum[]
}

/**
 * RecordDiagnosis findFirstOrThrow
 */
export type RecordDiagnosisFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisInclude<ExtArgs> | null
  /**
   * Filter, which RecordDiagnosis to fetch.
   */
  where?: Prisma.RecordDiagnosisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordDiagnoses to fetch.
   */
  orderBy?: Prisma.RecordDiagnosisOrderByWithRelationInput | Prisma.RecordDiagnosisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecordDiagnoses.
   */
  cursor?: Prisma.RecordDiagnosisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordDiagnoses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordDiagnoses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecordDiagnoses.
   */
  distinct?: Prisma.RecordDiagnosisScalarFieldEnum | Prisma.RecordDiagnosisScalarFieldEnum[]
}

/**
 * RecordDiagnosis findMany
 */
export type RecordDiagnosisFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisInclude<ExtArgs> | null
  /**
   * Filter, which RecordDiagnoses to fetch.
   */
  where?: Prisma.RecordDiagnosisWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordDiagnoses to fetch.
   */
  orderBy?: Prisma.RecordDiagnosisOrderByWithRelationInput | Prisma.RecordDiagnosisOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RecordDiagnoses.
   */
  cursor?: Prisma.RecordDiagnosisWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordDiagnoses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordDiagnoses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecordDiagnoses.
   */
  distinct?: Prisma.RecordDiagnosisScalarFieldEnum | Prisma.RecordDiagnosisScalarFieldEnum[]
}

/**
 * RecordDiagnosis create
 */
export type RecordDiagnosisCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisInclude<ExtArgs> | null
  /**
   * The data needed to create a RecordDiagnosis.
   */
  data: Prisma.XOR<Prisma.RecordDiagnosisCreateInput, Prisma.RecordDiagnosisUncheckedCreateInput>
}

/**
 * RecordDiagnosis createMany
 */
export type RecordDiagnosisCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RecordDiagnoses.
   */
  data: Prisma.RecordDiagnosisCreateManyInput | Prisma.RecordDiagnosisCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RecordDiagnosis createManyAndReturn
 */
export type RecordDiagnosisCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * The data used to create many RecordDiagnoses.
   */
  data: Prisma.RecordDiagnosisCreateManyInput | Prisma.RecordDiagnosisCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RecordDiagnosis update
 */
export type RecordDiagnosisUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisInclude<ExtArgs> | null
  /**
   * The data needed to update a RecordDiagnosis.
   */
  data: Prisma.XOR<Prisma.RecordDiagnosisUpdateInput, Prisma.RecordDiagnosisUncheckedUpdateInput>
  /**
   * Choose, which RecordDiagnosis to update.
   */
  where: Prisma.RecordDiagnosisWhereUniqueInput
}

/**
 * RecordDiagnosis updateMany
 */
export type RecordDiagnosisUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RecordDiagnoses.
   */
  data: Prisma.XOR<Prisma.RecordDiagnosisUpdateManyMutationInput, Prisma.RecordDiagnosisUncheckedUpdateManyInput>
  /**
   * Filter which RecordDiagnoses to update
   */
  where?: Prisma.RecordDiagnosisWhereInput
  /**
   * Limit how many RecordDiagnoses to update.
   */
  limit?: number
}

/**
 * RecordDiagnosis updateManyAndReturn
 */
export type RecordDiagnosisUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * The data used to update RecordDiagnoses.
   */
  data: Prisma.XOR<Prisma.RecordDiagnosisUpdateManyMutationInput, Prisma.RecordDiagnosisUncheckedUpdateManyInput>
  /**
   * Filter which RecordDiagnoses to update
   */
  where?: Prisma.RecordDiagnosisWhereInput
  /**
   * Limit how many RecordDiagnoses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RecordDiagnosis upsert
 */
export type RecordDiagnosisUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisInclude<ExtArgs> | null
  /**
   * The filter to search for the RecordDiagnosis to update in case it exists.
   */
  where: Prisma.RecordDiagnosisWhereUniqueInput
  /**
   * In case the RecordDiagnosis found by the `where` argument doesn't exist, create a new RecordDiagnosis with this data.
   */
  create: Prisma.XOR<Prisma.RecordDiagnosisCreateInput, Prisma.RecordDiagnosisUncheckedCreateInput>
  /**
   * In case the RecordDiagnosis was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RecordDiagnosisUpdateInput, Prisma.RecordDiagnosisUncheckedUpdateInput>
}

/**
 * RecordDiagnosis delete
 */
export type RecordDiagnosisDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisInclude<ExtArgs> | null
  /**
   * Filter which RecordDiagnosis to delete.
   */
  where: Prisma.RecordDiagnosisWhereUniqueInput
}

/**
 * RecordDiagnosis deleteMany
 */
export type RecordDiagnosisDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecordDiagnoses to delete
   */
  where?: Prisma.RecordDiagnosisWhereInput
  /**
   * Limit how many RecordDiagnoses to delete.
   */
  limit?: number
}

/**
 * RecordDiagnosis without action
 */
export type RecordDiagnosisDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisInclude<ExtArgs> | null
}
