
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RecordTreatment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RecordTreatment
 * 
 */
export type RecordTreatmentModel = runtime.Types.Result.DefaultSelection<Prisma.$RecordTreatmentPayload>

export type AggregateRecordTreatment = {
  _count: RecordTreatmentCountAggregateOutputType | null
  _avg: RecordTreatmentAvgAggregateOutputType | null
  _sum: RecordTreatmentSumAggregateOutputType | null
  _min: RecordTreatmentMinAggregateOutputType | null
  _max: RecordTreatmentMaxAggregateOutputType | null
}

export type RecordTreatmentAvgAggregateOutputType = {
  treatmentId: number | null
  recordId: number | null
}

export type RecordTreatmentSumAggregateOutputType = {
  treatmentId: number | null
  recordId: number | null
}

export type RecordTreatmentMinAggregateOutputType = {
  treatmentId: number | null
  recordId: number | null
  treatmentName: string | null
  treatmentDescription: string | null
  treatmentDate: Date | null
  outcome: string | null
  notes: string | null
  isActive: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RecordTreatmentMaxAggregateOutputType = {
  treatmentId: number | null
  recordId: number | null
  treatmentName: string | null
  treatmentDescription: string | null
  treatmentDate: Date | null
  outcome: string | null
  notes: string | null
  isActive: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RecordTreatmentCountAggregateOutputType = {
  treatmentId: number
  recordId: number
  treatmentName: number
  treatmentDescription: number
  treatmentDate: number
  outcome: number
  notes: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type RecordTreatmentAvgAggregateInputType = {
  treatmentId?: true
  recordId?: true
}

export type RecordTreatmentSumAggregateInputType = {
  treatmentId?: true
  recordId?: true
}

export type RecordTreatmentMinAggregateInputType = {
  treatmentId?: true
  recordId?: true
  treatmentName?: true
  treatmentDescription?: true
  treatmentDate?: true
  outcome?: true
  notes?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type RecordTreatmentMaxAggregateInputType = {
  treatmentId?: true
  recordId?: true
  treatmentName?: true
  treatmentDescription?: true
  treatmentDate?: true
  outcome?: true
  notes?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type RecordTreatmentCountAggregateInputType = {
  treatmentId?: true
  recordId?: true
  treatmentName?: true
  treatmentDescription?: true
  treatmentDate?: true
  outcome?: true
  notes?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type RecordTreatmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecordTreatment to aggregate.
   */
  where?: Prisma.RecordTreatmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordTreatments to fetch.
   */
  orderBy?: Prisma.RecordTreatmentOrderByWithRelationInput | Prisma.RecordTreatmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RecordTreatmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordTreatments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordTreatments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RecordTreatments
  **/
  _count?: true | RecordTreatmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RecordTreatmentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RecordTreatmentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RecordTreatmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RecordTreatmentMaxAggregateInputType
}

export type GetRecordTreatmentAggregateType<T extends RecordTreatmentAggregateArgs> = {
      [P in keyof T & keyof AggregateRecordTreatment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRecordTreatment[P]>
    : Prisma.GetScalarType<T[P], AggregateRecordTreatment[P]>
}




export type RecordTreatmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecordTreatmentWhereInput
  orderBy?: Prisma.RecordTreatmentOrderByWithAggregationInput | Prisma.RecordTreatmentOrderByWithAggregationInput[]
  by: Prisma.RecordTreatmentScalarFieldEnum[] | Prisma.RecordTreatmentScalarFieldEnum
  having?: Prisma.RecordTreatmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RecordTreatmentCountAggregateInputType | true
  _avg?: RecordTreatmentAvgAggregateInputType
  _sum?: RecordTreatmentSumAggregateInputType
  _min?: RecordTreatmentMinAggregateInputType
  _max?: RecordTreatmentMaxAggregateInputType
}

export type RecordTreatmentGroupByOutputType = {
  treatmentId: number
  recordId: number
  treatmentName: string
  treatmentDescription: string | null
  treatmentDate: Date
  outcome: string | null
  notes: string | null
  isActive: string
  createdAt: Date
  updatedAt: Date
  _count: RecordTreatmentCountAggregateOutputType | null
  _avg: RecordTreatmentAvgAggregateOutputType | null
  _sum: RecordTreatmentSumAggregateOutputType | null
  _min: RecordTreatmentMinAggregateOutputType | null
  _max: RecordTreatmentMaxAggregateOutputType | null
}

export type GetRecordTreatmentGroupByPayload<T extends RecordTreatmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RecordTreatmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RecordTreatmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RecordTreatmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RecordTreatmentGroupByOutputType[P]>
      }
    >
  >



export type RecordTreatmentWhereInput = {
  AND?: Prisma.RecordTreatmentWhereInput | Prisma.RecordTreatmentWhereInput[]
  OR?: Prisma.RecordTreatmentWhereInput[]
  NOT?: Prisma.RecordTreatmentWhereInput | Prisma.RecordTreatmentWhereInput[]
  treatmentId?: Prisma.IntFilter<"RecordTreatment"> | number
  recordId?: Prisma.IntFilter<"RecordTreatment"> | number
  treatmentName?: Prisma.StringFilter<"RecordTreatment"> | string
  treatmentDescription?: Prisma.StringNullableFilter<"RecordTreatment"> | string | null
  treatmentDate?: Prisma.DateTimeFilter<"RecordTreatment"> | Date | string
  outcome?: Prisma.StringNullableFilter<"RecordTreatment"> | string | null
  notes?: Prisma.StringNullableFilter<"RecordTreatment"> | string | null
  isActive?: Prisma.StringFilter<"RecordTreatment"> | string
  createdAt?: Prisma.DateTimeFilter<"RecordTreatment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecordTreatment"> | Date | string
  record?: Prisma.XOR<Prisma.MedicalRecordScalarRelationFilter, Prisma.MedicalRecordWhereInput>
}

export type RecordTreatmentOrderByWithRelationInput = {
  treatmentId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  treatmentName?: Prisma.SortOrder
  treatmentDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  treatmentDate?: Prisma.SortOrder
  outcome?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  record?: Prisma.MedicalRecordOrderByWithRelationInput
}

export type RecordTreatmentWhereUniqueInput = Prisma.AtLeast<{
  treatmentId?: number
  AND?: Prisma.RecordTreatmentWhereInput | Prisma.RecordTreatmentWhereInput[]
  OR?: Prisma.RecordTreatmentWhereInput[]
  NOT?: Prisma.RecordTreatmentWhereInput | Prisma.RecordTreatmentWhereInput[]
  recordId?: Prisma.IntFilter<"RecordTreatment"> | number
  treatmentName?: Prisma.StringFilter<"RecordTreatment"> | string
  treatmentDescription?: Prisma.StringNullableFilter<"RecordTreatment"> | string | null
  treatmentDate?: Prisma.DateTimeFilter<"RecordTreatment"> | Date | string
  outcome?: Prisma.StringNullableFilter<"RecordTreatment"> | string | null
  notes?: Prisma.StringNullableFilter<"RecordTreatment"> | string | null
  isActive?: Prisma.StringFilter<"RecordTreatment"> | string
  createdAt?: Prisma.DateTimeFilter<"RecordTreatment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecordTreatment"> | Date | string
  record?: Prisma.XOR<Prisma.MedicalRecordScalarRelationFilter, Prisma.MedicalRecordWhereInput>
}, "treatmentId">

export type RecordTreatmentOrderByWithAggregationInput = {
  treatmentId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  treatmentName?: Prisma.SortOrder
  treatmentDescription?: Prisma.SortOrderInput | Prisma.SortOrder
  treatmentDate?: Prisma.SortOrder
  outcome?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.RecordTreatmentCountOrderByAggregateInput
  _avg?: Prisma.RecordTreatmentAvgOrderByAggregateInput
  _max?: Prisma.RecordTreatmentMaxOrderByAggregateInput
  _min?: Prisma.RecordTreatmentMinOrderByAggregateInput
  _sum?: Prisma.RecordTreatmentSumOrderByAggregateInput
}

export type RecordTreatmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.RecordTreatmentScalarWhereWithAggregatesInput | Prisma.RecordTreatmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.RecordTreatmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RecordTreatmentScalarWhereWithAggregatesInput | Prisma.RecordTreatmentScalarWhereWithAggregatesInput[]
  treatmentId?: Prisma.IntWithAggregatesFilter<"RecordTreatment"> | number
  recordId?: Prisma.IntWithAggregatesFilter<"RecordTreatment"> | number
  treatmentName?: Prisma.StringWithAggregatesFilter<"RecordTreatment"> | string
  treatmentDescription?: Prisma.StringNullableWithAggregatesFilter<"RecordTreatment"> | string | null
  treatmentDate?: Prisma.DateTimeWithAggregatesFilter<"RecordTreatment"> | Date | string
  outcome?: Prisma.StringNullableWithAggregatesFilter<"RecordTreatment"> | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"RecordTreatment"> | string | null
  isActive?: Prisma.StringWithAggregatesFilter<"RecordTreatment"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RecordTreatment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RecordTreatment"> | Date | string
}

export type RecordTreatmentCreateInput = {
  treatmentName: string
  treatmentDescription?: string | null
  treatmentDate?: Date | string
  outcome?: string | null
  notes?: string | null
  isActive?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  record: Prisma.MedicalRecordCreateNestedOneWithoutTreatmentsInput
}

export type RecordTreatmentUncheckedCreateInput = {
  treatmentId?: number
  recordId: number
  treatmentName: string
  treatmentDescription?: string | null
  treatmentDate?: Date | string
  outcome?: string | null
  notes?: string | null
  isActive?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordTreatmentUpdateInput = {
  treatmentName?: Prisma.StringFieldUpdateOperationsInput | string
  treatmentDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  treatmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  record?: Prisma.MedicalRecordUpdateOneRequiredWithoutTreatmentsNestedInput
}

export type RecordTreatmentUncheckedUpdateInput = {
  treatmentId?: Prisma.IntFieldUpdateOperationsInput | number
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  treatmentName?: Prisma.StringFieldUpdateOperationsInput | string
  treatmentDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  treatmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordTreatmentCreateManyInput = {
  treatmentId?: number
  recordId: number
  treatmentName: string
  treatmentDescription?: string | null
  treatmentDate?: Date | string
  outcome?: string | null
  notes?: string | null
  isActive?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordTreatmentUpdateManyMutationInput = {
  treatmentName?: Prisma.StringFieldUpdateOperationsInput | string
  treatmentDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  treatmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordTreatmentUncheckedUpdateManyInput = {
  treatmentId?: Prisma.IntFieldUpdateOperationsInput | number
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  treatmentName?: Prisma.StringFieldUpdateOperationsInput | string
  treatmentDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  treatmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordTreatmentListRelationFilter = {
  every?: Prisma.RecordTreatmentWhereInput
  some?: Prisma.RecordTreatmentWhereInput
  none?: Prisma.RecordTreatmentWhereInput
}

export type RecordTreatmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RecordTreatmentCountOrderByAggregateInput = {
  treatmentId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  treatmentName?: Prisma.SortOrder
  treatmentDescription?: Prisma.SortOrder
  treatmentDate?: Prisma.SortOrder
  outcome?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecordTreatmentAvgOrderByAggregateInput = {
  treatmentId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
}

export type RecordTreatmentMaxOrderByAggregateInput = {
  treatmentId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  treatmentName?: Prisma.SortOrder
  treatmentDescription?: Prisma.SortOrder
  treatmentDate?: Prisma.SortOrder
  outcome?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecordTreatmentMinOrderByAggregateInput = {
  treatmentId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  treatmentName?: Prisma.SortOrder
  treatmentDescription?: Prisma.SortOrder
  treatmentDate?: Prisma.SortOrder
  outcome?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecordTreatmentSumOrderByAggregateInput = {
  treatmentId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
}

export type RecordTreatmentCreateNestedManyWithoutRecordInput = {
  create?: Prisma.XOR<Prisma.RecordTreatmentCreateWithoutRecordInput, Prisma.RecordTreatmentUncheckedCreateWithoutRecordInput> | Prisma.RecordTreatmentCreateWithoutRecordInput[] | Prisma.RecordTreatmentUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordTreatmentCreateOrConnectWithoutRecordInput | Prisma.RecordTreatmentCreateOrConnectWithoutRecordInput[]
  createMany?: Prisma.RecordTreatmentCreateManyRecordInputEnvelope
  connect?: Prisma.RecordTreatmentWhereUniqueInput | Prisma.RecordTreatmentWhereUniqueInput[]
}

export type RecordTreatmentUncheckedCreateNestedManyWithoutRecordInput = {
  create?: Prisma.XOR<Prisma.RecordTreatmentCreateWithoutRecordInput, Prisma.RecordTreatmentUncheckedCreateWithoutRecordInput> | Prisma.RecordTreatmentCreateWithoutRecordInput[] | Prisma.RecordTreatmentUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordTreatmentCreateOrConnectWithoutRecordInput | Prisma.RecordTreatmentCreateOrConnectWithoutRecordInput[]
  createMany?: Prisma.RecordTreatmentCreateManyRecordInputEnvelope
  connect?: Prisma.RecordTreatmentWhereUniqueInput | Prisma.RecordTreatmentWhereUniqueInput[]
}

export type RecordTreatmentUpdateManyWithoutRecordNestedInput = {
  create?: Prisma.XOR<Prisma.RecordTreatmentCreateWithoutRecordInput, Prisma.RecordTreatmentUncheckedCreateWithoutRecordInput> | Prisma.RecordTreatmentCreateWithoutRecordInput[] | Prisma.RecordTreatmentUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordTreatmentCreateOrConnectWithoutRecordInput | Prisma.RecordTreatmentCreateOrConnectWithoutRecordInput[]
  upsert?: Prisma.RecordTreatmentUpsertWithWhereUniqueWithoutRecordInput | Prisma.RecordTreatmentUpsertWithWhereUniqueWithoutRecordInput[]
  createMany?: Prisma.RecordTreatmentCreateManyRecordInputEnvelope
  set?: Prisma.RecordTreatmentWhereUniqueInput | Prisma.RecordTreatmentWhereUniqueInput[]
  disconnect?: Prisma.RecordTreatmentWhereUniqueInput | Prisma.RecordTreatmentWhereUniqueInput[]
  delete?: Prisma.RecordTreatmentWhereUniqueInput | Prisma.RecordTreatmentWhereUniqueInput[]
  connect?: Prisma.RecordTreatmentWhereUniqueInput | Prisma.RecordTreatmentWhereUniqueInput[]
  update?: Prisma.RecordTreatmentUpdateWithWhereUniqueWithoutRecordInput | Prisma.RecordTreatmentUpdateWithWhereUniqueWithoutRecordInput[]
  updateMany?: Prisma.RecordTreatmentUpdateManyWithWhereWithoutRecordInput | Prisma.RecordTreatmentUpdateManyWithWhereWithoutRecordInput[]
  deleteMany?: Prisma.RecordTreatmentScalarWhereInput | Prisma.RecordTreatmentScalarWhereInput[]
}

export type RecordTreatmentUncheckedUpdateManyWithoutRecordNestedInput = {
  create?: Prisma.XOR<Prisma.RecordTreatmentCreateWithoutRecordInput, Prisma.RecordTreatmentUncheckedCreateWithoutRecordInput> | Prisma.RecordTreatmentCreateWithoutRecordInput[] | Prisma.RecordTreatmentUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordTreatmentCreateOrConnectWithoutRecordInput | Prisma.RecordTreatmentCreateOrConnectWithoutRecordInput[]
  upsert?: Prisma.RecordTreatmentUpsertWithWhereUniqueWithoutRecordInput | Prisma.RecordTreatmentUpsertWithWhereUniqueWithoutRecordInput[]
  createMany?: Prisma.RecordTreatmentCreateManyRecordInputEnvelope
  set?: Prisma.RecordTreatmentWhereUniqueInput | Prisma.RecordTreatmentWhereUniqueInput[]
  disconnect?: Prisma.RecordTreatmentWhereUniqueInput | Prisma.RecordTreatmentWhereUniqueInput[]
  delete?: Prisma.RecordTreatmentWhereUniqueInput | Prisma.RecordTreatmentWhereUniqueInput[]
  connect?: Prisma.RecordTreatmentWhereUniqueInput | Prisma.RecordTreatmentWhereUniqueInput[]
  update?: Prisma.RecordTreatmentUpdateWithWhereUniqueWithoutRecordInput | Prisma.RecordTreatmentUpdateWithWhereUniqueWithoutRecordInput[]
  updateMany?: Prisma.RecordTreatmentUpdateManyWithWhereWithoutRecordInput | Prisma.RecordTreatmentUpdateManyWithWhereWithoutRecordInput[]
  deleteMany?: Prisma.RecordTreatmentScalarWhereInput | Prisma.RecordTreatmentScalarWhereInput[]
}

export type RecordTreatmentCreateWithoutRecordInput = {
  treatmentName: string
  treatmentDescription?: string | null
  treatmentDate?: Date | string
  outcome?: string | null
  notes?: string | null
  isActive?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordTreatmentUncheckedCreateWithoutRecordInput = {
  treatmentId?: number
  treatmentName: string
  treatmentDescription?: string | null
  treatmentDate?: Date | string
  outcome?: string | null
  notes?: string | null
  isActive?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordTreatmentCreateOrConnectWithoutRecordInput = {
  where: Prisma.RecordTreatmentWhereUniqueInput
  create: Prisma.XOR<Prisma.RecordTreatmentCreateWithoutRecordInput, Prisma.RecordTreatmentUncheckedCreateWithoutRecordInput>
}

export type RecordTreatmentCreateManyRecordInputEnvelope = {
  data: Prisma.RecordTreatmentCreateManyRecordInput | Prisma.RecordTreatmentCreateManyRecordInput[]
  skipDuplicates?: boolean
}

export type RecordTreatmentUpsertWithWhereUniqueWithoutRecordInput = {
  where: Prisma.RecordTreatmentWhereUniqueInput
  update: Prisma.XOR<Prisma.RecordTreatmentUpdateWithoutRecordInput, Prisma.RecordTreatmentUncheckedUpdateWithoutRecordInput>
  create: Prisma.XOR<Prisma.RecordTreatmentCreateWithoutRecordInput, Prisma.RecordTreatmentUncheckedCreateWithoutRecordInput>
}

export type RecordTreatmentUpdateWithWhereUniqueWithoutRecordInput = {
  where: Prisma.RecordTreatmentWhereUniqueInput
  data: Prisma.XOR<Prisma.RecordTreatmentUpdateWithoutRecordInput, Prisma.RecordTreatmentUncheckedUpdateWithoutRecordInput>
}

export type RecordTreatmentUpdateManyWithWhereWithoutRecordInput = {
  where: Prisma.RecordTreatmentScalarWhereInput
  data: Prisma.XOR<Prisma.RecordTreatmentUpdateManyMutationInput, Prisma.RecordTreatmentUncheckedUpdateManyWithoutRecordInput>
}

export type RecordTreatmentScalarWhereInput = {
  AND?: Prisma.RecordTreatmentScalarWhereInput | Prisma.RecordTreatmentScalarWhereInput[]
  OR?: Prisma.RecordTreatmentScalarWhereInput[]
  NOT?: Prisma.RecordTreatmentScalarWhereInput | Prisma.RecordTreatmentScalarWhereInput[]
  treatmentId?: Prisma.IntFilter<"RecordTreatment"> | number
  recordId?: Prisma.IntFilter<"RecordTreatment"> | number
  treatmentName?: Prisma.StringFilter<"RecordTreatment"> | string
  treatmentDescription?: Prisma.StringNullableFilter<"RecordTreatment"> | string | null
  treatmentDate?: Prisma.DateTimeFilter<"RecordTreatment"> | Date | string
  outcome?: Prisma.StringNullableFilter<"RecordTreatment"> | string | null
  notes?: Prisma.StringNullableFilter<"RecordTreatment"> | string | null
  isActive?: Prisma.StringFilter<"RecordTreatment"> | string
  createdAt?: Prisma.DateTimeFilter<"RecordTreatment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecordTreatment"> | Date | string
}

export type RecordTreatmentCreateManyRecordInput = {
  treatmentId?: number
  treatmentName: string
  treatmentDescription?: string | null
  treatmentDate?: Date | string
  outcome?: string | null
  notes?: string | null
  isActive?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordTreatmentUpdateWithoutRecordInput = {
  treatmentName?: Prisma.StringFieldUpdateOperationsInput | string
  treatmentDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  treatmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordTreatmentUncheckedUpdateWithoutRecordInput = {
  treatmentId?: Prisma.IntFieldUpdateOperationsInput | number
  treatmentName?: Prisma.StringFieldUpdateOperationsInput | string
  treatmentDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  treatmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordTreatmentUncheckedUpdateManyWithoutRecordInput = {
  treatmentId?: Prisma.IntFieldUpdateOperationsInput | number
  treatmentName?: Prisma.StringFieldUpdateOperationsInput | string
  treatmentDescription?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  treatmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  outcome?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RecordTreatmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  treatmentId?: boolean
  recordId?: boolean
  treatmentName?: boolean
  treatmentDescription?: boolean
  treatmentDate?: boolean
  outcome?: boolean
  notes?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recordTreatment"]>

export type RecordTreatmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  treatmentId?: boolean
  recordId?: boolean
  treatmentName?: boolean
  treatmentDescription?: boolean
  treatmentDate?: boolean
  outcome?: boolean
  notes?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recordTreatment"]>

export type RecordTreatmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  treatmentId?: boolean
  recordId?: boolean
  treatmentName?: boolean
  treatmentDescription?: boolean
  treatmentDate?: boolean
  outcome?: boolean
  notes?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recordTreatment"]>

export type RecordTreatmentSelectScalar = {
  treatmentId?: boolean
  recordId?: boolean
  treatmentName?: boolean
  treatmentDescription?: boolean
  treatmentDate?: boolean
  outcome?: boolean
  notes?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type RecordTreatmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"treatmentId" | "recordId" | "treatmentName" | "treatmentDescription" | "treatmentDate" | "outcome" | "notes" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["recordTreatment"]>
export type RecordTreatmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}
export type RecordTreatmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}
export type RecordTreatmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}

export type $RecordTreatmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RecordTreatment"
  objects: {
    record: Prisma.$MedicalRecordPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    treatmentId: number
    recordId: number
    treatmentName: string
    treatmentDescription: string | null
    treatmentDate: Date
    outcome: string | null
    notes: string | null
    isActive: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["recordTreatment"]>
  composites: {}
}

export type RecordTreatmentGetPayload<S extends boolean | null | undefined | RecordTreatmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload, S>

export type RecordTreatmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RecordTreatmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RecordTreatmentCountAggregateInputType | true
  }

export interface RecordTreatmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RecordTreatment'], meta: { name: 'RecordTreatment' } }
  /**
   * Find zero or one RecordTreatment that matches the filter.
   * @param {RecordTreatmentFindUniqueArgs} args - Arguments to find a RecordTreatment
   * @example
   * // Get one RecordTreatment
   * const recordTreatment = await prisma.recordTreatment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RecordTreatmentFindUniqueArgs>(args: Prisma.SelectSubset<T, RecordTreatmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RecordTreatmentClient<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RecordTreatment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RecordTreatmentFindUniqueOrThrowArgs} args - Arguments to find a RecordTreatment
   * @example
   * // Get one RecordTreatment
   * const recordTreatment = await prisma.recordTreatment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RecordTreatmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RecordTreatmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecordTreatmentClient<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecordTreatment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordTreatmentFindFirstArgs} args - Arguments to find a RecordTreatment
   * @example
   * // Get one RecordTreatment
   * const recordTreatment = await prisma.recordTreatment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RecordTreatmentFindFirstArgs>(args?: Prisma.SelectSubset<T, RecordTreatmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__RecordTreatmentClient<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecordTreatment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordTreatmentFindFirstOrThrowArgs} args - Arguments to find a RecordTreatment
   * @example
   * // Get one RecordTreatment
   * const recordTreatment = await prisma.recordTreatment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RecordTreatmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RecordTreatmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecordTreatmentClient<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RecordTreatments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordTreatmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RecordTreatments
   * const recordTreatments = await prisma.recordTreatment.findMany()
   * 
   * // Get first 10 RecordTreatments
   * const recordTreatments = await prisma.recordTreatment.findMany({ take: 10 })
   * 
   * // Only select the `treatmentId`
   * const recordTreatmentWithTreatmentIdOnly = await prisma.recordTreatment.findMany({ select: { treatmentId: true } })
   * 
   */
  findMany<T extends RecordTreatmentFindManyArgs>(args?: Prisma.SelectSubset<T, RecordTreatmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RecordTreatment.
   * @param {RecordTreatmentCreateArgs} args - Arguments to create a RecordTreatment.
   * @example
   * // Create one RecordTreatment
   * const RecordTreatment = await prisma.recordTreatment.create({
   *   data: {
   *     // ... data to create a RecordTreatment
   *   }
   * })
   * 
   */
  create<T extends RecordTreatmentCreateArgs>(args: Prisma.SelectSubset<T, RecordTreatmentCreateArgs<ExtArgs>>): Prisma.Prisma__RecordTreatmentClient<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RecordTreatments.
   * @param {RecordTreatmentCreateManyArgs} args - Arguments to create many RecordTreatments.
   * @example
   * // Create many RecordTreatments
   * const recordTreatment = await prisma.recordTreatment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RecordTreatmentCreateManyArgs>(args?: Prisma.SelectSubset<T, RecordTreatmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RecordTreatments and returns the data saved in the database.
   * @param {RecordTreatmentCreateManyAndReturnArgs} args - Arguments to create many RecordTreatments.
   * @example
   * // Create many RecordTreatments
   * const recordTreatment = await prisma.recordTreatment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RecordTreatments and only return the `treatmentId`
   * const recordTreatmentWithTreatmentIdOnly = await prisma.recordTreatment.createManyAndReturn({
   *   select: { treatmentId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RecordTreatmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RecordTreatmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RecordTreatment.
   * @param {RecordTreatmentDeleteArgs} args - Arguments to delete one RecordTreatment.
   * @example
   * // Delete one RecordTreatment
   * const RecordTreatment = await prisma.recordTreatment.delete({
   *   where: {
   *     // ... filter to delete one RecordTreatment
   *   }
   * })
   * 
   */
  delete<T extends RecordTreatmentDeleteArgs>(args: Prisma.SelectSubset<T, RecordTreatmentDeleteArgs<ExtArgs>>): Prisma.Prisma__RecordTreatmentClient<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RecordTreatment.
   * @param {RecordTreatmentUpdateArgs} args - Arguments to update one RecordTreatment.
   * @example
   * // Update one RecordTreatment
   * const recordTreatment = await prisma.recordTreatment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RecordTreatmentUpdateArgs>(args: Prisma.SelectSubset<T, RecordTreatmentUpdateArgs<ExtArgs>>): Prisma.Prisma__RecordTreatmentClient<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RecordTreatments.
   * @param {RecordTreatmentDeleteManyArgs} args - Arguments to filter RecordTreatments to delete.
   * @example
   * // Delete a few RecordTreatments
   * const { count } = await prisma.recordTreatment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RecordTreatmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, RecordTreatmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecordTreatments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordTreatmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RecordTreatments
   * const recordTreatment = await prisma.recordTreatment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RecordTreatmentUpdateManyArgs>(args: Prisma.SelectSubset<T, RecordTreatmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecordTreatments and returns the data updated in the database.
   * @param {RecordTreatmentUpdateManyAndReturnArgs} args - Arguments to update many RecordTreatments.
   * @example
   * // Update many RecordTreatments
   * const recordTreatment = await prisma.recordTreatment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RecordTreatments and only return the `treatmentId`
   * const recordTreatmentWithTreatmentIdOnly = await prisma.recordTreatment.updateManyAndReturn({
   *   select: { treatmentId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RecordTreatmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RecordTreatmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RecordTreatment.
   * @param {RecordTreatmentUpsertArgs} args - Arguments to update or create a RecordTreatment.
   * @example
   * // Update or create a RecordTreatment
   * const recordTreatment = await prisma.recordTreatment.upsert({
   *   create: {
   *     // ... data to create a RecordTreatment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RecordTreatment we want to update
   *   }
   * })
   */
  upsert<T extends RecordTreatmentUpsertArgs>(args: Prisma.SelectSubset<T, RecordTreatmentUpsertArgs<ExtArgs>>): Prisma.Prisma__RecordTreatmentClient<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RecordTreatments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordTreatmentCountArgs} args - Arguments to filter RecordTreatments to count.
   * @example
   * // Count the number of RecordTreatments
   * const count = await prisma.recordTreatment.count({
   *   where: {
   *     // ... the filter for the RecordTreatments we want to count
   *   }
   * })
  **/
  count<T extends RecordTreatmentCountArgs>(
    args?: Prisma.Subset<T, RecordTreatmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RecordTreatmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RecordTreatment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordTreatmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RecordTreatmentAggregateArgs>(args: Prisma.Subset<T, RecordTreatmentAggregateArgs>): Prisma.PrismaPromise<GetRecordTreatmentAggregateType<T>>

  /**
   * Group by RecordTreatment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordTreatmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RecordTreatmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RecordTreatmentGroupByArgs['orderBy'] }
      : { orderBy?: RecordTreatmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RecordTreatmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRecordTreatmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RecordTreatment model
 */
readonly fields: RecordTreatmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RecordTreatment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RecordTreatmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  record<T extends Prisma.MedicalRecordDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MedicalRecordDefaultArgs<ExtArgs>>): Prisma.Prisma__MedicalRecordClient<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RecordTreatment model
 */
export interface RecordTreatmentFieldRefs {
  readonly treatmentId: Prisma.FieldRef<"RecordTreatment", 'Int'>
  readonly recordId: Prisma.FieldRef<"RecordTreatment", 'Int'>
  readonly treatmentName: Prisma.FieldRef<"RecordTreatment", 'String'>
  readonly treatmentDescription: Prisma.FieldRef<"RecordTreatment", 'String'>
  readonly treatmentDate: Prisma.FieldRef<"RecordTreatment", 'DateTime'>
  readonly outcome: Prisma.FieldRef<"RecordTreatment", 'String'>
  readonly notes: Prisma.FieldRef<"RecordTreatment", 'String'>
  readonly isActive: Prisma.FieldRef<"RecordTreatment", 'String'>
  readonly createdAt: Prisma.FieldRef<"RecordTreatment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RecordTreatment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RecordTreatment findUnique
 */
export type RecordTreatmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentInclude<ExtArgs> | null
  /**
   * Filter, which RecordTreatment to fetch.
   */
  where: Prisma.RecordTreatmentWhereUniqueInput
}

/**
 * RecordTreatment findUniqueOrThrow
 */
export type RecordTreatmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentInclude<ExtArgs> | null
  /**
   * Filter, which RecordTreatment to fetch.
   */
  where: Prisma.RecordTreatmentWhereUniqueInput
}

/**
 * RecordTreatment findFirst
 */
export type RecordTreatmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentInclude<ExtArgs> | null
  /**
   * Filter, which RecordTreatment to fetch.
   */
  where?: Prisma.RecordTreatmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordTreatments to fetch.
   */
  orderBy?: Prisma.RecordTreatmentOrderByWithRelationInput | Prisma.RecordTreatmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecordTreatments.
   */
  cursor?: Prisma.RecordTreatmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordTreatments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordTreatments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecordTreatments.
   */
  distinct?: Prisma.RecordTreatmentScalarFieldEnum | Prisma.RecordTreatmentScalarFieldEnum[]
}

/**
 * RecordTreatment findFirstOrThrow
 */
export type RecordTreatmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentInclude<ExtArgs> | null
  /**
   * Filter, which RecordTreatment to fetch.
   */
  where?: Prisma.RecordTreatmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordTreatments to fetch.
   */
  orderBy?: Prisma.RecordTreatmentOrderByWithRelationInput | Prisma.RecordTreatmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecordTreatments.
   */
  cursor?: Prisma.RecordTreatmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordTreatments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordTreatments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecordTreatments.
   */
  distinct?: Prisma.RecordTreatmentScalarFieldEnum | Prisma.RecordTreatmentScalarFieldEnum[]
}

/**
 * RecordTreatment findMany
 */
export type RecordTreatmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentInclude<ExtArgs> | null
  /**
   * Filter, which RecordTreatments to fetch.
   */
  where?: Prisma.RecordTreatmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordTreatments to fetch.
   */
  orderBy?: Prisma.RecordTreatmentOrderByWithRelationInput | Prisma.RecordTreatmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RecordTreatments.
   */
  cursor?: Prisma.RecordTreatmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordTreatments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordTreatments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecordTreatments.
   */
  distinct?: Prisma.RecordTreatmentScalarFieldEnum | Prisma.RecordTreatmentScalarFieldEnum[]
}

/**
 * RecordTreatment create
 */
export type RecordTreatmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentInclude<ExtArgs> | null
  /**
   * The data needed to create a RecordTreatment.
   */
  data: Prisma.XOR<Prisma.RecordTreatmentCreateInput, Prisma.RecordTreatmentUncheckedCreateInput>
}

/**
 * RecordTreatment createMany
 */
export type RecordTreatmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RecordTreatments.
   */
  data: Prisma.RecordTreatmentCreateManyInput | Prisma.RecordTreatmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RecordTreatment createManyAndReturn
 */
export type RecordTreatmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * The data used to create many RecordTreatments.
   */
  data: Prisma.RecordTreatmentCreateManyInput | Prisma.RecordTreatmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RecordTreatment update
 */
export type RecordTreatmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentInclude<ExtArgs> | null
  /**
   * The data needed to update a RecordTreatment.
   */
  data: Prisma.XOR<Prisma.RecordTreatmentUpdateInput, Prisma.RecordTreatmentUncheckedUpdateInput>
  /**
   * Choose, which RecordTreatment to update.
   */
  where: Prisma.RecordTreatmentWhereUniqueInput
}

/**
 * RecordTreatment updateMany
 */
export type RecordTreatmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RecordTreatments.
   */
  data: Prisma.XOR<Prisma.RecordTreatmentUpdateManyMutationInput, Prisma.RecordTreatmentUncheckedUpdateManyInput>
  /**
   * Filter which RecordTreatments to update
   */
  where?: Prisma.RecordTreatmentWhereInput
  /**
   * Limit how many RecordTreatments to update.
   */
  limit?: number
}

/**
 * RecordTreatment updateManyAndReturn
 */
export type RecordTreatmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * The data used to update RecordTreatments.
   */
  data: Prisma.XOR<Prisma.RecordTreatmentUpdateManyMutationInput, Prisma.RecordTreatmentUncheckedUpdateManyInput>
  /**
   * Filter which RecordTreatments to update
   */
  where?: Prisma.RecordTreatmentWhereInput
  /**
   * Limit how many RecordTreatments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RecordTreatment upsert
 */
export type RecordTreatmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentInclude<ExtArgs> | null
  /**
   * The filter to search for the RecordTreatment to update in case it exists.
   */
  where: Prisma.RecordTreatmentWhereUniqueInput
  /**
   * In case the RecordTreatment found by the `where` argument doesn't exist, create a new RecordTreatment with this data.
   */
  create: Prisma.XOR<Prisma.RecordTreatmentCreateInput, Prisma.RecordTreatmentUncheckedCreateInput>
  /**
   * In case the RecordTreatment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RecordTreatmentUpdateInput, Prisma.RecordTreatmentUncheckedUpdateInput>
}

/**
 * RecordTreatment delete
 */
export type RecordTreatmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentInclude<ExtArgs> | null
  /**
   * Filter which RecordTreatment to delete.
   */
  where: Prisma.RecordTreatmentWhereUniqueInput
}

/**
 * RecordTreatment deleteMany
 */
export type RecordTreatmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecordTreatments to delete
   */
  where?: Prisma.RecordTreatmentWhereInput
  /**
   * Limit how many RecordTreatments to delete.
   */
  limit?: number
}

/**
 * RecordTreatment without action
 */
export type RecordTreatmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentInclude<ExtArgs> | null
}
