
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Role'
export type * from './models/User'
export type * from './models/AuthSession'
export type * from './models/Patient'
export type * from './models/MedicalRecord'
export type * from './models/RecordDiagnosis'
export type * from './models/RecordPrescription'
export type * from './models/RecordTreatment'
export type * from './models/Appointment'
export type * from './models/InventorySupply'
export type * from './models/AuditLog'
export type * from './commonInputTypes'