-- PostgreSQL schema for the EHR foundation
-- Run this script first.

CREATE TABLE roles (
    role_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_name    VARCHAR(50) NOT NULL,
    description  VARCHAR(255),
    is_system    CHAR(1) DEFAULT 'N' NOT NULL,
    created_at   TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id),
    CONSTRAINT uq_roles_role_name UNIQUE (role_name),
    CONSTRAINT ck_roles_is_system CHECK (is_system IN ('Y', 'N'))
);

CREATE TABLE users (
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_id         BIGINT NOT NULL,
    username        VARCHAR(50) NOT NULL,
    display_name    VARCHAR(120) NOT NULL,
    email           VARCHAR(255),
    password_hash   VARCHAR(255) NOT NULL,
    password_salt   VARCHAR(255) NOT NULL,
    is_active       CHAR(1) DEFAULT 'Y' NOT NULL,
    failed_login_count BIGINT DEFAULT 0 NOT NULL,
    locked_until    TIMESTAMP,
    mfa_enabled     CHAR(1) DEFAULT 'N' NOT NULL,
    mfa_secret      VARCHAR(64),
    last_login_at   TIMESTAMP,
    created_at      TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at      TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (role_id),
    CONSTRAINT ck_users_is_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT ck_users_mfa_enabled CHECK (mfa_enabled IN ('Y', 'N'))
);

CREATE TABLE auth_sessions (
    session_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id          BIGINT NOT NULL,
    jti              VARCHAR(64) NOT NULL,
    expires_at       TIMESTAMP NOT NULL,
    revoked_at       TIMESTAMP,
    created_at       TIMESTAMP DEFAULT NOW() NOT NULL,
    last_seen_at     TIMESTAMP DEFAULT NOW() NOT NULL,
    ip_address       VARCHAR(45),
    user_agent       VARCHAR(255),
    CONSTRAINT pk_auth_sessions PRIMARY KEY (session_id),
    CONSTRAINT uq_auth_sessions_jti UNIQUE (jti),
    CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE patients (
    patient_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    mrn             VARCHAR(30) NOT NULL,
    first_name      VARCHAR(80) NOT NULL,
    last_name       VARCHAR(80) NOT NULL,
    date_of_birth   DATE NOT NULL,
    sex             VARCHAR(20) NOT NULL,
    phone_number    VARCHAR(30),
    email           VARCHAR(255),
    address_line1   VARCHAR(255),
    address_line2   VARCHAR(255),
    city            VARCHAR(80),
    region          VARCHAR(80),
    country         VARCHAR(80) DEFAULT 'Ghana' NOT NULL,
    is_active       CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at      TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_patients PRIMARY KEY (patient_id),
    CONSTRAINT uq_patients_mrn UNIQUE (mrn),
    CONSTRAINT uq_patients_email UNIQUE (email),
    CONSTRAINT ck_patients_sex CHECK (sex IN ('Male', 'Female', 'Other')),
    CONSTRAINT ck_patients_is_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE medical_records (
    record_id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    patient_id          BIGINT NOT NULL,
    created_by_user_id  BIGINT NOT NULL,
    record_type         VARCHAR(50) NOT NULL,
    title               VARCHAR(150) NOT NULL,
    clinical_note       TEXT NOT NULL,
    record_status       VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    encounter_date      TIMESTAMP DEFAULT NOW() NOT NULL,
    created_at          TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at          TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_medical_records PRIMARY KEY (record_id),
    CONSTRAINT fk_medical_records_patient FOREIGN KEY (patient_id) REFERENCES patients (patient_id),
    CONSTRAINT fk_medical_records_user FOREIGN KEY (created_by_user_id) REFERENCES users (user_id),
    CONSTRAINT ck_medical_records_type CHECK (record_type IN ('Encounter', 'Diagnosis', 'Medication', 'Lab Result', 'Imaging', 'Procedure', 'Note')),
    CONSTRAINT ck_medical_records_status CHECK (record_status IN ('ACTIVE', 'AMENDED', 'VOID'))
);

CREATE TABLE record_diagnoses (
    diagnosis_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    record_id         BIGINT NOT NULL,
    diagnosis_name    VARCHAR(500) NOT NULL,
    icd10_code        VARCHAR(255),
    diagnosis_status  VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    is_primary        CHAR(1) DEFAULT 'N' NOT NULL,
    is_active         CHAR(1) DEFAULT 'Y' NOT NULL,
    diagnosed_at      TIMESTAMP DEFAULT NOW() NOT NULL,
    created_at        TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at        TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_record_diagnoses PRIMARY KEY (diagnosis_id),
    CONSTRAINT fk_record_diagnoses_record FOREIGN KEY (record_id) REFERENCES medical_records (record_id),
    CONSTRAINT ck_record_diagnoses_status CHECK (diagnosis_status IN ('ACTIVE', 'RESOLVED', 'RULE_OUT')),
    CONSTRAINT ck_record_diagnoses_primary CHECK (is_primary IN ('Y', 'N')),
    CONSTRAINT ck_record_diagnoses_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE record_prescriptions (
    prescription_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    record_id            BIGINT NOT NULL,
    medication_name      VARCHAR(500) NOT NULL,
    dosage               VARCHAR(255),
    frequency            VARCHAR(255),
    route                VARCHAR(255),
    duration_days        BIGINT,
    instructions         TEXT,
    prescription_status  VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    is_active            CHAR(1) DEFAULT 'Y' NOT NULL,
    prescribed_at        TIMESTAMP DEFAULT NOW() NOT NULL,
    created_at           TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at           TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_record_prescriptions PRIMARY KEY (prescription_id),
    CONSTRAINT fk_record_prescriptions_record FOREIGN KEY (record_id) REFERENCES medical_records (record_id),
    CONSTRAINT ck_record_prescriptions_status CHECK (prescription_status IN ('ACTIVE', 'DISCONTINUED', 'COMPLETED')),
    CONSTRAINT ck_record_prescriptions_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE record_treatments (
    treatment_id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    record_id              BIGINT NOT NULL,
    treatment_name         VARCHAR(500) NOT NULL,
    treatment_description  TEXT,
    treatment_date         TIMESTAMP DEFAULT NOW() NOT NULL,
    outcome                TEXT,
    notes                  TEXT,
    is_active              CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at             TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at             TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_record_treatments PRIMARY KEY (treatment_id),
    CONSTRAINT fk_record_treatments_record FOREIGN KEY (record_id) REFERENCES medical_records (record_id),
    CONSTRAINT ck_record_treatments_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE appointments (
    appointment_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    patient_id          BIGINT NOT NULL,
    scheduled_by_user_id BIGINT NOT NULL,
    clinician_user_id   BIGINT,
    appointment_date    TIMESTAMP NOT NULL,
    appointment_type    VARCHAR(50) NOT NULL,
    status              VARCHAR(20) DEFAULT 'SCHEDULED' NOT NULL,
    reason              VARCHAR(255),
    location            VARCHAR(120),
    notes               TEXT,
    created_at          TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at          TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_appointments PRIMARY KEY (appointment_id),
    CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients (patient_id),
    CONSTRAINT fk_appointments_scheduler FOREIGN KEY (scheduled_by_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_appointments_clinician FOREIGN KEY (clinician_user_id) REFERENCES users (user_id),
    CONSTRAINT ck_appointments_status CHECK (status IN ('SCHEDULED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    CONSTRAINT ck_appointments_type CHECK (appointment_type IN ('Consultation', 'Follow-up', 'Procedure', 'Telehealth', 'Lab Review', 'Referral'))
);

CREATE TABLE audit_logs (
    audit_log_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT,
    action_type     VARCHAR(60) NOT NULL,
    entity_name     VARCHAR(60) NOT NULL,
    entity_id       VARCHAR(60) NOT NULL,
    details         TEXT,
    ip_address      VARCHAR(45),
    created_at      TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (audit_log_id),
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT ck_audit_logs_action CHECK (action_type IN ('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'VIEW', 'EXPORT', 'APPROVE', 'REVOKE', 'LOCKOUT', 'MFA_FAILED', 'UNAUTHORIZED'))
);

CREATE INDEX ix_users_role_id ON users (role_id);
CREATE INDEX ix_users_username ON users (username);
CREATE INDEX ix_auth_sessions_user_id ON auth_sessions (user_id);
CREATE INDEX ix_auth_sessions_jti ON auth_sessions (jti);
CREATE INDEX ix_auth_sessions_expires_at ON auth_sessions (expires_at);
CREATE INDEX ix_patients_last_name_first_name ON patients (last_name, first_name);
CREATE INDEX ix_patients_mrn ON patients (mrn);
CREATE INDEX ix_medical_records_patient_id ON medical_records (patient_id);
CREATE INDEX ix_medical_records_created_by_user_id ON medical_records (created_by_user_id);
CREATE INDEX ix_medical_records_record_type ON medical_records (record_type);
CREATE INDEX ix_record_diagnoses_record_id ON record_diagnoses (record_id);
CREATE INDEX ix_record_prescriptions_record_id ON record_prescriptions (record_id);
CREATE INDEX ix_record_treatments_record_id ON record_treatments (record_id);
CREATE INDEX ix_appointments_patient_id ON appointments (patient_id);
CREATE INDEX ix_appointments_date_status ON appointments (appointment_date, status);
CREATE INDEX ix_appointments_clinician_user_id ON appointments (clinician_user_id);
CREATE INDEX ix_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX ix_audit_logs_created_at ON audit_logs (created_at);
CREATE INDEX ix_audit_logs_entity ON audit_logs (entity_name, entity_id);
