-- Oracle Database schema for the EHR foundation
-- Run this script first.

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF3';

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE audit_logs CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE record_treatments CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE record_prescriptions CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE record_diagnoses CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE medical_records CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE appointments CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE patients CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE roles CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE roles (
    role_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_name    VARCHAR2(50 CHAR) NOT NULL,
    description  VARCHAR2(255 CHAR),
    is_system    CHAR(1) DEFAULT 'N' NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id),
    CONSTRAINT uq_roles_role_name UNIQUE (role_name),
    CONSTRAINT ck_roles_is_system CHECK (is_system IN ('Y', 'N'))
);

CREATE TABLE users (
    user_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_id         NUMBER NOT NULL,
    username        VARCHAR2(50 CHAR) NOT NULL,
    display_name    VARCHAR2(120 CHAR) NOT NULL,
    email           VARCHAR2(255 CHAR),
    password_hash   VARCHAR2(255 CHAR) NOT NULL,
    password_salt   VARCHAR2(255 CHAR) NOT NULL,
    is_active       CHAR(1) DEFAULT 'Y' NOT NULL,
    failed_login_count NUMBER DEFAULT 0 NOT NULL,
    locked_until    TIMESTAMP,
    mfa_enabled     CHAR(1) DEFAULT 'N' NOT NULL,
    mfa_secret      VARCHAR2(64 CHAR),
    last_login_at   TIMESTAMP,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (role_id),
    CONSTRAINT ck_users_is_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT ck_users_mfa_enabled CHECK (mfa_enabled IN ('Y', 'N'))
);

CREATE TABLE auth_sessions (
    session_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id          NUMBER NOT NULL,
    jti              VARCHAR2(64 CHAR) NOT NULL,
    expires_at       TIMESTAMP NOT NULL,
    revoked_at       TIMESTAMP,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    last_seen_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ip_address       VARCHAR2(45 CHAR),
    user_agent       VARCHAR2(255 CHAR),
    CONSTRAINT pk_auth_sessions PRIMARY KEY (session_id),
    CONSTRAINT uq_auth_sessions_jti UNIQUE (jti),
    CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE patients (
    patient_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    mrn             VARCHAR2(30 CHAR) NOT NULL,
    first_name      VARCHAR2(80 CHAR) NOT NULL,
    last_name       VARCHAR2(80 CHAR) NOT NULL,
    date_of_birth   DATE NOT NULL,
    sex             VARCHAR2(20 CHAR) NOT NULL,
    phone_number    VARCHAR2(30 CHAR),
    email           VARCHAR2(255 CHAR),
    address_line1   VARCHAR2(255 CHAR),
    address_line2   VARCHAR2(255 CHAR),
    city            VARCHAR2(80 CHAR),
    region          VARCHAR2(80 CHAR),
    country         VARCHAR2(80 CHAR) DEFAULT 'Ghana' NOT NULL,
    is_active       CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_patients PRIMARY KEY (patient_id),
    CONSTRAINT uq_patients_mrn UNIQUE (mrn),
    CONSTRAINT uq_patients_email UNIQUE (email),
    CONSTRAINT ck_patients_sex CHECK (sex IN ('Male', 'Female', 'Other')),
    CONSTRAINT ck_patients_is_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE medical_records (
    record_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    patient_id          NUMBER NOT NULL,
    created_by_user_id  NUMBER NOT NULL,
    record_type         VARCHAR2(50 CHAR) NOT NULL,
    title               VARCHAR2(150 CHAR) NOT NULL,
    clinical_note       CLOB NOT NULL,
    record_status       VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    encounter_date      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_medical_records PRIMARY KEY (record_id),
    CONSTRAINT fk_medical_records_patient FOREIGN KEY (patient_id) REFERENCES patients (patient_id),
    CONSTRAINT fk_medical_records_user FOREIGN KEY (created_by_user_id) REFERENCES users (user_id),
    CONSTRAINT ck_medical_records_type CHECK (record_type IN ('Encounter', 'Diagnosis', 'Medication', 'Lab Result', 'Imaging', 'Procedure', 'Note')),
    CONSTRAINT ck_medical_records_status CHECK (record_status IN ('ACTIVE', 'AMENDED', 'VOID'))
);

CREATE TABLE record_diagnoses (
    diagnosis_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id         NUMBER NOT NULL,
    diagnosis_name    VARCHAR2(500 CHAR) NOT NULL,
    icd10_code        VARCHAR2(255 CHAR),
    diagnosis_status  VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    is_primary        CHAR(1) DEFAULT 'N' NOT NULL,
    is_active         CHAR(1) DEFAULT 'Y' NOT NULL,
    diagnosed_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_record_diagnoses PRIMARY KEY (diagnosis_id),
    CONSTRAINT fk_record_diagnoses_record FOREIGN KEY (record_id) REFERENCES medical_records (record_id),
    CONSTRAINT ck_record_diagnoses_status CHECK (diagnosis_status IN ('ACTIVE', 'RESOLVED', 'RULE_OUT')),
    CONSTRAINT ck_record_diagnoses_primary CHECK (is_primary IN ('Y', 'N')),
    CONSTRAINT ck_record_diagnoses_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE record_prescriptions (
    prescription_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id            NUMBER NOT NULL,
    medication_name      VARCHAR2(500 CHAR) NOT NULL,
    dosage               VARCHAR2(255 CHAR),
    frequency            VARCHAR2(255 CHAR),
    route                VARCHAR2(255 CHAR),
    duration_days        NUMBER,
    instructions         CLOB,
    prescription_status  VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    is_active            CHAR(1) DEFAULT 'Y' NOT NULL,
    prescribed_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_record_prescriptions PRIMARY KEY (prescription_id),
    CONSTRAINT fk_record_prescriptions_record FOREIGN KEY (record_id) REFERENCES medical_records (record_id),
    CONSTRAINT ck_record_prescriptions_status CHECK (prescription_status IN ('ACTIVE', 'DISCONTINUED', 'COMPLETED')),
    CONSTRAINT ck_record_prescriptions_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE record_treatments (
    treatment_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id              NUMBER NOT NULL,
    treatment_name         VARCHAR2(500 CHAR) NOT NULL,
    treatment_description  CLOB,
    treatment_date         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    outcome                CLOB,
    notes                  CLOB,
    is_active              CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_record_treatments PRIMARY KEY (treatment_id),
    CONSTRAINT fk_record_treatments_record FOREIGN KEY (record_id) REFERENCES medical_records (record_id),
    CONSTRAINT ck_record_treatments_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE appointments (
    appointment_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    patient_id          NUMBER NOT NULL,
    scheduled_by_user_id NUMBER NOT NULL,
    clinician_user_id   NUMBER,
    appointment_date    TIMESTAMP NOT NULL,
    appointment_type    VARCHAR2(50 CHAR) NOT NULL,
    status              VARCHAR2(20 CHAR) DEFAULT 'SCHEDULED' NOT NULL,
    reason              VARCHAR2(255 CHAR),
    location            VARCHAR2(120 CHAR),
    notes               CLOB,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_appointments PRIMARY KEY (appointment_id),
    CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients (patient_id),
    CONSTRAINT fk_appointments_scheduler FOREIGN KEY (scheduled_by_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_appointments_clinician FOREIGN KEY (clinician_user_id) REFERENCES users (user_id),
    CONSTRAINT ck_appointments_status CHECK (status IN ('SCHEDULED', 'CHECKED_IN', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    CONSTRAINT ck_appointments_type CHECK (appointment_type IN ('Consultation', 'Follow-up', 'Procedure', 'Telehealth', 'Lab Review', 'Referral'))
);

CREATE TABLE audit_logs (
    audit_log_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id         NUMBER,
    action_type     VARCHAR2(60 CHAR) NOT NULL,
    entity_name     VARCHAR2(60 CHAR) NOT NULL,
    entity_id       VARCHAR2(60 CHAR) NOT NULL,
    details         CLOB,
    ip_address      VARCHAR2(45 CHAR),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (audit_log_id),
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT ck_audit_logs_action CHECK (action_type IN ('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'VIEW', 'EXPORT', 'APPROVE', 'REVOKE', 'LOCKOUT', 'MFA_FAILED', 'UNAUTHORIZED'))
);

CREATE INDEX ix_users_role_id ON users (role_id);
CREATE INDEX ix_users_username ON users (username);
CREATE INDEX ix_auth_sessions_user_id ON auth_sessions (user_id);
CREATE INDEX ix_auth_sessions_jti ON auth_sessions (jti);
CREATE INDEX ix_auth_sessions_expires_at ON auth_sessions (expires_at);
CREATE INDEX ix_patients_last_name_first_name ON patients (last_name, first_name);
CREATE INDEX ix_patients_mrn ON patients (mrn);
CREATE INDEX ix_medical_records_patient_id ON medical_records (patient_id);
CREATE INDEX ix_medical_records_created_by_user_id ON medical_records (created_by_user_id);
CREATE INDEX ix_medical_records_record_type ON medical_records (record_type);
CREATE INDEX ix_record_diagnoses_record_id ON record_diagnoses (record_id);
CREATE INDEX ix_record_prescriptions_record_id ON record_prescriptions (record_id);
CREATE INDEX ix_record_treatments_record_id ON record_treatments (record_id);
CREATE INDEX ix_appointments_patient_id ON appointments (patient_id);
CREATE INDEX ix_appointments_date_status ON appointments (appointment_date, status);
CREATE INDEX ix_appointments_clinician_user_id ON appointments (clinician_user_id);
CREATE INDEX ix_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX ix_audit_logs_created_at ON audit_logs (created_at);
CREATE INDEX ix_audit_logs_entity ON audit_logs (entity_name, entity_id);
