-- PostgreSQL teardown script

DROP TABLE IF EXISTS auth_sessions CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS record_treatments CASCADE;
DROP TABLE IF EXISTS record_prescriptions CASCADE;
DROP TABLE IF EXISTS record_diagnoses CASCADE;
DROP TABLE IF EXISTS medical_records CASCADE;
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS patients CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
