-- Security, audit, MFA, lockout, and encrypted clinical-data support.
-- Run this on existing databases created before Phase 9-13.

ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF3';

ALTER TABLE users ADD failed_login_count NUMBER DEFAULT 0 NOT NULL;
ALTER TABLE users ADD locked_until TIMESTAMP;
ALTER TABLE users ADD mfa_enabled CHAR(1) DEFAULT 'N' NOT NULL;
ALTER TABLE users ADD mfa_secret VARCHAR2(64 CHAR);
ALTER TABLE users ADD CONSTRAINT ck_users_mfa_enabled CHECK (mfa_enabled IN ('Y', 'N'));

ALTER TABLE audit_logs DROP CONSTRAINT ck_audit_logs_action;
ALTER TABLE audit_logs ADD CONSTRAINT ck_audit_logs_action CHECK (
    action_type IN ('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'VIEW', 'EXPORT', 'APPROVE', 'REVOKE', 'LOCKOUT', 'MFA_FAILED', 'UNAUTHORIZED')
);

CREATE TABLE record_diagnoses (
    diagnosis_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id         NUMBER NOT NULL,
    diagnosis_name    VARCHAR2(500 CHAR) NOT NULL,
    icd10_code        VARCHAR2(255 CHAR),
    diagnosis_status  VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    is_primary        CHAR(1) DEFAULT 'N' NOT NULL,
    is_active         CHAR(1) DEFAULT 'Y' NOT NULL,
    diagnosed_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_record_diagnoses PRIMARY KEY (diagnosis_id),
    CONSTRAINT fk_record_diagnoses_record FOREIGN KEY (record_id) REFERENCES medical_records (record_id),
    CONSTRAINT ck_record_diagnoses_status CHECK (diagnosis_status IN ('ACTIVE', 'RESOLVED', 'RULE_OUT')),
    CONSTRAINT ck_record_diagnoses_primary CHECK (is_primary IN ('Y', 'N')),
    CONSTRAINT ck_record_diagnoses_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE record_prescriptions (
    prescription_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id            NUMBER NOT NULL,
    medication_name      VARCHAR2(500 CHAR) NOT NULL,
    dosage               VARCHAR2(255 CHAR),
    frequency            VARCHAR2(255 CHAR),
    route                VARCHAR2(255 CHAR),
    duration_days        NUMBER,
    instructions         CLOB,
    prescription_status  VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    is_active            CHAR(1) DEFAULT 'Y' NOT NULL,
    prescribed_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_record_prescriptions PRIMARY KEY (prescription_id),
    CONSTRAINT fk_record_prescriptions_record FOREIGN KEY (record_id) REFERENCES medical_records (record_id),
    CONSTRAINT ck_record_prescriptions_status CHECK (prescription_status IN ('ACTIVE', 'DISCONTINUED', 'COMPLETED')),
    CONSTRAINT ck_record_prescriptions_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE record_treatments (
    treatment_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id              NUMBER NOT NULL,
    treatment_name         VARCHAR2(500 CHAR) NOT NULL,
    treatment_description  CLOB,
    treatment_date         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    outcome                CLOB,
    notes                  CLOB,
    is_active              CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_record_treatments PRIMARY KEY (treatment_id),
    CONSTRAINT fk_record_treatments_record FOREIGN KEY (record_id) REFERENCES medical_records (record_id),
    CONSTRAINT ck_record_treatments_active CHECK (is_active IN ('Y', 'N'))
);

CREATE INDEX ix_record_diagnoses_record_id ON record_diagnoses (record_id);
CREATE INDEX ix_record_prescriptions_record_id ON record_prescriptions (record_id);
CREATE INDEX ix_record_treatments_record_id ON record_treatments (record_id);
