
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `InventorySupply` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model InventorySupply
 * 
 */
export type InventorySupplyModel = runtime.Types.Result.DefaultSelection<Prisma.$InventorySupplyPayload>

export type AggregateInventorySupply = {
  _count: InventorySupplyCountAggregateOutputType | null
  _avg: InventorySupplyAvgAggregateOutputType | null
  _sum: InventorySupplySumAggregateOutputType | null
  _min: InventorySupplyMinAggregateOutputType | null
  _max: InventorySupplyMaxAggregateOutputType | null
}

export type InventorySupplyAvgAggregateOutputType = {
  supplyId: number | null
  quantity: number | null
  reorderLevel: number | null
  unitCost: runtime.Decimal | null
}

export type InventorySupplySumAggregateOutputType = {
  supplyId: number | null
  quantity: number | null
  reorderLevel: number | null
  unitCost: runtime.Decimal | null
}

export type InventorySupplyMinAggregateOutputType = {
  supplyId: number | null
  name: string | null
  category: string | null
  quantity: number | null
  unit: string | null
  reorderLevel: number | null
  unitCost: runtime.Decimal | null
  expiryDate: Date | null
  batchNumber: string | null
  manufacturer: string | null
  notes: string | null
  isActive: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type InventorySupplyMaxAggregateOutputType = {
  supplyId: number | null
  name: string | null
  category: string | null
  quantity: number | null
  unit: string | null
  reorderLevel: number | null
  unitCost: runtime.Decimal | null
  expiryDate: Date | null
  batchNumber: string | null
  manufacturer: string | null
  notes: string | null
  isActive: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type InventorySupplyCountAggregateOutputType = {
  supplyId: number
  name: number
  category: number
  quantity: number
  unit: number
  reorderLevel: number
  unitCost: number
  expiryDate: number
  batchNumber: number
  manufacturer: number
  notes: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type InventorySupplyAvgAggregateInputType = {
  supplyId?: true
  quantity?: true
  reorderLevel?: true
  unitCost?: true
}

export type InventorySupplySumAggregateInputType = {
  supplyId?: true
  quantity?: true
  reorderLevel?: true
  unitCost?: true
}

export type InventorySupplyMinAggregateInputType = {
  supplyId?: true
  name?: true
  category?: true
  quantity?: true
  unit?: true
  reorderLevel?: true
  unitCost?: true
  expiryDate?: true
  batchNumber?: true
  manufacturer?: true
  notes?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type InventorySupplyMaxAggregateInputType = {
  supplyId?: true
  name?: true
  category?: true
  quantity?: true
  unit?: true
  reorderLevel?: true
  unitCost?: true
  expiryDate?: true
  batchNumber?: true
  manufacturer?: true
  notes?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type InventorySupplyCountAggregateInputType = {
  supplyId?: true
  name?: true
  category?: true
  quantity?: true
  unit?: true
  reorderLevel?: true
  unitCost?: true
  expiryDate?: true
  batchNumber?: true
  manufacturer?: true
  notes?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type InventorySupplyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InventorySupply to aggregate.
   */
  where?: Prisma.InventorySupplyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InventorySupplies to fetch.
   */
  orderBy?: Prisma.InventorySupplyOrderByWithRelationInput | Prisma.InventorySupplyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InventorySupplyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InventorySupplies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InventorySupplies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InventorySupplies
  **/
  _count?: true | InventorySupplyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InventorySupplyAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InventorySupplySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InventorySupplyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InventorySupplyMaxAggregateInputType
}

export type GetInventorySupplyAggregateType<T extends InventorySupplyAggregateArgs> = {
      [P in keyof T & keyof AggregateInventorySupply]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInventorySupply[P]>
    : Prisma.GetScalarType<T[P], AggregateInventorySupply[P]>
}




export type InventorySupplyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InventorySupplyWhereInput
  orderBy?: Prisma.InventorySupplyOrderByWithAggregationInput | Prisma.InventorySupplyOrderByWithAggregationInput[]
  by: Prisma.InventorySupplyScalarFieldEnum[] | Prisma.InventorySupplyScalarFieldEnum
  having?: Prisma.InventorySupplyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InventorySupplyCountAggregateInputType | true
  _avg?: InventorySupplyAvgAggregateInputType
  _sum?: InventorySupplySumAggregateInputType
  _min?: InventorySupplyMinAggregateInputType
  _max?: InventorySupplyMaxAggregateInputType
}

export type InventorySupplyGroupByOutputType = {
  supplyId: number
  name: string
  category: string
  quantity: number
  unit: string
  reorderLevel: number
  unitCost: runtime.Decimal | null
  expiryDate: Date | null
  batchNumber: string | null
  manufacturer: string | null
  notes: string | null
  isActive: string
  createdAt: Date
  updatedAt: Date
  _count: InventorySupplyCountAggregateOutputType | null
  _avg: InventorySupplyAvgAggregateOutputType | null
  _sum: InventorySupplySumAggregateOutputType | null
  _min: InventorySupplyMinAggregateOutputType | null
  _max: InventorySupplyMaxAggregateOutputType | null
}

export type GetInventorySupplyGroupByPayload<T extends InventorySupplyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InventorySupplyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InventorySupplyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InventorySupplyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InventorySupplyGroupByOutputType[P]>
      }
    >
  >



export type InventorySupplyWhereInput = {
  AND?: Prisma.InventorySupplyWhereInput | Prisma.InventorySupplyWhereInput[]
  OR?: Prisma.InventorySupplyWhereInput[]
  NOT?: Prisma.InventorySupplyWhereInput | Prisma.InventorySupplyWhereInput[]
  supplyId?: Prisma.IntFilter<"InventorySupply"> | number
  name?: Prisma.StringFilter<"InventorySupply"> | string
  category?: Prisma.StringFilter<"InventorySupply"> | string
  quantity?: Prisma.IntFilter<"InventorySupply"> | number
  unit?: Prisma.StringFilter<"InventorySupply"> | string
  reorderLevel?: Prisma.IntFilter<"InventorySupply"> | number
  unitCost?: Prisma.DecimalNullableFilter<"InventorySupply"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  expiryDate?: Prisma.DateTimeNullableFilter<"InventorySupply"> | Date | string | null
  batchNumber?: Prisma.StringNullableFilter<"InventorySupply"> | string | null
  manufacturer?: Prisma.StringNullableFilter<"InventorySupply"> | string | null
  notes?: Prisma.StringNullableFilter<"InventorySupply"> | string | null
  isActive?: Prisma.StringFilter<"InventorySupply"> | string
  createdAt?: Prisma.DateTimeFilter<"InventorySupply"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InventorySupply"> | Date | string
}

export type InventorySupplyOrderByWithRelationInput = {
  supplyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  reorderLevel?: Prisma.SortOrder
  unitCost?: Prisma.SortOrderInput | Prisma.SortOrder
  expiryDate?: Prisma.SortOrderInput | Prisma.SortOrder
  batchNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  manufacturer?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InventorySupplyWhereUniqueInput = Prisma.AtLeast<{
  supplyId?: number
  AND?: Prisma.InventorySupplyWhereInput | Prisma.InventorySupplyWhereInput[]
  OR?: Prisma.InventorySupplyWhereInput[]
  NOT?: Prisma.InventorySupplyWhereInput | Prisma.InventorySupplyWhereInput[]
  name?: Prisma.StringFilter<"InventorySupply"> | string
  category?: Prisma.StringFilter<"InventorySupply"> | string
  quantity?: Prisma.IntFilter<"InventorySupply"> | number
  unit?: Prisma.StringFilter<"InventorySupply"> | string
  reorderLevel?: Prisma.IntFilter<"InventorySupply"> | number
  unitCost?: Prisma.DecimalNullableFilter<"InventorySupply"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  expiryDate?: Prisma.DateTimeNullableFilter<"InventorySupply"> | Date | string | null
  batchNumber?: Prisma.StringNullableFilter<"InventorySupply"> | string | null
  manufacturer?: Prisma.StringNullableFilter<"InventorySupply"> | string | null
  notes?: Prisma.StringNullableFilter<"InventorySupply"> | string | null
  isActive?: Prisma.StringFilter<"InventorySupply"> | string
  createdAt?: Prisma.DateTimeFilter<"InventorySupply"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"InventorySupply"> | Date | string
}, "supplyId">

export type InventorySupplyOrderByWithAggregationInput = {
  supplyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  reorderLevel?: Prisma.SortOrder
  unitCost?: Prisma.SortOrderInput | Prisma.SortOrder
  expiryDate?: Prisma.SortOrderInput | Prisma.SortOrder
  batchNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  manufacturer?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.InventorySupplyCountOrderByAggregateInput
  _avg?: Prisma.InventorySupplyAvgOrderByAggregateInput
  _max?: Prisma.InventorySupplyMaxOrderByAggregateInput
  _min?: Prisma.InventorySupplyMinOrderByAggregateInput
  _sum?: Prisma.InventorySupplySumOrderByAggregateInput
}

export type InventorySupplyScalarWhereWithAggregatesInput = {
  AND?: Prisma.InventorySupplyScalarWhereWithAggregatesInput | Prisma.InventorySupplyScalarWhereWithAggregatesInput[]
  OR?: Prisma.InventorySupplyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InventorySupplyScalarWhereWithAggregatesInput | Prisma.InventorySupplyScalarWhereWithAggregatesInput[]
  supplyId?: Prisma.IntWithAggregatesFilter<"InventorySupply"> | number
  name?: Prisma.StringWithAggregatesFilter<"InventorySupply"> | string
  category?: Prisma.StringWithAggregatesFilter<"InventorySupply"> | string
  quantity?: Prisma.IntWithAggregatesFilter<"InventorySupply"> | number
  unit?: Prisma.StringWithAggregatesFilter<"InventorySupply"> | string
  reorderLevel?: Prisma.IntWithAggregatesFilter<"InventorySupply"> | number
  unitCost?: Prisma.DecimalNullableWithAggregatesFilter<"InventorySupply"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  expiryDate?: Prisma.DateTimeNullableWithAggregatesFilter<"InventorySupply"> | Date | string | null
  batchNumber?: Prisma.StringNullableWithAggregatesFilter<"InventorySupply"> | string | null
  manufacturer?: Prisma.StringNullableWithAggregatesFilter<"InventorySupply"> | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"InventorySupply"> | string | null
  isActive?: Prisma.StringWithAggregatesFilter<"InventorySupply"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"InventorySupply"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"InventorySupply"> | Date | string
}

export type InventorySupplyCreateInput = {
  name: string
  category: string
  quantity: number
  unit: string
  reorderLevel?: number
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  expiryDate?: Date | string | null
  batchNumber?: string | null
  manufacturer?: string | null
  notes?: string | null
  isActive?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InventorySupplyUncheckedCreateInput = {
  supplyId?: number
  name: string
  category: string
  quantity: number
  unit: string
  reorderLevel?: number
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  expiryDate?: Date | string | null
  batchNumber?: string | null
  manufacturer?: string | null
  notes?: string | null
  isActive?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InventorySupplyUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  reorderLevel?: Prisma.IntFieldUpdateOperationsInput | number
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  expiryDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  batchNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  manufacturer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InventorySupplyUncheckedUpdateInput = {
  supplyId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  reorderLevel?: Prisma.IntFieldUpdateOperationsInput | number
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  expiryDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  batchNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  manufacturer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InventorySupplyCreateManyInput = {
  supplyId?: number
  name: string
  category: string
  quantity: number
  unit: string
  reorderLevel?: number
  unitCost?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  expiryDate?: Date | string | null
  batchNumber?: string | null
  manufacturer?: string | null
  notes?: string | null
  isActive?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type InventorySupplyUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  reorderLevel?: Prisma.IntFieldUpdateOperationsInput | number
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  expiryDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  batchNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  manufacturer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InventorySupplyUncheckedUpdateManyInput = {
  supplyId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  unit?: Prisma.StringFieldUpdateOperationsInput | string
  reorderLevel?: Prisma.IntFieldUpdateOperationsInput | number
  unitCost?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  expiryDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  batchNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  manufacturer?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type InventorySupplyCountOrderByAggregateInput = {
  supplyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  reorderLevel?: Prisma.SortOrder
  unitCost?: Prisma.SortOrder
  expiryDate?: Prisma.SortOrder
  batchNumber?: Prisma.SortOrder
  manufacturer?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InventorySupplyAvgOrderByAggregateInput = {
  supplyId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  reorderLevel?: Prisma.SortOrder
  unitCost?: Prisma.SortOrder
}

export type InventorySupplyMaxOrderByAggregateInput = {
  supplyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  reorderLevel?: Prisma.SortOrder
  unitCost?: Prisma.SortOrder
  expiryDate?: Prisma.SortOrder
  batchNumber?: Prisma.SortOrder
  manufacturer?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InventorySupplyMinOrderByAggregateInput = {
  supplyId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  unit?: Prisma.SortOrder
  reorderLevel?: Prisma.SortOrder
  unitCost?: Prisma.SortOrder
  expiryDate?: Prisma.SortOrder
  batchNumber?: Prisma.SortOrder
  manufacturer?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type InventorySupplySumOrderByAggregateInput = {
  supplyId?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  reorderLevel?: Prisma.SortOrder
  unitCost?: Prisma.SortOrder
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}



export type InventorySupplySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  supplyId?: boolean
  name?: boolean
  category?: boolean
  quantity?: boolean
  unit?: boolean
  reorderLevel?: boolean
  unitCost?: boolean
  expiryDate?: boolean
  batchNumber?: boolean
  manufacturer?: boolean
  notes?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["inventorySupply"]>

export type InventorySupplySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  supplyId?: boolean
  name?: boolean
  category?: boolean
  quantity?: boolean
  unit?: boolean
  reorderLevel?: boolean
  unitCost?: boolean
  expiryDate?: boolean
  batchNumber?: boolean
  manufacturer?: boolean
  notes?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["inventorySupply"]>

export type InventorySupplySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  supplyId?: boolean
  name?: boolean
  category?: boolean
  quantity?: boolean
  unit?: boolean
  reorderLevel?: boolean
  unitCost?: boolean
  expiryDate?: boolean
  batchNumber?: boolean
  manufacturer?: boolean
  notes?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["inventorySupply"]>

export type InventorySupplySelectScalar = {
  supplyId?: boolean
  name?: boolean
  category?: boolean
  quantity?: boolean
  unit?: boolean
  reorderLevel?: boolean
  unitCost?: boolean
  expiryDate?: boolean
  batchNumber?: boolean
  manufacturer?: boolean
  notes?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type InventorySupplyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"supplyId" | "name" | "category" | "quantity" | "unit" | "reorderLevel" | "unitCost" | "expiryDate" | "batchNumber" | "manufacturer" | "notes" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["inventorySupply"]>

export type $InventorySupplyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InventorySupply"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    supplyId: number
    name: string
    category: string
    quantity: number
    unit: string
    reorderLevel: number
    unitCost: runtime.Decimal | null
    expiryDate: Date | null
    batchNumber: string | null
    manufacturer: string | null
    notes: string | null
    isActive: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["inventorySupply"]>
  composites: {}
}

export type InventorySupplyGetPayload<S extends boolean | null | undefined | InventorySupplyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload, S>

export type InventorySupplyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InventorySupplyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InventorySupplyCountAggregateInputType | true
  }

export interface InventorySupplyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InventorySupply'], meta: { name: 'InventorySupply' } }
  /**
   * Find zero or one InventorySupply that matches the filter.
   * @param {InventorySupplyFindUniqueArgs} args - Arguments to find a InventorySupply
   * @example
   * // Get one InventorySupply
   * const inventorySupply = await prisma.inventorySupply.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InventorySupplyFindUniqueArgs>(args: Prisma.SelectSubset<T, InventorySupplyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InventorySupplyClient<runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InventorySupply that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InventorySupplyFindUniqueOrThrowArgs} args - Arguments to find a InventorySupply
   * @example
   * // Get one InventorySupply
   * const inventorySupply = await prisma.inventorySupply.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InventorySupplyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InventorySupplyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InventorySupplyClient<runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InventorySupply that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InventorySupplyFindFirstArgs} args - Arguments to find a InventorySupply
   * @example
   * // Get one InventorySupply
   * const inventorySupply = await prisma.inventorySupply.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InventorySupplyFindFirstArgs>(args?: Prisma.SelectSubset<T, InventorySupplyFindFirstArgs<ExtArgs>>): Prisma.Prisma__InventorySupplyClient<runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InventorySupply that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InventorySupplyFindFirstOrThrowArgs} args - Arguments to find a InventorySupply
   * @example
   * // Get one InventorySupply
   * const inventorySupply = await prisma.inventorySupply.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InventorySupplyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InventorySupplyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InventorySupplyClient<runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InventorySupplies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InventorySupplyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InventorySupplies
   * const inventorySupplies = await prisma.inventorySupply.findMany()
   * 
   * // Get first 10 InventorySupplies
   * const inventorySupplies = await prisma.inventorySupply.findMany({ take: 10 })
   * 
   * // Only select the `supplyId`
   * const inventorySupplyWithSupplyIdOnly = await prisma.inventorySupply.findMany({ select: { supplyId: true } })
   * 
   */
  findMany<T extends InventorySupplyFindManyArgs>(args?: Prisma.SelectSubset<T, InventorySupplyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InventorySupply.
   * @param {InventorySupplyCreateArgs} args - Arguments to create a InventorySupply.
   * @example
   * // Create one InventorySupply
   * const InventorySupply = await prisma.inventorySupply.create({
   *   data: {
   *     // ... data to create a InventorySupply
   *   }
   * })
   * 
   */
  create<T extends InventorySupplyCreateArgs>(args: Prisma.SelectSubset<T, InventorySupplyCreateArgs<ExtArgs>>): Prisma.Prisma__InventorySupplyClient<runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InventorySupplies.
   * @param {InventorySupplyCreateManyArgs} args - Arguments to create many InventorySupplies.
   * @example
   * // Create many InventorySupplies
   * const inventorySupply = await prisma.inventorySupply.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InventorySupplyCreateManyArgs>(args?: Prisma.SelectSubset<T, InventorySupplyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many InventorySupplies and returns the data saved in the database.
   * @param {InventorySupplyCreateManyAndReturnArgs} args - Arguments to create many InventorySupplies.
   * @example
   * // Create many InventorySupplies
   * const inventorySupply = await prisma.inventorySupply.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many InventorySupplies and only return the `supplyId`
   * const inventorySupplyWithSupplyIdOnly = await prisma.inventorySupply.createManyAndReturn({
   *   select: { supplyId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InventorySupplyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InventorySupplyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a InventorySupply.
   * @param {InventorySupplyDeleteArgs} args - Arguments to delete one InventorySupply.
   * @example
   * // Delete one InventorySupply
   * const InventorySupply = await prisma.inventorySupply.delete({
   *   where: {
   *     // ... filter to delete one InventorySupply
   *   }
   * })
   * 
   */
  delete<T extends InventorySupplyDeleteArgs>(args: Prisma.SelectSubset<T, InventorySupplyDeleteArgs<ExtArgs>>): Prisma.Prisma__InventorySupplyClient<runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InventorySupply.
   * @param {InventorySupplyUpdateArgs} args - Arguments to update one InventorySupply.
   * @example
   * // Update one InventorySupply
   * const inventorySupply = await prisma.inventorySupply.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InventorySupplyUpdateArgs>(args: Prisma.SelectSubset<T, InventorySupplyUpdateArgs<ExtArgs>>): Prisma.Prisma__InventorySupplyClient<runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InventorySupplies.
   * @param {InventorySupplyDeleteManyArgs} args - Arguments to filter InventorySupplies to delete.
   * @example
   * // Delete a few InventorySupplies
   * const { count } = await prisma.inventorySupply.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InventorySupplyDeleteManyArgs>(args?: Prisma.SelectSubset<T, InventorySupplyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InventorySupplies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InventorySupplyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InventorySupplies
   * const inventorySupply = await prisma.inventorySupply.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InventorySupplyUpdateManyArgs>(args: Prisma.SelectSubset<T, InventorySupplyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InventorySupplies and returns the data updated in the database.
   * @param {InventorySupplyUpdateManyAndReturnArgs} args - Arguments to update many InventorySupplies.
   * @example
   * // Update many InventorySupplies
   * const inventorySupply = await prisma.inventorySupply.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more InventorySupplies and only return the `supplyId`
   * const inventorySupplyWithSupplyIdOnly = await prisma.inventorySupply.updateManyAndReturn({
   *   select: { supplyId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InventorySupplyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InventorySupplyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one InventorySupply.
   * @param {InventorySupplyUpsertArgs} args - Arguments to update or create a InventorySupply.
   * @example
   * // Update or create a InventorySupply
   * const inventorySupply = await prisma.inventorySupply.upsert({
   *   create: {
   *     // ... data to create a InventorySupply
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InventorySupply we want to update
   *   }
   * })
   */
  upsert<T extends InventorySupplyUpsertArgs>(args: Prisma.SelectSubset<T, InventorySupplyUpsertArgs<ExtArgs>>): Prisma.Prisma__InventorySupplyClient<runtime.Types.Result.GetResult<Prisma.$InventorySupplyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InventorySupplies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InventorySupplyCountArgs} args - Arguments to filter InventorySupplies to count.
   * @example
   * // Count the number of InventorySupplies
   * const count = await prisma.inventorySupply.count({
   *   where: {
   *     // ... the filter for the InventorySupplies we want to count
   *   }
   * })
  **/
  count<T extends InventorySupplyCountArgs>(
    args?: Prisma.Subset<T, InventorySupplyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InventorySupplyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InventorySupply.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InventorySupplyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InventorySupplyAggregateArgs>(args: Prisma.Subset<T, InventorySupplyAggregateArgs>): Prisma.PrismaPromise<GetInventorySupplyAggregateType<T>>

  /**
   * Group by InventorySupply.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InventorySupplyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InventorySupplyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InventorySupplyGroupByArgs['orderBy'] }
      : { orderBy?: InventorySupplyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InventorySupplyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInventorySupplyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InventorySupply model
 */
readonly fields: InventorySupplyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InventorySupply.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InventorySupplyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InventorySupply model
 */
export interface InventorySupplyFieldRefs {
  readonly supplyId: Prisma.FieldRef<"InventorySupply", 'Int'>
  readonly name: Prisma.FieldRef<"InventorySupply", 'String'>
  readonly category: Prisma.FieldRef<"InventorySupply", 'String'>
  readonly quantity: Prisma.FieldRef<"InventorySupply", 'Int'>
  readonly unit: Prisma.FieldRef<"InventorySupply", 'String'>
  readonly reorderLevel: Prisma.FieldRef<"InventorySupply", 'Int'>
  readonly unitCost: Prisma.FieldRef<"InventorySupply", 'Decimal'>
  readonly expiryDate: Prisma.FieldRef<"InventorySupply", 'DateTime'>
  readonly batchNumber: Prisma.FieldRef<"InventorySupply", 'String'>
  readonly manufacturer: Prisma.FieldRef<"InventorySupply", 'String'>
  readonly notes: Prisma.FieldRef<"InventorySupply", 'String'>
  readonly isActive: Prisma.FieldRef<"InventorySupply", 'String'>
  readonly createdAt: Prisma.FieldRef<"InventorySupply", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"InventorySupply", 'DateTime'>
}
    

// Custom InputTypes
/**
 * InventorySupply findUnique
 */
export type InventorySupplyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
  /**
   * Filter, which InventorySupply to fetch.
   */
  where: Prisma.InventorySupplyWhereUniqueInput
}

/**
 * InventorySupply findUniqueOrThrow
 */
export type InventorySupplyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
  /**
   * Filter, which InventorySupply to fetch.
   */
  where: Prisma.InventorySupplyWhereUniqueInput
}

/**
 * InventorySupply findFirst
 */
export type InventorySupplyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
  /**
   * Filter, which InventorySupply to fetch.
   */
  where?: Prisma.InventorySupplyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InventorySupplies to fetch.
   */
  orderBy?: Prisma.InventorySupplyOrderByWithRelationInput | Prisma.InventorySupplyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InventorySupplies.
   */
  cursor?: Prisma.InventorySupplyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InventorySupplies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InventorySupplies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InventorySupplies.
   */
  distinct?: Prisma.InventorySupplyScalarFieldEnum | Prisma.InventorySupplyScalarFieldEnum[]
}

/**
 * InventorySupply findFirstOrThrow
 */
export type InventorySupplyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
  /**
   * Filter, which InventorySupply to fetch.
   */
  where?: Prisma.InventorySupplyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InventorySupplies to fetch.
   */
  orderBy?: Prisma.InventorySupplyOrderByWithRelationInput | Prisma.InventorySupplyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InventorySupplies.
   */
  cursor?: Prisma.InventorySupplyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InventorySupplies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InventorySupplies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InventorySupplies.
   */
  distinct?: Prisma.InventorySupplyScalarFieldEnum | Prisma.InventorySupplyScalarFieldEnum[]
}

/**
 * InventorySupply findMany
 */
export type InventorySupplyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
  /**
   * Filter, which InventorySupplies to fetch.
   */
  where?: Prisma.InventorySupplyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InventorySupplies to fetch.
   */
  orderBy?: Prisma.InventorySupplyOrderByWithRelationInput | Prisma.InventorySupplyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InventorySupplies.
   */
  cursor?: Prisma.InventorySupplyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InventorySupplies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InventorySupplies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InventorySupplies.
   */
  distinct?: Prisma.InventorySupplyScalarFieldEnum | Prisma.InventorySupplyScalarFieldEnum[]
}

/**
 * InventorySupply create
 */
export type InventorySupplyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
  /**
   * The data needed to create a InventorySupply.
   */
  data: Prisma.XOR<Prisma.InventorySupplyCreateInput, Prisma.InventorySupplyUncheckedCreateInput>
}

/**
 * InventorySupply createMany
 */
export type InventorySupplyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InventorySupplies.
   */
  data: Prisma.InventorySupplyCreateManyInput | Prisma.InventorySupplyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InventorySupply createManyAndReturn
 */
export type InventorySupplyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
  /**
   * The data used to create many InventorySupplies.
   */
  data: Prisma.InventorySupplyCreateManyInput | Prisma.InventorySupplyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InventorySupply update
 */
export type InventorySupplyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
  /**
   * The data needed to update a InventorySupply.
   */
  data: Prisma.XOR<Prisma.InventorySupplyUpdateInput, Prisma.InventorySupplyUncheckedUpdateInput>
  /**
   * Choose, which InventorySupply to update.
   */
  where: Prisma.InventorySupplyWhereUniqueInput
}

/**
 * InventorySupply updateMany
 */
export type InventorySupplyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InventorySupplies.
   */
  data: Prisma.XOR<Prisma.InventorySupplyUpdateManyMutationInput, Prisma.InventorySupplyUncheckedUpdateManyInput>
  /**
   * Filter which InventorySupplies to update
   */
  where?: Prisma.InventorySupplyWhereInput
  /**
   * Limit how many InventorySupplies to update.
   */
  limit?: number
}

/**
 * InventorySupply updateManyAndReturn
 */
export type InventorySupplyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
  /**
   * The data used to update InventorySupplies.
   */
  data: Prisma.XOR<Prisma.InventorySupplyUpdateManyMutationInput, Prisma.InventorySupplyUncheckedUpdateManyInput>
  /**
   * Filter which InventorySupplies to update
   */
  where?: Prisma.InventorySupplyWhereInput
  /**
   * Limit how many InventorySupplies to update.
   */
  limit?: number
}

/**
 * InventorySupply upsert
 */
export type InventorySupplyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
  /**
   * The filter to search for the InventorySupply to update in case it exists.
   */
  where: Prisma.InventorySupplyWhereUniqueInput
  /**
   * In case the InventorySupply found by the `where` argument doesn't exist, create a new InventorySupply with this data.
   */
  create: Prisma.XOR<Prisma.InventorySupplyCreateInput, Prisma.InventorySupplyUncheckedCreateInput>
  /**
   * In case the InventorySupply was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InventorySupplyUpdateInput, Prisma.InventorySupplyUncheckedUpdateInput>
}

/**
 * InventorySupply delete
 */
export type InventorySupplyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
  /**
   * Filter which InventorySupply to delete.
   */
  where: Prisma.InventorySupplyWhereUniqueInput
}

/**
 * InventorySupply deleteMany
 */
export type InventorySupplyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InventorySupplies to delete
   */
  where?: Prisma.InventorySupplyWhereInput
  /**
   * Limit how many InventorySupplies to delete.
   */
  limit?: number
}

/**
 * InventorySupply without action
 */
export type InventorySupplyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InventorySupply
   */
  select?: Prisma.InventorySupplySelect<ExtArgs> | null
  /**
   * Omit specific fields from the InventorySupply
   */
  omit?: Prisma.InventorySupplyOmit<ExtArgs> | null
}
