
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MedicalRecord` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MedicalRecord
 * 
 */
export type MedicalRecordModel = runtime.Types.Result.DefaultSelection<Prisma.$MedicalRecordPayload>

export type AggregateMedicalRecord = {
  _count: MedicalRecordCountAggregateOutputType | null
  _avg: MedicalRecordAvgAggregateOutputType | null
  _sum: MedicalRecordSumAggregateOutputType | null
  _min: MedicalRecordMinAggregateOutputType | null
  _max: MedicalRecordMaxAggregateOutputType | null
}

export type MedicalRecordAvgAggregateOutputType = {
  recordId: number | null
  patientId: number | null
  createdByUserId: number | null
}

export type MedicalRecordSumAggregateOutputType = {
  recordId: number | null
  patientId: number | null
  createdByUserId: number | null
}

export type MedicalRecordMinAggregateOutputType = {
  recordId: number | null
  patientId: number | null
  createdByUserId: number | null
  recordType: string | null
  title: string | null
  clinicalNote: string | null
  recordStatus: string | null
  encounterDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MedicalRecordMaxAggregateOutputType = {
  recordId: number | null
  patientId: number | null
  createdByUserId: number | null
  recordType: string | null
  title: string | null
  clinicalNote: string | null
  recordStatus: string | null
  encounterDate: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MedicalRecordCountAggregateOutputType = {
  recordId: number
  patientId: number
  createdByUserId: number
  recordType: number
  title: number
  clinicalNote: number
  recordStatus: number
  encounterDate: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MedicalRecordAvgAggregateInputType = {
  recordId?: true
  patientId?: true
  createdByUserId?: true
}

export type MedicalRecordSumAggregateInputType = {
  recordId?: true
  patientId?: true
  createdByUserId?: true
}

export type MedicalRecordMinAggregateInputType = {
  recordId?: true
  patientId?: true
  createdByUserId?: true
  recordType?: true
  title?: true
  clinicalNote?: true
  recordStatus?: true
  encounterDate?: true
  createdAt?: true
  updatedAt?: true
}

export type MedicalRecordMaxAggregateInputType = {
  recordId?: true
  patientId?: true
  createdByUserId?: true
  recordType?: true
  title?: true
  clinicalNote?: true
  recordStatus?: true
  encounterDate?: true
  createdAt?: true
  updatedAt?: true
}

export type MedicalRecordCountAggregateInputType = {
  recordId?: true
  patientId?: true
  createdByUserId?: true
  recordType?: true
  title?: true
  clinicalNote?: true
  recordStatus?: true
  encounterDate?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MedicalRecordAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MedicalRecord to aggregate.
   */
  where?: Prisma.MedicalRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MedicalRecords to fetch.
   */
  orderBy?: Prisma.MedicalRecordOrderByWithRelationInput | Prisma.MedicalRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MedicalRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MedicalRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MedicalRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MedicalRecords
  **/
  _count?: true | MedicalRecordCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MedicalRecordAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MedicalRecordSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MedicalRecordMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MedicalRecordMaxAggregateInputType
}

export type GetMedicalRecordAggregateType<T extends MedicalRecordAggregateArgs> = {
      [P in keyof T & keyof AggregateMedicalRecord]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMedicalRecord[P]>
    : Prisma.GetScalarType<T[P], AggregateMedicalRecord[P]>
}




export type MedicalRecordGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MedicalRecordWhereInput
  orderBy?: Prisma.MedicalRecordOrderByWithAggregationInput | Prisma.MedicalRecordOrderByWithAggregationInput[]
  by: Prisma.MedicalRecordScalarFieldEnum[] | Prisma.MedicalRecordScalarFieldEnum
  having?: Prisma.MedicalRecordScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MedicalRecordCountAggregateInputType | true
  _avg?: MedicalRecordAvgAggregateInputType
  _sum?: MedicalRecordSumAggregateInputType
  _min?: MedicalRecordMinAggregateInputType
  _max?: MedicalRecordMaxAggregateInputType
}

export type MedicalRecordGroupByOutputType = {
  recordId: number
  patientId: number
  createdByUserId: number
  recordType: string
  title: string
  clinicalNote: string
  recordStatus: string
  encounterDate: Date
  createdAt: Date
  updatedAt: Date
  _count: MedicalRecordCountAggregateOutputType | null
  _avg: MedicalRecordAvgAggregateOutputType | null
  _sum: MedicalRecordSumAggregateOutputType | null
  _min: MedicalRecordMinAggregateOutputType | null
  _max: MedicalRecordMaxAggregateOutputType | null
}

export type GetMedicalRecordGroupByPayload<T extends MedicalRecordGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MedicalRecordGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MedicalRecordGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MedicalRecordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MedicalRecordGroupByOutputType[P]>
      }
    >
  >



export type MedicalRecordWhereInput = {
  AND?: Prisma.MedicalRecordWhereInput | Prisma.MedicalRecordWhereInput[]
  OR?: Prisma.MedicalRecordWhereInput[]
  NOT?: Prisma.MedicalRecordWhereInput | Prisma.MedicalRecordWhereInput[]
  recordId?: Prisma.IntFilter<"MedicalRecord"> | number
  patientId?: Prisma.IntFilter<"MedicalRecord"> | number
  createdByUserId?: Prisma.IntFilter<"MedicalRecord"> | number
  recordType?: Prisma.StringFilter<"MedicalRecord"> | string
  title?: Prisma.StringFilter<"MedicalRecord"> | string
  clinicalNote?: Prisma.StringFilter<"MedicalRecord"> | string
  recordStatus?: Prisma.StringFilter<"MedicalRecord"> | string
  encounterDate?: Prisma.DateTimeFilter<"MedicalRecord"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"MedicalRecord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MedicalRecord"> | Date | string
  patient?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  patientRecord?: Prisma.XOR<Prisma.PatientScalarRelationFilter, Prisma.PatientWhereInput>
  diagnoses?: Prisma.RecordDiagnosisListRelationFilter
  prescriptions?: Prisma.RecordPrescriptionListRelationFilter
  treatments?: Prisma.RecordTreatmentListRelationFilter
}

export type MedicalRecordOrderByWithRelationInput = {
  recordId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  createdByUserId?: Prisma.SortOrder
  recordType?: Prisma.SortOrder
  title?: Prisma.SortOrder
  clinicalNote?: Prisma.SortOrder
  recordStatus?: Prisma.SortOrder
  encounterDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  patient?: Prisma.UserOrderByWithRelationInput
  patientRecord?: Prisma.PatientOrderByWithRelationInput
  diagnoses?: Prisma.RecordDiagnosisOrderByRelationAggregateInput
  prescriptions?: Prisma.RecordPrescriptionOrderByRelationAggregateInput
  treatments?: Prisma.RecordTreatmentOrderByRelationAggregateInput
}

export type MedicalRecordWhereUniqueInput = Prisma.AtLeast<{
  recordId?: number
  AND?: Prisma.MedicalRecordWhereInput | Prisma.MedicalRecordWhereInput[]
  OR?: Prisma.MedicalRecordWhereInput[]
  NOT?: Prisma.MedicalRecordWhereInput | Prisma.MedicalRecordWhereInput[]
  patientId?: Prisma.IntFilter<"MedicalRecord"> | number
  createdByUserId?: Prisma.IntFilter<"MedicalRecord"> | number
  recordType?: Prisma.StringFilter<"MedicalRecord"> | string
  title?: Prisma.StringFilter<"MedicalRecord"> | string
  clinicalNote?: Prisma.StringFilter<"MedicalRecord"> | string
  recordStatus?: Prisma.StringFilter<"MedicalRecord"> | string
  encounterDate?: Prisma.DateTimeFilter<"MedicalRecord"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"MedicalRecord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MedicalRecord"> | Date | string
  patient?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  patientRecord?: Prisma.XOR<Prisma.PatientScalarRelationFilter, Prisma.PatientWhereInput>
  diagnoses?: Prisma.RecordDiagnosisListRelationFilter
  prescriptions?: Prisma.RecordPrescriptionListRelationFilter
  treatments?: Prisma.RecordTreatmentListRelationFilter
}, "recordId">

export type MedicalRecordOrderByWithAggregationInput = {
  recordId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  createdByUserId?: Prisma.SortOrder
  recordType?: Prisma.SortOrder
  title?: Prisma.SortOrder
  clinicalNote?: Prisma.SortOrder
  recordStatus?: Prisma.SortOrder
  encounterDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MedicalRecordCountOrderByAggregateInput
  _avg?: Prisma.MedicalRecordAvgOrderByAggregateInput
  _max?: Prisma.MedicalRecordMaxOrderByAggregateInput
  _min?: Prisma.MedicalRecordMinOrderByAggregateInput
  _sum?: Prisma.MedicalRecordSumOrderByAggregateInput
}

export type MedicalRecordScalarWhereWithAggregatesInput = {
  AND?: Prisma.MedicalRecordScalarWhereWithAggregatesInput | Prisma.MedicalRecordScalarWhereWithAggregatesInput[]
  OR?: Prisma.MedicalRecordScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MedicalRecordScalarWhereWithAggregatesInput | Prisma.MedicalRecordScalarWhereWithAggregatesInput[]
  recordId?: Prisma.IntWithAggregatesFilter<"MedicalRecord"> | number
  patientId?: Prisma.IntWithAggregatesFilter<"MedicalRecord"> | number
  createdByUserId?: Prisma.IntWithAggregatesFilter<"MedicalRecord"> | number
  recordType?: Prisma.StringWithAggregatesFilter<"MedicalRecord"> | string
  title?: Prisma.StringWithAggregatesFilter<"MedicalRecord"> | string
  clinicalNote?: Prisma.StringWithAggregatesFilter<"MedicalRecord"> | string
  recordStatus?: Prisma.StringWithAggregatesFilter<"MedicalRecord"> | string
  encounterDate?: Prisma.DateTimeWithAggregatesFilter<"MedicalRecord"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MedicalRecord"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MedicalRecord"> | Date | string
}

export type MedicalRecordCreateInput = {
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  patient: Prisma.UserCreateNestedOneWithoutMedicalRecordsInput
  patientRecord: Prisma.PatientCreateNestedOneWithoutMedicalRecordsInput
  diagnoses?: Prisma.RecordDiagnosisCreateNestedManyWithoutRecordInput
  prescriptions?: Prisma.RecordPrescriptionCreateNestedManyWithoutRecordInput
  treatments?: Prisma.RecordTreatmentCreateNestedManyWithoutRecordInput
}

export type MedicalRecordUncheckedCreateInput = {
  recordId?: number
  patientId: number
  createdByUserId: number
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  diagnoses?: Prisma.RecordDiagnosisUncheckedCreateNestedManyWithoutRecordInput
  prescriptions?: Prisma.RecordPrescriptionUncheckedCreateNestedManyWithoutRecordInput
  treatments?: Prisma.RecordTreatmentUncheckedCreateNestedManyWithoutRecordInput
}

export type MedicalRecordUpdateInput = {
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  patient?: Prisma.UserUpdateOneRequiredWithoutMedicalRecordsNestedInput
  patientRecord?: Prisma.PatientUpdateOneRequiredWithoutMedicalRecordsNestedInput
  diagnoses?: Prisma.RecordDiagnosisUpdateManyWithoutRecordNestedInput
  prescriptions?: Prisma.RecordPrescriptionUpdateManyWithoutRecordNestedInput
  treatments?: Prisma.RecordTreatmentUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordUncheckedUpdateInput = {
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  createdByUserId?: Prisma.IntFieldUpdateOperationsInput | number
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  diagnoses?: Prisma.RecordDiagnosisUncheckedUpdateManyWithoutRecordNestedInput
  prescriptions?: Prisma.RecordPrescriptionUncheckedUpdateManyWithoutRecordNestedInput
  treatments?: Prisma.RecordTreatmentUncheckedUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordCreateManyInput = {
  recordId?: number
  patientId: number
  createdByUserId: number
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MedicalRecordUpdateManyMutationInput = {
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MedicalRecordUncheckedUpdateManyInput = {
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  createdByUserId?: Prisma.IntFieldUpdateOperationsInput | number
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MedicalRecordListRelationFilter = {
  every?: Prisma.MedicalRecordWhereInput
  some?: Prisma.MedicalRecordWhereInput
  none?: Prisma.MedicalRecordWhereInput
}

export type MedicalRecordOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MedicalRecordCountOrderByAggregateInput = {
  recordId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  createdByUserId?: Prisma.SortOrder
  recordType?: Prisma.SortOrder
  title?: Prisma.SortOrder
  clinicalNote?: Prisma.SortOrder
  recordStatus?: Prisma.SortOrder
  encounterDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MedicalRecordAvgOrderByAggregateInput = {
  recordId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  createdByUserId?: Prisma.SortOrder
}

export type MedicalRecordMaxOrderByAggregateInput = {
  recordId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  createdByUserId?: Prisma.SortOrder
  recordType?: Prisma.SortOrder
  title?: Prisma.SortOrder
  clinicalNote?: Prisma.SortOrder
  recordStatus?: Prisma.SortOrder
  encounterDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MedicalRecordMinOrderByAggregateInput = {
  recordId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  createdByUserId?: Prisma.SortOrder
  recordType?: Prisma.SortOrder
  title?: Prisma.SortOrder
  clinicalNote?: Prisma.SortOrder
  recordStatus?: Prisma.SortOrder
  encounterDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MedicalRecordSumOrderByAggregateInput = {
  recordId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  createdByUserId?: Prisma.SortOrder
}

export type MedicalRecordScalarRelationFilter = {
  is?: Prisma.MedicalRecordWhereInput
  isNot?: Prisma.MedicalRecordWhereInput
}

export type MedicalRecordCreateNestedManyWithoutPatientInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientInput> | Prisma.MedicalRecordCreateWithoutPatientInput[] | Prisma.MedicalRecordUncheckedCreateWithoutPatientInput[]
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutPatientInput | Prisma.MedicalRecordCreateOrConnectWithoutPatientInput[]
  createMany?: Prisma.MedicalRecordCreateManyPatientInputEnvelope
  connect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
}

export type MedicalRecordUncheckedCreateNestedManyWithoutPatientInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientInput> | Prisma.MedicalRecordCreateWithoutPatientInput[] | Prisma.MedicalRecordUncheckedCreateWithoutPatientInput[]
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutPatientInput | Prisma.MedicalRecordCreateOrConnectWithoutPatientInput[]
  createMany?: Prisma.MedicalRecordCreateManyPatientInputEnvelope
  connect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
}

export type MedicalRecordUpdateManyWithoutPatientNestedInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientInput> | Prisma.MedicalRecordCreateWithoutPatientInput[] | Prisma.MedicalRecordUncheckedCreateWithoutPatientInput[]
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutPatientInput | Prisma.MedicalRecordCreateOrConnectWithoutPatientInput[]
  upsert?: Prisma.MedicalRecordUpsertWithWhereUniqueWithoutPatientInput | Prisma.MedicalRecordUpsertWithWhereUniqueWithoutPatientInput[]
  createMany?: Prisma.MedicalRecordCreateManyPatientInputEnvelope
  set?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  disconnect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  delete?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  connect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  update?: Prisma.MedicalRecordUpdateWithWhereUniqueWithoutPatientInput | Prisma.MedicalRecordUpdateWithWhereUniqueWithoutPatientInput[]
  updateMany?: Prisma.MedicalRecordUpdateManyWithWhereWithoutPatientInput | Prisma.MedicalRecordUpdateManyWithWhereWithoutPatientInput[]
  deleteMany?: Prisma.MedicalRecordScalarWhereInput | Prisma.MedicalRecordScalarWhereInput[]
}

export type MedicalRecordUncheckedUpdateManyWithoutPatientNestedInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientInput> | Prisma.MedicalRecordCreateWithoutPatientInput[] | Prisma.MedicalRecordUncheckedCreateWithoutPatientInput[]
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutPatientInput | Prisma.MedicalRecordCreateOrConnectWithoutPatientInput[]
  upsert?: Prisma.MedicalRecordUpsertWithWhereUniqueWithoutPatientInput | Prisma.MedicalRecordUpsertWithWhereUniqueWithoutPatientInput[]
  createMany?: Prisma.MedicalRecordCreateManyPatientInputEnvelope
  set?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  disconnect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  delete?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  connect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  update?: Prisma.MedicalRecordUpdateWithWhereUniqueWithoutPatientInput | Prisma.MedicalRecordUpdateWithWhereUniqueWithoutPatientInput[]
  updateMany?: Prisma.MedicalRecordUpdateManyWithWhereWithoutPatientInput | Prisma.MedicalRecordUpdateManyWithWhereWithoutPatientInput[]
  deleteMany?: Prisma.MedicalRecordScalarWhereInput | Prisma.MedicalRecordScalarWhereInput[]
}

export type MedicalRecordCreateNestedManyWithoutPatientRecordInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientRecordInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientRecordInput> | Prisma.MedicalRecordCreateWithoutPatientRecordInput[] | Prisma.MedicalRecordUncheckedCreateWithoutPatientRecordInput[]
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutPatientRecordInput | Prisma.MedicalRecordCreateOrConnectWithoutPatientRecordInput[]
  createMany?: Prisma.MedicalRecordCreateManyPatientRecordInputEnvelope
  connect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
}

export type MedicalRecordUncheckedCreateNestedManyWithoutPatientRecordInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientRecordInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientRecordInput> | Prisma.MedicalRecordCreateWithoutPatientRecordInput[] | Prisma.MedicalRecordUncheckedCreateWithoutPatientRecordInput[]
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutPatientRecordInput | Prisma.MedicalRecordCreateOrConnectWithoutPatientRecordInput[]
  createMany?: Prisma.MedicalRecordCreateManyPatientRecordInputEnvelope
  connect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
}

export type MedicalRecordUpdateManyWithoutPatientRecordNestedInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientRecordInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientRecordInput> | Prisma.MedicalRecordCreateWithoutPatientRecordInput[] | Prisma.MedicalRecordUncheckedCreateWithoutPatientRecordInput[]
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutPatientRecordInput | Prisma.MedicalRecordCreateOrConnectWithoutPatientRecordInput[]
  upsert?: Prisma.MedicalRecordUpsertWithWhereUniqueWithoutPatientRecordInput | Prisma.MedicalRecordUpsertWithWhereUniqueWithoutPatientRecordInput[]
  createMany?: Prisma.MedicalRecordCreateManyPatientRecordInputEnvelope
  set?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  disconnect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  delete?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  connect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  update?: Prisma.MedicalRecordUpdateWithWhereUniqueWithoutPatientRecordInput | Prisma.MedicalRecordUpdateWithWhereUniqueWithoutPatientRecordInput[]
  updateMany?: Prisma.MedicalRecordUpdateManyWithWhereWithoutPatientRecordInput | Prisma.MedicalRecordUpdateManyWithWhereWithoutPatientRecordInput[]
  deleteMany?: Prisma.MedicalRecordScalarWhereInput | Prisma.MedicalRecordScalarWhereInput[]
}

export type MedicalRecordUncheckedUpdateManyWithoutPatientRecordNestedInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientRecordInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientRecordInput> | Prisma.MedicalRecordCreateWithoutPatientRecordInput[] | Prisma.MedicalRecordUncheckedCreateWithoutPatientRecordInput[]
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutPatientRecordInput | Prisma.MedicalRecordCreateOrConnectWithoutPatientRecordInput[]
  upsert?: Prisma.MedicalRecordUpsertWithWhereUniqueWithoutPatientRecordInput | Prisma.MedicalRecordUpsertWithWhereUniqueWithoutPatientRecordInput[]
  createMany?: Prisma.MedicalRecordCreateManyPatientRecordInputEnvelope
  set?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  disconnect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  delete?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  connect?: Prisma.MedicalRecordWhereUniqueInput | Prisma.MedicalRecordWhereUniqueInput[]
  update?: Prisma.MedicalRecordUpdateWithWhereUniqueWithoutPatientRecordInput | Prisma.MedicalRecordUpdateWithWhereUniqueWithoutPatientRecordInput[]
  updateMany?: Prisma.MedicalRecordUpdateManyWithWhereWithoutPatientRecordInput | Prisma.MedicalRecordUpdateManyWithWhereWithoutPatientRecordInput[]
  deleteMany?: Prisma.MedicalRecordScalarWhereInput | Prisma.MedicalRecordScalarWhereInput[]
}

export type MedicalRecordCreateNestedOneWithoutDiagnosesInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutDiagnosesInput, Prisma.MedicalRecordUncheckedCreateWithoutDiagnosesInput>
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutDiagnosesInput
  connect?: Prisma.MedicalRecordWhereUniqueInput
}

export type MedicalRecordUpdateOneRequiredWithoutDiagnosesNestedInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutDiagnosesInput, Prisma.MedicalRecordUncheckedCreateWithoutDiagnosesInput>
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutDiagnosesInput
  upsert?: Prisma.MedicalRecordUpsertWithoutDiagnosesInput
  connect?: Prisma.MedicalRecordWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MedicalRecordUpdateToOneWithWhereWithoutDiagnosesInput, Prisma.MedicalRecordUpdateWithoutDiagnosesInput>, Prisma.MedicalRecordUncheckedUpdateWithoutDiagnosesInput>
}

export type MedicalRecordCreateNestedOneWithoutPrescriptionsInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPrescriptionsInput, Prisma.MedicalRecordUncheckedCreateWithoutPrescriptionsInput>
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutPrescriptionsInput
  connect?: Prisma.MedicalRecordWhereUniqueInput
}

export type MedicalRecordUpdateOneRequiredWithoutPrescriptionsNestedInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPrescriptionsInput, Prisma.MedicalRecordUncheckedCreateWithoutPrescriptionsInput>
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutPrescriptionsInput
  upsert?: Prisma.MedicalRecordUpsertWithoutPrescriptionsInput
  connect?: Prisma.MedicalRecordWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MedicalRecordUpdateToOneWithWhereWithoutPrescriptionsInput, Prisma.MedicalRecordUpdateWithoutPrescriptionsInput>, Prisma.MedicalRecordUncheckedUpdateWithoutPrescriptionsInput>
}

export type MedicalRecordCreateNestedOneWithoutTreatmentsInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutTreatmentsInput, Prisma.MedicalRecordUncheckedCreateWithoutTreatmentsInput>
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutTreatmentsInput
  connect?: Prisma.MedicalRecordWhereUniqueInput
}

export type MedicalRecordUpdateOneRequiredWithoutTreatmentsNestedInput = {
  create?: Prisma.XOR<Prisma.MedicalRecordCreateWithoutTreatmentsInput, Prisma.MedicalRecordUncheckedCreateWithoutTreatmentsInput>
  connectOrCreate?: Prisma.MedicalRecordCreateOrConnectWithoutTreatmentsInput
  upsert?: Prisma.MedicalRecordUpsertWithoutTreatmentsInput
  connect?: Prisma.MedicalRecordWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MedicalRecordUpdateToOneWithWhereWithoutTreatmentsInput, Prisma.MedicalRecordUpdateWithoutTreatmentsInput>, Prisma.MedicalRecordUncheckedUpdateWithoutTreatmentsInput>
}

export type MedicalRecordCreateWithoutPatientInput = {
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  patientRecord: Prisma.PatientCreateNestedOneWithoutMedicalRecordsInput
  diagnoses?: Prisma.RecordDiagnosisCreateNestedManyWithoutRecordInput
  prescriptions?: Prisma.RecordPrescriptionCreateNestedManyWithoutRecordInput
  treatments?: Prisma.RecordTreatmentCreateNestedManyWithoutRecordInput
}

export type MedicalRecordUncheckedCreateWithoutPatientInput = {
  recordId?: number
  patientId: number
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  diagnoses?: Prisma.RecordDiagnosisUncheckedCreateNestedManyWithoutRecordInput
  prescriptions?: Prisma.RecordPrescriptionUncheckedCreateNestedManyWithoutRecordInput
  treatments?: Prisma.RecordTreatmentUncheckedCreateNestedManyWithoutRecordInput
}

export type MedicalRecordCreateOrConnectWithoutPatientInput = {
  where: Prisma.MedicalRecordWhereUniqueInput
  create: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientInput>
}

export type MedicalRecordCreateManyPatientInputEnvelope = {
  data: Prisma.MedicalRecordCreateManyPatientInput | Prisma.MedicalRecordCreateManyPatientInput[]
  skipDuplicates?: boolean
}

export type MedicalRecordUpsertWithWhereUniqueWithoutPatientInput = {
  where: Prisma.MedicalRecordWhereUniqueInput
  update: Prisma.XOR<Prisma.MedicalRecordUpdateWithoutPatientInput, Prisma.MedicalRecordUncheckedUpdateWithoutPatientInput>
  create: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientInput>
}

export type MedicalRecordUpdateWithWhereUniqueWithoutPatientInput = {
  where: Prisma.MedicalRecordWhereUniqueInput
  data: Prisma.XOR<Prisma.MedicalRecordUpdateWithoutPatientInput, Prisma.MedicalRecordUncheckedUpdateWithoutPatientInput>
}

export type MedicalRecordUpdateManyWithWhereWithoutPatientInput = {
  where: Prisma.MedicalRecordScalarWhereInput
  data: Prisma.XOR<Prisma.MedicalRecordUpdateManyMutationInput, Prisma.MedicalRecordUncheckedUpdateManyWithoutPatientInput>
}

export type MedicalRecordScalarWhereInput = {
  AND?: Prisma.MedicalRecordScalarWhereInput | Prisma.MedicalRecordScalarWhereInput[]
  OR?: Prisma.MedicalRecordScalarWhereInput[]
  NOT?: Prisma.MedicalRecordScalarWhereInput | Prisma.MedicalRecordScalarWhereInput[]
  recordId?: Prisma.IntFilter<"MedicalRecord"> | number
  patientId?: Prisma.IntFilter<"MedicalRecord"> | number
  createdByUserId?: Prisma.IntFilter<"MedicalRecord"> | number
  recordType?: Prisma.StringFilter<"MedicalRecord"> | string
  title?: Prisma.StringFilter<"MedicalRecord"> | string
  clinicalNote?: Prisma.StringFilter<"MedicalRecord"> | string
  recordStatus?: Prisma.StringFilter<"MedicalRecord"> | string
  encounterDate?: Prisma.DateTimeFilter<"MedicalRecord"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"MedicalRecord"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MedicalRecord"> | Date | string
}

export type MedicalRecordCreateWithoutPatientRecordInput = {
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  patient: Prisma.UserCreateNestedOneWithoutMedicalRecordsInput
  diagnoses?: Prisma.RecordDiagnosisCreateNestedManyWithoutRecordInput
  prescriptions?: Prisma.RecordPrescriptionCreateNestedManyWithoutRecordInput
  treatments?: Prisma.RecordTreatmentCreateNestedManyWithoutRecordInput
}

export type MedicalRecordUncheckedCreateWithoutPatientRecordInput = {
  recordId?: number
  createdByUserId: number
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  diagnoses?: Prisma.RecordDiagnosisUncheckedCreateNestedManyWithoutRecordInput
  prescriptions?: Prisma.RecordPrescriptionUncheckedCreateNestedManyWithoutRecordInput
  treatments?: Prisma.RecordTreatmentUncheckedCreateNestedManyWithoutRecordInput
}

export type MedicalRecordCreateOrConnectWithoutPatientRecordInput = {
  where: Prisma.MedicalRecordWhereUniqueInput
  create: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientRecordInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientRecordInput>
}

export type MedicalRecordCreateManyPatientRecordInputEnvelope = {
  data: Prisma.MedicalRecordCreateManyPatientRecordInput | Prisma.MedicalRecordCreateManyPatientRecordInput[]
  skipDuplicates?: boolean
}

export type MedicalRecordUpsertWithWhereUniqueWithoutPatientRecordInput = {
  where: Prisma.MedicalRecordWhereUniqueInput
  update: Prisma.XOR<Prisma.MedicalRecordUpdateWithoutPatientRecordInput, Prisma.MedicalRecordUncheckedUpdateWithoutPatientRecordInput>
  create: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPatientRecordInput, Prisma.MedicalRecordUncheckedCreateWithoutPatientRecordInput>
}

export type MedicalRecordUpdateWithWhereUniqueWithoutPatientRecordInput = {
  where: Prisma.MedicalRecordWhereUniqueInput
  data: Prisma.XOR<Prisma.MedicalRecordUpdateWithoutPatientRecordInput, Prisma.MedicalRecordUncheckedUpdateWithoutPatientRecordInput>
}

export type MedicalRecordUpdateManyWithWhereWithoutPatientRecordInput = {
  where: Prisma.MedicalRecordScalarWhereInput
  data: Prisma.XOR<Prisma.MedicalRecordUpdateManyMutationInput, Prisma.MedicalRecordUncheckedUpdateManyWithoutPatientRecordInput>
}

export type MedicalRecordCreateWithoutDiagnosesInput = {
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  patient: Prisma.UserCreateNestedOneWithoutMedicalRecordsInput
  patientRecord: Prisma.PatientCreateNestedOneWithoutMedicalRecordsInput
  prescriptions?: Prisma.RecordPrescriptionCreateNestedManyWithoutRecordInput
  treatments?: Prisma.RecordTreatmentCreateNestedManyWithoutRecordInput
}

export type MedicalRecordUncheckedCreateWithoutDiagnosesInput = {
  recordId?: number
  patientId: number
  createdByUserId: number
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  prescriptions?: Prisma.RecordPrescriptionUncheckedCreateNestedManyWithoutRecordInput
  treatments?: Prisma.RecordTreatmentUncheckedCreateNestedManyWithoutRecordInput
}

export type MedicalRecordCreateOrConnectWithoutDiagnosesInput = {
  where: Prisma.MedicalRecordWhereUniqueInput
  create: Prisma.XOR<Prisma.MedicalRecordCreateWithoutDiagnosesInput, Prisma.MedicalRecordUncheckedCreateWithoutDiagnosesInput>
}

export type MedicalRecordUpsertWithoutDiagnosesInput = {
  update: Prisma.XOR<Prisma.MedicalRecordUpdateWithoutDiagnosesInput, Prisma.MedicalRecordUncheckedUpdateWithoutDiagnosesInput>
  create: Prisma.XOR<Prisma.MedicalRecordCreateWithoutDiagnosesInput, Prisma.MedicalRecordUncheckedCreateWithoutDiagnosesInput>
  where?: Prisma.MedicalRecordWhereInput
}

export type MedicalRecordUpdateToOneWithWhereWithoutDiagnosesInput = {
  where?: Prisma.MedicalRecordWhereInput
  data: Prisma.XOR<Prisma.MedicalRecordUpdateWithoutDiagnosesInput, Prisma.MedicalRecordUncheckedUpdateWithoutDiagnosesInput>
}

export type MedicalRecordUpdateWithoutDiagnosesInput = {
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  patient?: Prisma.UserUpdateOneRequiredWithoutMedicalRecordsNestedInput
  patientRecord?: Prisma.PatientUpdateOneRequiredWithoutMedicalRecordsNestedInput
  prescriptions?: Prisma.RecordPrescriptionUpdateManyWithoutRecordNestedInput
  treatments?: Prisma.RecordTreatmentUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordUncheckedUpdateWithoutDiagnosesInput = {
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  createdByUserId?: Prisma.IntFieldUpdateOperationsInput | number
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  prescriptions?: Prisma.RecordPrescriptionUncheckedUpdateManyWithoutRecordNestedInput
  treatments?: Prisma.RecordTreatmentUncheckedUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordCreateWithoutPrescriptionsInput = {
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  patient: Prisma.UserCreateNestedOneWithoutMedicalRecordsInput
  patientRecord: Prisma.PatientCreateNestedOneWithoutMedicalRecordsInput
  diagnoses?: Prisma.RecordDiagnosisCreateNestedManyWithoutRecordInput
  treatments?: Prisma.RecordTreatmentCreateNestedManyWithoutRecordInput
}

export type MedicalRecordUncheckedCreateWithoutPrescriptionsInput = {
  recordId?: number
  patientId: number
  createdByUserId: number
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  diagnoses?: Prisma.RecordDiagnosisUncheckedCreateNestedManyWithoutRecordInput
  treatments?: Prisma.RecordTreatmentUncheckedCreateNestedManyWithoutRecordInput
}

export type MedicalRecordCreateOrConnectWithoutPrescriptionsInput = {
  where: Prisma.MedicalRecordWhereUniqueInput
  create: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPrescriptionsInput, Prisma.MedicalRecordUncheckedCreateWithoutPrescriptionsInput>
}

export type MedicalRecordUpsertWithoutPrescriptionsInput = {
  update: Prisma.XOR<Prisma.MedicalRecordUpdateWithoutPrescriptionsInput, Prisma.MedicalRecordUncheckedUpdateWithoutPrescriptionsInput>
  create: Prisma.XOR<Prisma.MedicalRecordCreateWithoutPrescriptionsInput, Prisma.MedicalRecordUncheckedCreateWithoutPrescriptionsInput>
  where?: Prisma.MedicalRecordWhereInput
}

export type MedicalRecordUpdateToOneWithWhereWithoutPrescriptionsInput = {
  where?: Prisma.MedicalRecordWhereInput
  data: Prisma.XOR<Prisma.MedicalRecordUpdateWithoutPrescriptionsInput, Prisma.MedicalRecordUncheckedUpdateWithoutPrescriptionsInput>
}

export type MedicalRecordUpdateWithoutPrescriptionsInput = {
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  patient?: Prisma.UserUpdateOneRequiredWithoutMedicalRecordsNestedInput
  patientRecord?: Prisma.PatientUpdateOneRequiredWithoutMedicalRecordsNestedInput
  diagnoses?: Prisma.RecordDiagnosisUpdateManyWithoutRecordNestedInput
  treatments?: Prisma.RecordTreatmentUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordUncheckedUpdateWithoutPrescriptionsInput = {
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  createdByUserId?: Prisma.IntFieldUpdateOperationsInput | number
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  diagnoses?: Prisma.RecordDiagnosisUncheckedUpdateManyWithoutRecordNestedInput
  treatments?: Prisma.RecordTreatmentUncheckedUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordCreateWithoutTreatmentsInput = {
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  patient: Prisma.UserCreateNestedOneWithoutMedicalRecordsInput
  patientRecord: Prisma.PatientCreateNestedOneWithoutMedicalRecordsInput
  diagnoses?: Prisma.RecordDiagnosisCreateNestedManyWithoutRecordInput
  prescriptions?: Prisma.RecordPrescriptionCreateNestedManyWithoutRecordInput
}

export type MedicalRecordUncheckedCreateWithoutTreatmentsInput = {
  recordId?: number
  patientId: number
  createdByUserId: number
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  diagnoses?: Prisma.RecordDiagnosisUncheckedCreateNestedManyWithoutRecordInput
  prescriptions?: Prisma.RecordPrescriptionUncheckedCreateNestedManyWithoutRecordInput
}

export type MedicalRecordCreateOrConnectWithoutTreatmentsInput = {
  where: Prisma.MedicalRecordWhereUniqueInput
  create: Prisma.XOR<Prisma.MedicalRecordCreateWithoutTreatmentsInput, Prisma.MedicalRecordUncheckedCreateWithoutTreatmentsInput>
}

export type MedicalRecordUpsertWithoutTreatmentsInput = {
  update: Prisma.XOR<Prisma.MedicalRecordUpdateWithoutTreatmentsInput, Prisma.MedicalRecordUncheckedUpdateWithoutTreatmentsInput>
  create: Prisma.XOR<Prisma.MedicalRecordCreateWithoutTreatmentsInput, Prisma.MedicalRecordUncheckedCreateWithoutTreatmentsInput>
  where?: Prisma.MedicalRecordWhereInput
}

export type MedicalRecordUpdateToOneWithWhereWithoutTreatmentsInput = {
  where?: Prisma.MedicalRecordWhereInput
  data: Prisma.XOR<Prisma.MedicalRecordUpdateWithoutTreatmentsInput, Prisma.MedicalRecordUncheckedUpdateWithoutTreatmentsInput>
}

export type MedicalRecordUpdateWithoutTreatmentsInput = {
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  patient?: Prisma.UserUpdateOneRequiredWithoutMedicalRecordsNestedInput
  patientRecord?: Prisma.PatientUpdateOneRequiredWithoutMedicalRecordsNestedInput
  diagnoses?: Prisma.RecordDiagnosisUpdateManyWithoutRecordNestedInput
  prescriptions?: Prisma.RecordPrescriptionUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordUncheckedUpdateWithoutTreatmentsInput = {
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  createdByUserId?: Prisma.IntFieldUpdateOperationsInput | number
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  diagnoses?: Prisma.RecordDiagnosisUncheckedUpdateManyWithoutRecordNestedInput
  prescriptions?: Prisma.RecordPrescriptionUncheckedUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordCreateManyPatientInput = {
  recordId?: number
  patientId: number
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MedicalRecordUpdateWithoutPatientInput = {
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  patientRecord?: Prisma.PatientUpdateOneRequiredWithoutMedicalRecordsNestedInput
  diagnoses?: Prisma.RecordDiagnosisUpdateManyWithoutRecordNestedInput
  prescriptions?: Prisma.RecordPrescriptionUpdateManyWithoutRecordNestedInput
  treatments?: Prisma.RecordTreatmentUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordUncheckedUpdateWithoutPatientInput = {
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  diagnoses?: Prisma.RecordDiagnosisUncheckedUpdateManyWithoutRecordNestedInput
  prescriptions?: Prisma.RecordPrescriptionUncheckedUpdateManyWithoutRecordNestedInput
  treatments?: Prisma.RecordTreatmentUncheckedUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordUncheckedUpdateManyWithoutPatientInput = {
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  patientId?: Prisma.IntFieldUpdateOperationsInput | number
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MedicalRecordCreateManyPatientRecordInput = {
  recordId?: number
  createdByUserId: number
  recordType: string
  title: string
  clinicalNote: string
  recordStatus?: string
  encounterDate?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MedicalRecordUpdateWithoutPatientRecordInput = {
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  patient?: Prisma.UserUpdateOneRequiredWithoutMedicalRecordsNestedInput
  diagnoses?: Prisma.RecordDiagnosisUpdateManyWithoutRecordNestedInput
  prescriptions?: Prisma.RecordPrescriptionUpdateManyWithoutRecordNestedInput
  treatments?: Prisma.RecordTreatmentUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordUncheckedUpdateWithoutPatientRecordInput = {
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  createdByUserId?: Prisma.IntFieldUpdateOperationsInput | number
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  diagnoses?: Prisma.RecordDiagnosisUncheckedUpdateManyWithoutRecordNestedInput
  prescriptions?: Prisma.RecordPrescriptionUncheckedUpdateManyWithoutRecordNestedInput
  treatments?: Prisma.RecordTreatmentUncheckedUpdateManyWithoutRecordNestedInput
}

export type MedicalRecordUncheckedUpdateManyWithoutPatientRecordInput = {
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  createdByUserId?: Prisma.IntFieldUpdateOperationsInput | number
  recordType?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  clinicalNote?: Prisma.StringFieldUpdateOperationsInput | string
  recordStatus?: Prisma.StringFieldUpdateOperationsInput | string
  encounterDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type MedicalRecordCountOutputType
 */

export type MedicalRecordCountOutputType = {
  diagnoses: number
  prescriptions: number
  treatments: number
}

export type MedicalRecordCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  diagnoses?: boolean | MedicalRecordCountOutputTypeCountDiagnosesArgs
  prescriptions?: boolean | MedicalRecordCountOutputTypeCountPrescriptionsArgs
  treatments?: boolean | MedicalRecordCountOutputTypeCountTreatmentsArgs
}

/**
 * MedicalRecordCountOutputType without action
 */
export type MedicalRecordCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecordCountOutputType
   */
  select?: Prisma.MedicalRecordCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MedicalRecordCountOutputType without action
 */
export type MedicalRecordCountOutputTypeCountDiagnosesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecordDiagnosisWhereInput
}

/**
 * MedicalRecordCountOutputType without action
 */
export type MedicalRecordCountOutputTypeCountPrescriptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecordPrescriptionWhereInput
}

/**
 * MedicalRecordCountOutputType without action
 */
export type MedicalRecordCountOutputTypeCountTreatmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecordTreatmentWhereInput
}


export type MedicalRecordSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recordId?: boolean
  patientId?: boolean
  createdByUserId?: boolean
  recordType?: boolean
  title?: boolean
  clinicalNote?: boolean
  recordStatus?: boolean
  encounterDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  patientRecord?: boolean | Prisma.PatientDefaultArgs<ExtArgs>
  diagnoses?: boolean | Prisma.MedicalRecord$diagnosesArgs<ExtArgs>
  prescriptions?: boolean | Prisma.MedicalRecord$prescriptionsArgs<ExtArgs>
  treatments?: boolean | Prisma.MedicalRecord$treatmentsArgs<ExtArgs>
  _count?: boolean | Prisma.MedicalRecordCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["medicalRecord"]>

export type MedicalRecordSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recordId?: boolean
  patientId?: boolean
  createdByUserId?: boolean
  recordType?: boolean
  title?: boolean
  clinicalNote?: boolean
  recordStatus?: boolean
  encounterDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  patientRecord?: boolean | Prisma.PatientDefaultArgs<ExtArgs>
}, ExtArgs["result"]["medicalRecord"]>

export type MedicalRecordSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  recordId?: boolean
  patientId?: boolean
  createdByUserId?: boolean
  recordType?: boolean
  title?: boolean
  clinicalNote?: boolean
  recordStatus?: boolean
  encounterDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  patientRecord?: boolean | Prisma.PatientDefaultArgs<ExtArgs>
}, ExtArgs["result"]["medicalRecord"]>

export type MedicalRecordSelectScalar = {
  recordId?: boolean
  patientId?: boolean
  createdByUserId?: boolean
  recordType?: boolean
  title?: boolean
  clinicalNote?: boolean
  recordStatus?: boolean
  encounterDate?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MedicalRecordOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"recordId" | "patientId" | "createdByUserId" | "recordType" | "title" | "clinicalNote" | "recordStatus" | "encounterDate" | "createdAt" | "updatedAt", ExtArgs["result"]["medicalRecord"]>
export type MedicalRecordInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  patientRecord?: boolean | Prisma.PatientDefaultArgs<ExtArgs>
  diagnoses?: boolean | Prisma.MedicalRecord$diagnosesArgs<ExtArgs>
  prescriptions?: boolean | Prisma.MedicalRecord$prescriptionsArgs<ExtArgs>
  treatments?: boolean | Prisma.MedicalRecord$treatmentsArgs<ExtArgs>
  _count?: boolean | Prisma.MedicalRecordCountOutputTypeDefaultArgs<ExtArgs>
}
export type MedicalRecordIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  patientRecord?: boolean | Prisma.PatientDefaultArgs<ExtArgs>
}
export type MedicalRecordIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  patient?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  patientRecord?: boolean | Prisma.PatientDefaultArgs<ExtArgs>
}

export type $MedicalRecordPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MedicalRecord"
  objects: {
    patient: Prisma.$UserPayload<ExtArgs>
    patientRecord: Prisma.$PatientPayload<ExtArgs>
    diagnoses: Prisma.$RecordDiagnosisPayload<ExtArgs>[]
    prescriptions: Prisma.$RecordPrescriptionPayload<ExtArgs>[]
    treatments: Prisma.$RecordTreatmentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    recordId: number
    patientId: number
    createdByUserId: number
    recordType: string
    title: string
    clinicalNote: string
    recordStatus: string
    encounterDate: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["medicalRecord"]>
  composites: {}
}

export type MedicalRecordGetPayload<S extends boolean | null | undefined | MedicalRecordDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload, S>

export type MedicalRecordCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MedicalRecordFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MedicalRecordCountAggregateInputType | true
  }

export interface MedicalRecordDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MedicalRecord'], meta: { name: 'MedicalRecord' } }
  /**
   * Find zero or one MedicalRecord that matches the filter.
   * @param {MedicalRecordFindUniqueArgs} args - Arguments to find a MedicalRecord
   * @example
   * // Get one MedicalRecord
   * const medicalRecord = await prisma.medicalRecord.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MedicalRecordFindUniqueArgs>(args: Prisma.SelectSubset<T, MedicalRecordFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MedicalRecordClient<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MedicalRecord that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MedicalRecordFindUniqueOrThrowArgs} args - Arguments to find a MedicalRecord
   * @example
   * // Get one MedicalRecord
   * const medicalRecord = await prisma.medicalRecord.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MedicalRecordFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MedicalRecordFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MedicalRecordClient<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MedicalRecord that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MedicalRecordFindFirstArgs} args - Arguments to find a MedicalRecord
   * @example
   * // Get one MedicalRecord
   * const medicalRecord = await prisma.medicalRecord.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MedicalRecordFindFirstArgs>(args?: Prisma.SelectSubset<T, MedicalRecordFindFirstArgs<ExtArgs>>): Prisma.Prisma__MedicalRecordClient<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MedicalRecord that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MedicalRecordFindFirstOrThrowArgs} args - Arguments to find a MedicalRecord
   * @example
   * // Get one MedicalRecord
   * const medicalRecord = await prisma.medicalRecord.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MedicalRecordFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MedicalRecordFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MedicalRecordClient<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MedicalRecords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MedicalRecordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MedicalRecords
   * const medicalRecords = await prisma.medicalRecord.findMany()
   * 
   * // Get first 10 MedicalRecords
   * const medicalRecords = await prisma.medicalRecord.findMany({ take: 10 })
   * 
   * // Only select the `recordId`
   * const medicalRecordWithRecordIdOnly = await prisma.medicalRecord.findMany({ select: { recordId: true } })
   * 
   */
  findMany<T extends MedicalRecordFindManyArgs>(args?: Prisma.SelectSubset<T, MedicalRecordFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MedicalRecord.
   * @param {MedicalRecordCreateArgs} args - Arguments to create a MedicalRecord.
   * @example
   * // Create one MedicalRecord
   * const MedicalRecord = await prisma.medicalRecord.create({
   *   data: {
   *     // ... data to create a MedicalRecord
   *   }
   * })
   * 
   */
  create<T extends MedicalRecordCreateArgs>(args: Prisma.SelectSubset<T, MedicalRecordCreateArgs<ExtArgs>>): Prisma.Prisma__MedicalRecordClient<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MedicalRecords.
   * @param {MedicalRecordCreateManyArgs} args - Arguments to create many MedicalRecords.
   * @example
   * // Create many MedicalRecords
   * const medicalRecord = await prisma.medicalRecord.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MedicalRecordCreateManyArgs>(args?: Prisma.SelectSubset<T, MedicalRecordCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MedicalRecords and returns the data saved in the database.
   * @param {MedicalRecordCreateManyAndReturnArgs} args - Arguments to create many MedicalRecords.
   * @example
   * // Create many MedicalRecords
   * const medicalRecord = await prisma.medicalRecord.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MedicalRecords and only return the `recordId`
   * const medicalRecordWithRecordIdOnly = await prisma.medicalRecord.createManyAndReturn({
   *   select: { recordId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MedicalRecordCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MedicalRecordCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MedicalRecord.
   * @param {MedicalRecordDeleteArgs} args - Arguments to delete one MedicalRecord.
   * @example
   * // Delete one MedicalRecord
   * const MedicalRecord = await prisma.medicalRecord.delete({
   *   where: {
   *     // ... filter to delete one MedicalRecord
   *   }
   * })
   * 
   */
  delete<T extends MedicalRecordDeleteArgs>(args: Prisma.SelectSubset<T, MedicalRecordDeleteArgs<ExtArgs>>): Prisma.Prisma__MedicalRecordClient<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MedicalRecord.
   * @param {MedicalRecordUpdateArgs} args - Arguments to update one MedicalRecord.
   * @example
   * // Update one MedicalRecord
   * const medicalRecord = await prisma.medicalRecord.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MedicalRecordUpdateArgs>(args: Prisma.SelectSubset<T, MedicalRecordUpdateArgs<ExtArgs>>): Prisma.Prisma__MedicalRecordClient<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MedicalRecords.
   * @param {MedicalRecordDeleteManyArgs} args - Arguments to filter MedicalRecords to delete.
   * @example
   * // Delete a few MedicalRecords
   * const { count } = await prisma.medicalRecord.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MedicalRecordDeleteManyArgs>(args?: Prisma.SelectSubset<T, MedicalRecordDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MedicalRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MedicalRecordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MedicalRecords
   * const medicalRecord = await prisma.medicalRecord.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MedicalRecordUpdateManyArgs>(args: Prisma.SelectSubset<T, MedicalRecordUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MedicalRecords and returns the data updated in the database.
   * @param {MedicalRecordUpdateManyAndReturnArgs} args - Arguments to update many MedicalRecords.
   * @example
   * // Update many MedicalRecords
   * const medicalRecord = await prisma.medicalRecord.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MedicalRecords and only return the `recordId`
   * const medicalRecordWithRecordIdOnly = await prisma.medicalRecord.updateManyAndReturn({
   *   select: { recordId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MedicalRecordUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MedicalRecordUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MedicalRecord.
   * @param {MedicalRecordUpsertArgs} args - Arguments to update or create a MedicalRecord.
   * @example
   * // Update or create a MedicalRecord
   * const medicalRecord = await prisma.medicalRecord.upsert({
   *   create: {
   *     // ... data to create a MedicalRecord
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MedicalRecord we want to update
   *   }
   * })
   */
  upsert<T extends MedicalRecordUpsertArgs>(args: Prisma.SelectSubset<T, MedicalRecordUpsertArgs<ExtArgs>>): Prisma.Prisma__MedicalRecordClient<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MedicalRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MedicalRecordCountArgs} args - Arguments to filter MedicalRecords to count.
   * @example
   * // Count the number of MedicalRecords
   * const count = await prisma.medicalRecord.count({
   *   where: {
   *     // ... the filter for the MedicalRecords we want to count
   *   }
   * })
  **/
  count<T extends MedicalRecordCountArgs>(
    args?: Prisma.Subset<T, MedicalRecordCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MedicalRecordCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MedicalRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MedicalRecordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MedicalRecordAggregateArgs>(args: Prisma.Subset<T, MedicalRecordAggregateArgs>): Prisma.PrismaPromise<GetMedicalRecordAggregateType<T>>

  /**
   * Group by MedicalRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MedicalRecordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MedicalRecordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MedicalRecordGroupByArgs['orderBy'] }
      : { orderBy?: MedicalRecordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MedicalRecordGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMedicalRecordGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MedicalRecord model
 */
readonly fields: MedicalRecordFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MedicalRecord.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MedicalRecordClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  patient<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  patientRecord<T extends Prisma.PatientDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PatientDefaultArgs<ExtArgs>>): Prisma.Prisma__PatientClient<runtime.Types.Result.GetResult<Prisma.$PatientPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  diagnoses<T extends Prisma.MedicalRecord$diagnosesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MedicalRecord$diagnosesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordDiagnosisPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  prescriptions<T extends Prisma.MedicalRecord$prescriptionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MedicalRecord$prescriptionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  treatments<T extends Prisma.MedicalRecord$treatmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MedicalRecord$treatmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordTreatmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MedicalRecord model
 */
export interface MedicalRecordFieldRefs {
  readonly recordId: Prisma.FieldRef<"MedicalRecord", 'Int'>
  readonly patientId: Prisma.FieldRef<"MedicalRecord", 'Int'>
  readonly createdByUserId: Prisma.FieldRef<"MedicalRecord", 'Int'>
  readonly recordType: Prisma.FieldRef<"MedicalRecord", 'String'>
  readonly title: Prisma.FieldRef<"MedicalRecord", 'String'>
  readonly clinicalNote: Prisma.FieldRef<"MedicalRecord", 'String'>
  readonly recordStatus: Prisma.FieldRef<"MedicalRecord", 'String'>
  readonly encounterDate: Prisma.FieldRef<"MedicalRecord", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"MedicalRecord", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MedicalRecord", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MedicalRecord findUnique
 */
export type MedicalRecordFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordInclude<ExtArgs> | null
  /**
   * Filter, which MedicalRecord to fetch.
   */
  where: Prisma.MedicalRecordWhereUniqueInput
}

/**
 * MedicalRecord findUniqueOrThrow
 */
export type MedicalRecordFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordInclude<ExtArgs> | null
  /**
   * Filter, which MedicalRecord to fetch.
   */
  where: Prisma.MedicalRecordWhereUniqueInput
}

/**
 * MedicalRecord findFirst
 */
export type MedicalRecordFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordInclude<ExtArgs> | null
  /**
   * Filter, which MedicalRecord to fetch.
   */
  where?: Prisma.MedicalRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MedicalRecords to fetch.
   */
  orderBy?: Prisma.MedicalRecordOrderByWithRelationInput | Prisma.MedicalRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MedicalRecords.
   */
  cursor?: Prisma.MedicalRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MedicalRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MedicalRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MedicalRecords.
   */
  distinct?: Prisma.MedicalRecordScalarFieldEnum | Prisma.MedicalRecordScalarFieldEnum[]
}

/**
 * MedicalRecord findFirstOrThrow
 */
export type MedicalRecordFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordInclude<ExtArgs> | null
  /**
   * Filter, which MedicalRecord to fetch.
   */
  where?: Prisma.MedicalRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MedicalRecords to fetch.
   */
  orderBy?: Prisma.MedicalRecordOrderByWithRelationInput | Prisma.MedicalRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MedicalRecords.
   */
  cursor?: Prisma.MedicalRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MedicalRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MedicalRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MedicalRecords.
   */
  distinct?: Prisma.MedicalRecordScalarFieldEnum | Prisma.MedicalRecordScalarFieldEnum[]
}

/**
 * MedicalRecord findMany
 */
export type MedicalRecordFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordInclude<ExtArgs> | null
  /**
   * Filter, which MedicalRecords to fetch.
   */
  where?: Prisma.MedicalRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MedicalRecords to fetch.
   */
  orderBy?: Prisma.MedicalRecordOrderByWithRelationInput | Prisma.MedicalRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MedicalRecords.
   */
  cursor?: Prisma.MedicalRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MedicalRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MedicalRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MedicalRecords.
   */
  distinct?: Prisma.MedicalRecordScalarFieldEnum | Prisma.MedicalRecordScalarFieldEnum[]
}

/**
 * MedicalRecord create
 */
export type MedicalRecordCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordInclude<ExtArgs> | null
  /**
   * The data needed to create a MedicalRecord.
   */
  data: Prisma.XOR<Prisma.MedicalRecordCreateInput, Prisma.MedicalRecordUncheckedCreateInput>
}

/**
 * MedicalRecord createMany
 */
export type MedicalRecordCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MedicalRecords.
   */
  data: Prisma.MedicalRecordCreateManyInput | Prisma.MedicalRecordCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MedicalRecord createManyAndReturn
 */
export type MedicalRecordCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * The data used to create many MedicalRecords.
   */
  data: Prisma.MedicalRecordCreateManyInput | Prisma.MedicalRecordCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MedicalRecord update
 */
export type MedicalRecordUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordInclude<ExtArgs> | null
  /**
   * The data needed to update a MedicalRecord.
   */
  data: Prisma.XOR<Prisma.MedicalRecordUpdateInput, Prisma.MedicalRecordUncheckedUpdateInput>
  /**
   * Choose, which MedicalRecord to update.
   */
  where: Prisma.MedicalRecordWhereUniqueInput
}

/**
 * MedicalRecord updateMany
 */
export type MedicalRecordUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MedicalRecords.
   */
  data: Prisma.XOR<Prisma.MedicalRecordUpdateManyMutationInput, Prisma.MedicalRecordUncheckedUpdateManyInput>
  /**
   * Filter which MedicalRecords to update
   */
  where?: Prisma.MedicalRecordWhereInput
  /**
   * Limit how many MedicalRecords to update.
   */
  limit?: number
}

/**
 * MedicalRecord updateManyAndReturn
 */
export type MedicalRecordUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * The data used to update MedicalRecords.
   */
  data: Prisma.XOR<Prisma.MedicalRecordUpdateManyMutationInput, Prisma.MedicalRecordUncheckedUpdateManyInput>
  /**
   * Filter which MedicalRecords to update
   */
  where?: Prisma.MedicalRecordWhereInput
  /**
   * Limit how many MedicalRecords to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MedicalRecord upsert
 */
export type MedicalRecordUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordInclude<ExtArgs> | null
  /**
   * The filter to search for the MedicalRecord to update in case it exists.
   */
  where: Prisma.MedicalRecordWhereUniqueInput
  /**
   * In case the MedicalRecord found by the `where` argument doesn't exist, create a new MedicalRecord with this data.
   */
  create: Prisma.XOR<Prisma.MedicalRecordCreateInput, Prisma.MedicalRecordUncheckedCreateInput>
  /**
   * In case the MedicalRecord was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MedicalRecordUpdateInput, Prisma.MedicalRecordUncheckedUpdateInput>
}

/**
 * MedicalRecord delete
 */
export type MedicalRecordDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordInclude<ExtArgs> | null
  /**
   * Filter which MedicalRecord to delete.
   */
  where: Prisma.MedicalRecordWhereUniqueInput
}

/**
 * MedicalRecord deleteMany
 */
export type MedicalRecordDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MedicalRecords to delete
   */
  where?: Prisma.MedicalRecordWhereInput
  /**
   * Limit how many MedicalRecords to delete.
   */
  limit?: number
}

/**
 * MedicalRecord.diagnoses
 */
export type MedicalRecord$diagnosesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordDiagnosis
   */
  select?: Prisma.RecordDiagnosisSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordDiagnosis
   */
  omit?: Prisma.RecordDiagnosisOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordDiagnosisInclude<ExtArgs> | null
  where?: Prisma.RecordDiagnosisWhereInput
  orderBy?: Prisma.RecordDiagnosisOrderByWithRelationInput | Prisma.RecordDiagnosisOrderByWithRelationInput[]
  cursor?: Prisma.RecordDiagnosisWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecordDiagnosisScalarFieldEnum | Prisma.RecordDiagnosisScalarFieldEnum[]
}

/**
 * MedicalRecord.prescriptions
 */
export type MedicalRecord$prescriptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionInclude<ExtArgs> | null
  where?: Prisma.RecordPrescriptionWhereInput
  orderBy?: Prisma.RecordPrescriptionOrderByWithRelationInput | Prisma.RecordPrescriptionOrderByWithRelationInput[]
  cursor?: Prisma.RecordPrescriptionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecordPrescriptionScalarFieldEnum | Prisma.RecordPrescriptionScalarFieldEnum[]
}

/**
 * MedicalRecord.treatments
 */
export type MedicalRecord$treatmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordTreatment
   */
  select?: Prisma.RecordTreatmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordTreatment
   */
  omit?: Prisma.RecordTreatmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordTreatmentInclude<ExtArgs> | null
  where?: Prisma.RecordTreatmentWhereInput
  orderBy?: Prisma.RecordTreatmentOrderByWithRelationInput | Prisma.RecordTreatmentOrderByWithRelationInput[]
  cursor?: Prisma.RecordTreatmentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RecordTreatmentScalarFieldEnum | Prisma.RecordTreatmentScalarFieldEnum[]
}

/**
 * MedicalRecord without action
 */
export type MedicalRecordDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MedicalRecord
   */
  select?: Prisma.MedicalRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MedicalRecord
   */
  omit?: Prisma.MedicalRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MedicalRecordInclude<ExtArgs> | null
}
