
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RecordPrescription` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RecordPrescription
 * 
 */
export type RecordPrescriptionModel = runtime.Types.Result.DefaultSelection<Prisma.$RecordPrescriptionPayload>

export type AggregateRecordPrescription = {
  _count: RecordPrescriptionCountAggregateOutputType | null
  _avg: RecordPrescriptionAvgAggregateOutputType | null
  _sum: RecordPrescriptionSumAggregateOutputType | null
  _min: RecordPrescriptionMinAggregateOutputType | null
  _max: RecordPrescriptionMaxAggregateOutputType | null
}

export type RecordPrescriptionAvgAggregateOutputType = {
  prescriptionId: number | null
  recordId: number | null
  durationDays: number | null
}

export type RecordPrescriptionSumAggregateOutputType = {
  prescriptionId: number | null
  recordId: number | null
  durationDays: number | null
}

export type RecordPrescriptionMinAggregateOutputType = {
  prescriptionId: number | null
  recordId: number | null
  medicationName: string | null
  dosage: string | null
  frequency: string | null
  route: string | null
  durationDays: number | null
  instructions: string | null
  prescriptionStatus: string | null
  isActive: string | null
  prescribedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RecordPrescriptionMaxAggregateOutputType = {
  prescriptionId: number | null
  recordId: number | null
  medicationName: string | null
  dosage: string | null
  frequency: string | null
  route: string | null
  durationDays: number | null
  instructions: string | null
  prescriptionStatus: string | null
  isActive: string | null
  prescribedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RecordPrescriptionCountAggregateOutputType = {
  prescriptionId: number
  recordId: number
  medicationName: number
  dosage: number
  frequency: number
  route: number
  durationDays: number
  instructions: number
  prescriptionStatus: number
  isActive: number
  prescribedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type RecordPrescriptionAvgAggregateInputType = {
  prescriptionId?: true
  recordId?: true
  durationDays?: true
}

export type RecordPrescriptionSumAggregateInputType = {
  prescriptionId?: true
  recordId?: true
  durationDays?: true
}

export type RecordPrescriptionMinAggregateInputType = {
  prescriptionId?: true
  recordId?: true
  medicationName?: true
  dosage?: true
  frequency?: true
  route?: true
  durationDays?: true
  instructions?: true
  prescriptionStatus?: true
  isActive?: true
  prescribedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type RecordPrescriptionMaxAggregateInputType = {
  prescriptionId?: true
  recordId?: true
  medicationName?: true
  dosage?: true
  frequency?: true
  route?: true
  durationDays?: true
  instructions?: true
  prescriptionStatus?: true
  isActive?: true
  prescribedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type RecordPrescriptionCountAggregateInputType = {
  prescriptionId?: true
  recordId?: true
  medicationName?: true
  dosage?: true
  frequency?: true
  route?: true
  durationDays?: true
  instructions?: true
  prescriptionStatus?: true
  isActive?: true
  prescribedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type RecordPrescriptionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecordPrescription to aggregate.
   */
  where?: Prisma.RecordPrescriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordPrescriptions to fetch.
   */
  orderBy?: Prisma.RecordPrescriptionOrderByWithRelationInput | Prisma.RecordPrescriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RecordPrescriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordPrescriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordPrescriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RecordPrescriptions
  **/
  _count?: true | RecordPrescriptionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RecordPrescriptionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RecordPrescriptionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RecordPrescriptionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RecordPrescriptionMaxAggregateInputType
}

export type GetRecordPrescriptionAggregateType<T extends RecordPrescriptionAggregateArgs> = {
      [P in keyof T & keyof AggregateRecordPrescription]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRecordPrescription[P]>
    : Prisma.GetScalarType<T[P], AggregateRecordPrescription[P]>
}




export type RecordPrescriptionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RecordPrescriptionWhereInput
  orderBy?: Prisma.RecordPrescriptionOrderByWithAggregationInput | Prisma.RecordPrescriptionOrderByWithAggregationInput[]
  by: Prisma.RecordPrescriptionScalarFieldEnum[] | Prisma.RecordPrescriptionScalarFieldEnum
  having?: Prisma.RecordPrescriptionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RecordPrescriptionCountAggregateInputType | true
  _avg?: RecordPrescriptionAvgAggregateInputType
  _sum?: RecordPrescriptionSumAggregateInputType
  _min?: RecordPrescriptionMinAggregateInputType
  _max?: RecordPrescriptionMaxAggregateInputType
}

export type RecordPrescriptionGroupByOutputType = {
  prescriptionId: number
  recordId: number
  medicationName: string
  dosage: string | null
  frequency: string | null
  route: string | null
  durationDays: number | null
  instructions: string | null
  prescriptionStatus: string
  isActive: string
  prescribedAt: Date
  createdAt: Date
  updatedAt: Date
  _count: RecordPrescriptionCountAggregateOutputType | null
  _avg: RecordPrescriptionAvgAggregateOutputType | null
  _sum: RecordPrescriptionSumAggregateOutputType | null
  _min: RecordPrescriptionMinAggregateOutputType | null
  _max: RecordPrescriptionMaxAggregateOutputType | null
}

export type GetRecordPrescriptionGroupByPayload<T extends RecordPrescriptionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RecordPrescriptionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RecordPrescriptionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RecordPrescriptionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RecordPrescriptionGroupByOutputType[P]>
      }
    >
  >



export type RecordPrescriptionWhereInput = {
  AND?: Prisma.RecordPrescriptionWhereInput | Prisma.RecordPrescriptionWhereInput[]
  OR?: Prisma.RecordPrescriptionWhereInput[]
  NOT?: Prisma.RecordPrescriptionWhereInput | Prisma.RecordPrescriptionWhereInput[]
  prescriptionId?: Prisma.IntFilter<"RecordPrescription"> | number
  recordId?: Prisma.IntFilter<"RecordPrescription"> | number
  medicationName?: Prisma.StringFilter<"RecordPrescription"> | string
  dosage?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  frequency?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  route?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  durationDays?: Prisma.IntNullableFilter<"RecordPrescription"> | number | null
  instructions?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  prescriptionStatus?: Prisma.StringFilter<"RecordPrescription"> | string
  isActive?: Prisma.StringFilter<"RecordPrescription"> | string
  prescribedAt?: Prisma.DateTimeFilter<"RecordPrescription"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"RecordPrescription"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecordPrescription"> | Date | string
  record?: Prisma.XOR<Prisma.MedicalRecordScalarRelationFilter, Prisma.MedicalRecordWhereInput>
}

export type RecordPrescriptionOrderByWithRelationInput = {
  prescriptionId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  medicationName?: Prisma.SortOrder
  dosage?: Prisma.SortOrderInput | Prisma.SortOrder
  frequency?: Prisma.SortOrderInput | Prisma.SortOrder
  route?: Prisma.SortOrderInput | Prisma.SortOrder
  durationDays?: Prisma.SortOrderInput | Prisma.SortOrder
  instructions?: Prisma.SortOrderInput | Prisma.SortOrder
  prescriptionStatus?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  prescribedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  record?: Prisma.MedicalRecordOrderByWithRelationInput
}

export type RecordPrescriptionWhereUniqueInput = Prisma.AtLeast<{
  prescriptionId?: number
  AND?: Prisma.RecordPrescriptionWhereInput | Prisma.RecordPrescriptionWhereInput[]
  OR?: Prisma.RecordPrescriptionWhereInput[]
  NOT?: Prisma.RecordPrescriptionWhereInput | Prisma.RecordPrescriptionWhereInput[]
  recordId?: Prisma.IntFilter<"RecordPrescription"> | number
  medicationName?: Prisma.StringFilter<"RecordPrescription"> | string
  dosage?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  frequency?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  route?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  durationDays?: Prisma.IntNullableFilter<"RecordPrescription"> | number | null
  instructions?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  prescriptionStatus?: Prisma.StringFilter<"RecordPrescription"> | string
  isActive?: Prisma.StringFilter<"RecordPrescription"> | string
  prescribedAt?: Prisma.DateTimeFilter<"RecordPrescription"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"RecordPrescription"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecordPrescription"> | Date | string
  record?: Prisma.XOR<Prisma.MedicalRecordScalarRelationFilter, Prisma.MedicalRecordWhereInput>
}, "prescriptionId">

export type RecordPrescriptionOrderByWithAggregationInput = {
  prescriptionId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  medicationName?: Prisma.SortOrder
  dosage?: Prisma.SortOrderInput | Prisma.SortOrder
  frequency?: Prisma.SortOrderInput | Prisma.SortOrder
  route?: Prisma.SortOrderInput | Prisma.SortOrder
  durationDays?: Prisma.SortOrderInput | Prisma.SortOrder
  instructions?: Prisma.SortOrderInput | Prisma.SortOrder
  prescriptionStatus?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  prescribedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.RecordPrescriptionCountOrderByAggregateInput
  _avg?: Prisma.RecordPrescriptionAvgOrderByAggregateInput
  _max?: Prisma.RecordPrescriptionMaxOrderByAggregateInput
  _min?: Prisma.RecordPrescriptionMinOrderByAggregateInput
  _sum?: Prisma.RecordPrescriptionSumOrderByAggregateInput
}

export type RecordPrescriptionScalarWhereWithAggregatesInput = {
  AND?: Prisma.RecordPrescriptionScalarWhereWithAggregatesInput | Prisma.RecordPrescriptionScalarWhereWithAggregatesInput[]
  OR?: Prisma.RecordPrescriptionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RecordPrescriptionScalarWhereWithAggregatesInput | Prisma.RecordPrescriptionScalarWhereWithAggregatesInput[]
  prescriptionId?: Prisma.IntWithAggregatesFilter<"RecordPrescription"> | number
  recordId?: Prisma.IntWithAggregatesFilter<"RecordPrescription"> | number
  medicationName?: Prisma.StringWithAggregatesFilter<"RecordPrescription"> | string
  dosage?: Prisma.StringNullableWithAggregatesFilter<"RecordPrescription"> | string | null
  frequency?: Prisma.StringNullableWithAggregatesFilter<"RecordPrescription"> | string | null
  route?: Prisma.StringNullableWithAggregatesFilter<"RecordPrescription"> | string | null
  durationDays?: Prisma.IntNullableWithAggregatesFilter<"RecordPrescription"> | number | null
  instructions?: Prisma.StringNullableWithAggregatesFilter<"RecordPrescription"> | string | null
  prescriptionStatus?: Prisma.StringWithAggregatesFilter<"RecordPrescription"> | string
  isActive?: Prisma.StringWithAggregatesFilter<"RecordPrescription"> | string
  prescribedAt?: Prisma.DateTimeWithAggregatesFilter<"RecordPrescription"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RecordPrescription"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RecordPrescription"> | Date | string
}

export type RecordPrescriptionCreateInput = {
  medicationName: string
  dosage?: string | null
  frequency?: string | null
  route?: string | null
  durationDays?: number | null
  instructions?: string | null
  prescriptionStatus?: string
  isActive?: string
  prescribedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  record: Prisma.MedicalRecordCreateNestedOneWithoutPrescriptionsInput
}

export type RecordPrescriptionUncheckedCreateInput = {
  prescriptionId?: number
  recordId: number
  medicationName: string
  dosage?: string | null
  frequency?: string | null
  route?: string | null
  durationDays?: number | null
  instructions?: string | null
  prescriptionStatus?: string
  isActive?: string
  prescribedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordPrescriptionUpdateInput = {
  medicationName?: Prisma.StringFieldUpdateOperationsInput | string
  dosage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  frequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  route?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prescriptionStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  prescribedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  record?: Prisma.MedicalRecordUpdateOneRequiredWithoutPrescriptionsNestedInput
}

export type RecordPrescriptionUncheckedUpdateInput = {
  prescriptionId?: Prisma.IntFieldUpdateOperationsInput | number
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  medicationName?: Prisma.StringFieldUpdateOperationsInput | string
  dosage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  frequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  route?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prescriptionStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  prescribedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordPrescriptionCreateManyInput = {
  prescriptionId?: number
  recordId: number
  medicationName: string
  dosage?: string | null
  frequency?: string | null
  route?: string | null
  durationDays?: number | null
  instructions?: string | null
  prescriptionStatus?: string
  isActive?: string
  prescribedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordPrescriptionUpdateManyMutationInput = {
  medicationName?: Prisma.StringFieldUpdateOperationsInput | string
  dosage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  frequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  route?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prescriptionStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  prescribedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordPrescriptionUncheckedUpdateManyInput = {
  prescriptionId?: Prisma.IntFieldUpdateOperationsInput | number
  recordId?: Prisma.IntFieldUpdateOperationsInput | number
  medicationName?: Prisma.StringFieldUpdateOperationsInput | string
  dosage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  frequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  route?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prescriptionStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  prescribedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordPrescriptionListRelationFilter = {
  every?: Prisma.RecordPrescriptionWhereInput
  some?: Prisma.RecordPrescriptionWhereInput
  none?: Prisma.RecordPrescriptionWhereInput
}

export type RecordPrescriptionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RecordPrescriptionCountOrderByAggregateInput = {
  prescriptionId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  medicationName?: Prisma.SortOrder
  dosage?: Prisma.SortOrder
  frequency?: Prisma.SortOrder
  route?: Prisma.SortOrder
  durationDays?: Prisma.SortOrder
  instructions?: Prisma.SortOrder
  prescriptionStatus?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  prescribedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecordPrescriptionAvgOrderByAggregateInput = {
  prescriptionId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  durationDays?: Prisma.SortOrder
}

export type RecordPrescriptionMaxOrderByAggregateInput = {
  prescriptionId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  medicationName?: Prisma.SortOrder
  dosage?: Prisma.SortOrder
  frequency?: Prisma.SortOrder
  route?: Prisma.SortOrder
  durationDays?: Prisma.SortOrder
  instructions?: Prisma.SortOrder
  prescriptionStatus?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  prescribedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecordPrescriptionMinOrderByAggregateInput = {
  prescriptionId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  medicationName?: Prisma.SortOrder
  dosage?: Prisma.SortOrder
  frequency?: Prisma.SortOrder
  route?: Prisma.SortOrder
  durationDays?: Prisma.SortOrder
  instructions?: Prisma.SortOrder
  prescriptionStatus?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  prescribedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RecordPrescriptionSumOrderByAggregateInput = {
  prescriptionId?: Prisma.SortOrder
  recordId?: Prisma.SortOrder
  durationDays?: Prisma.SortOrder
}

export type RecordPrescriptionCreateNestedManyWithoutRecordInput = {
  create?: Prisma.XOR<Prisma.RecordPrescriptionCreateWithoutRecordInput, Prisma.RecordPrescriptionUncheckedCreateWithoutRecordInput> | Prisma.RecordPrescriptionCreateWithoutRecordInput[] | Prisma.RecordPrescriptionUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordPrescriptionCreateOrConnectWithoutRecordInput | Prisma.RecordPrescriptionCreateOrConnectWithoutRecordInput[]
  createMany?: Prisma.RecordPrescriptionCreateManyRecordInputEnvelope
  connect?: Prisma.RecordPrescriptionWhereUniqueInput | Prisma.RecordPrescriptionWhereUniqueInput[]
}

export type RecordPrescriptionUncheckedCreateNestedManyWithoutRecordInput = {
  create?: Prisma.XOR<Prisma.RecordPrescriptionCreateWithoutRecordInput, Prisma.RecordPrescriptionUncheckedCreateWithoutRecordInput> | Prisma.RecordPrescriptionCreateWithoutRecordInput[] | Prisma.RecordPrescriptionUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordPrescriptionCreateOrConnectWithoutRecordInput | Prisma.RecordPrescriptionCreateOrConnectWithoutRecordInput[]
  createMany?: Prisma.RecordPrescriptionCreateManyRecordInputEnvelope
  connect?: Prisma.RecordPrescriptionWhereUniqueInput | Prisma.RecordPrescriptionWhereUniqueInput[]
}

export type RecordPrescriptionUpdateManyWithoutRecordNestedInput = {
  create?: Prisma.XOR<Prisma.RecordPrescriptionCreateWithoutRecordInput, Prisma.RecordPrescriptionUncheckedCreateWithoutRecordInput> | Prisma.RecordPrescriptionCreateWithoutRecordInput[] | Prisma.RecordPrescriptionUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordPrescriptionCreateOrConnectWithoutRecordInput | Prisma.RecordPrescriptionCreateOrConnectWithoutRecordInput[]
  upsert?: Prisma.RecordPrescriptionUpsertWithWhereUniqueWithoutRecordInput | Prisma.RecordPrescriptionUpsertWithWhereUniqueWithoutRecordInput[]
  createMany?: Prisma.RecordPrescriptionCreateManyRecordInputEnvelope
  set?: Prisma.RecordPrescriptionWhereUniqueInput | Prisma.RecordPrescriptionWhereUniqueInput[]
  disconnect?: Prisma.RecordPrescriptionWhereUniqueInput | Prisma.RecordPrescriptionWhereUniqueInput[]
  delete?: Prisma.RecordPrescriptionWhereUniqueInput | Prisma.RecordPrescriptionWhereUniqueInput[]
  connect?: Prisma.RecordPrescriptionWhereUniqueInput | Prisma.RecordPrescriptionWhereUniqueInput[]
  update?: Prisma.RecordPrescriptionUpdateWithWhereUniqueWithoutRecordInput | Prisma.RecordPrescriptionUpdateWithWhereUniqueWithoutRecordInput[]
  updateMany?: Prisma.RecordPrescriptionUpdateManyWithWhereWithoutRecordInput | Prisma.RecordPrescriptionUpdateManyWithWhereWithoutRecordInput[]
  deleteMany?: Prisma.RecordPrescriptionScalarWhereInput | Prisma.RecordPrescriptionScalarWhereInput[]
}

export type RecordPrescriptionUncheckedUpdateManyWithoutRecordNestedInput = {
  create?: Prisma.XOR<Prisma.RecordPrescriptionCreateWithoutRecordInput, Prisma.RecordPrescriptionUncheckedCreateWithoutRecordInput> | Prisma.RecordPrescriptionCreateWithoutRecordInput[] | Prisma.RecordPrescriptionUncheckedCreateWithoutRecordInput[]
  connectOrCreate?: Prisma.RecordPrescriptionCreateOrConnectWithoutRecordInput | Prisma.RecordPrescriptionCreateOrConnectWithoutRecordInput[]
  upsert?: Prisma.RecordPrescriptionUpsertWithWhereUniqueWithoutRecordInput | Prisma.RecordPrescriptionUpsertWithWhereUniqueWithoutRecordInput[]
  createMany?: Prisma.RecordPrescriptionCreateManyRecordInputEnvelope
  set?: Prisma.RecordPrescriptionWhereUniqueInput | Prisma.RecordPrescriptionWhereUniqueInput[]
  disconnect?: Prisma.RecordPrescriptionWhereUniqueInput | Prisma.RecordPrescriptionWhereUniqueInput[]
  delete?: Prisma.RecordPrescriptionWhereUniqueInput | Prisma.RecordPrescriptionWhereUniqueInput[]
  connect?: Prisma.RecordPrescriptionWhereUniqueInput | Prisma.RecordPrescriptionWhereUniqueInput[]
  update?: Prisma.RecordPrescriptionUpdateWithWhereUniqueWithoutRecordInput | Prisma.RecordPrescriptionUpdateWithWhereUniqueWithoutRecordInput[]
  updateMany?: Prisma.RecordPrescriptionUpdateManyWithWhereWithoutRecordInput | Prisma.RecordPrescriptionUpdateManyWithWhereWithoutRecordInput[]
  deleteMany?: Prisma.RecordPrescriptionScalarWhereInput | Prisma.RecordPrescriptionScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type RecordPrescriptionCreateWithoutRecordInput = {
  medicationName: string
  dosage?: string | null
  frequency?: string | null
  route?: string | null
  durationDays?: number | null
  instructions?: string | null
  prescriptionStatus?: string
  isActive?: string
  prescribedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordPrescriptionUncheckedCreateWithoutRecordInput = {
  prescriptionId?: number
  medicationName: string
  dosage?: string | null
  frequency?: string | null
  route?: string | null
  durationDays?: number | null
  instructions?: string | null
  prescriptionStatus?: string
  isActive?: string
  prescribedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordPrescriptionCreateOrConnectWithoutRecordInput = {
  where: Prisma.RecordPrescriptionWhereUniqueInput
  create: Prisma.XOR<Prisma.RecordPrescriptionCreateWithoutRecordInput, Prisma.RecordPrescriptionUncheckedCreateWithoutRecordInput>
}

export type RecordPrescriptionCreateManyRecordInputEnvelope = {
  data: Prisma.RecordPrescriptionCreateManyRecordInput | Prisma.RecordPrescriptionCreateManyRecordInput[]
  skipDuplicates?: boolean
}

export type RecordPrescriptionUpsertWithWhereUniqueWithoutRecordInput = {
  where: Prisma.RecordPrescriptionWhereUniqueInput
  update: Prisma.XOR<Prisma.RecordPrescriptionUpdateWithoutRecordInput, Prisma.RecordPrescriptionUncheckedUpdateWithoutRecordInput>
  create: Prisma.XOR<Prisma.RecordPrescriptionCreateWithoutRecordInput, Prisma.RecordPrescriptionUncheckedCreateWithoutRecordInput>
}

export type RecordPrescriptionUpdateWithWhereUniqueWithoutRecordInput = {
  where: Prisma.RecordPrescriptionWhereUniqueInput
  data: Prisma.XOR<Prisma.RecordPrescriptionUpdateWithoutRecordInput, Prisma.RecordPrescriptionUncheckedUpdateWithoutRecordInput>
}

export type RecordPrescriptionUpdateManyWithWhereWithoutRecordInput = {
  where: Prisma.RecordPrescriptionScalarWhereInput
  data: Prisma.XOR<Prisma.RecordPrescriptionUpdateManyMutationInput, Prisma.RecordPrescriptionUncheckedUpdateManyWithoutRecordInput>
}

export type RecordPrescriptionScalarWhereInput = {
  AND?: Prisma.RecordPrescriptionScalarWhereInput | Prisma.RecordPrescriptionScalarWhereInput[]
  OR?: Prisma.RecordPrescriptionScalarWhereInput[]
  NOT?: Prisma.RecordPrescriptionScalarWhereInput | Prisma.RecordPrescriptionScalarWhereInput[]
  prescriptionId?: Prisma.IntFilter<"RecordPrescription"> | number
  recordId?: Prisma.IntFilter<"RecordPrescription"> | number
  medicationName?: Prisma.StringFilter<"RecordPrescription"> | string
  dosage?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  frequency?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  route?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  durationDays?: Prisma.IntNullableFilter<"RecordPrescription"> | number | null
  instructions?: Prisma.StringNullableFilter<"RecordPrescription"> | string | null
  prescriptionStatus?: Prisma.StringFilter<"RecordPrescription"> | string
  isActive?: Prisma.StringFilter<"RecordPrescription"> | string
  prescribedAt?: Prisma.DateTimeFilter<"RecordPrescription"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"RecordPrescription"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RecordPrescription"> | Date | string
}

export type RecordPrescriptionCreateManyRecordInput = {
  prescriptionId?: number
  medicationName: string
  dosage?: string | null
  frequency?: string | null
  route?: string | null
  durationDays?: number | null
  instructions?: string | null
  prescriptionStatus?: string
  isActive?: string
  prescribedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RecordPrescriptionUpdateWithoutRecordInput = {
  medicationName?: Prisma.StringFieldUpdateOperationsInput | string
  dosage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  frequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  route?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prescriptionStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  prescribedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordPrescriptionUncheckedUpdateWithoutRecordInput = {
  prescriptionId?: Prisma.IntFieldUpdateOperationsInput | number
  medicationName?: Prisma.StringFieldUpdateOperationsInput | string
  dosage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  frequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  route?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prescriptionStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  prescribedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RecordPrescriptionUncheckedUpdateManyWithoutRecordInput = {
  prescriptionId?: Prisma.IntFieldUpdateOperationsInput | number
  medicationName?: Prisma.StringFieldUpdateOperationsInput | string
  dosage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  frequency?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  route?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  durationDays?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  prescriptionStatus?: Prisma.StringFieldUpdateOperationsInput | string
  isActive?: Prisma.StringFieldUpdateOperationsInput | string
  prescribedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RecordPrescriptionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  prescriptionId?: boolean
  recordId?: boolean
  medicationName?: boolean
  dosage?: boolean
  frequency?: boolean
  route?: boolean
  durationDays?: boolean
  instructions?: boolean
  prescriptionStatus?: boolean
  isActive?: boolean
  prescribedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recordPrescription"]>

export type RecordPrescriptionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  prescriptionId?: boolean
  recordId?: boolean
  medicationName?: boolean
  dosage?: boolean
  frequency?: boolean
  route?: boolean
  durationDays?: boolean
  instructions?: boolean
  prescriptionStatus?: boolean
  isActive?: boolean
  prescribedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recordPrescription"]>

export type RecordPrescriptionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  prescriptionId?: boolean
  recordId?: boolean
  medicationName?: boolean
  dosage?: boolean
  frequency?: boolean
  route?: boolean
  durationDays?: boolean
  instructions?: boolean
  prescriptionStatus?: boolean
  isActive?: boolean
  prescribedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}, ExtArgs["result"]["recordPrescription"]>

export type RecordPrescriptionSelectScalar = {
  prescriptionId?: boolean
  recordId?: boolean
  medicationName?: boolean
  dosage?: boolean
  frequency?: boolean
  route?: boolean
  durationDays?: boolean
  instructions?: boolean
  prescriptionStatus?: boolean
  isActive?: boolean
  prescribedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type RecordPrescriptionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"prescriptionId" | "recordId" | "medicationName" | "dosage" | "frequency" | "route" | "durationDays" | "instructions" | "prescriptionStatus" | "isActive" | "prescribedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["recordPrescription"]>
export type RecordPrescriptionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}
export type RecordPrescriptionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}
export type RecordPrescriptionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  record?: boolean | Prisma.MedicalRecordDefaultArgs<ExtArgs>
}

export type $RecordPrescriptionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RecordPrescription"
  objects: {
    record: Prisma.$MedicalRecordPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    prescriptionId: number
    recordId: number
    medicationName: string
    dosage: string | null
    frequency: string | null
    route: string | null
    durationDays: number | null
    instructions: string | null
    prescriptionStatus: string
    isActive: string
    prescribedAt: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["recordPrescription"]>
  composites: {}
}

export type RecordPrescriptionGetPayload<S extends boolean | null | undefined | RecordPrescriptionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload, S>

export type RecordPrescriptionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RecordPrescriptionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RecordPrescriptionCountAggregateInputType | true
  }

export interface RecordPrescriptionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RecordPrescription'], meta: { name: 'RecordPrescription' } }
  /**
   * Find zero or one RecordPrescription that matches the filter.
   * @param {RecordPrescriptionFindUniqueArgs} args - Arguments to find a RecordPrescription
   * @example
   * // Get one RecordPrescription
   * const recordPrescription = await prisma.recordPrescription.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RecordPrescriptionFindUniqueArgs>(args: Prisma.SelectSubset<T, RecordPrescriptionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RecordPrescriptionClient<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RecordPrescription that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RecordPrescriptionFindUniqueOrThrowArgs} args - Arguments to find a RecordPrescription
   * @example
   * // Get one RecordPrescription
   * const recordPrescription = await prisma.recordPrescription.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RecordPrescriptionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RecordPrescriptionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecordPrescriptionClient<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecordPrescription that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordPrescriptionFindFirstArgs} args - Arguments to find a RecordPrescription
   * @example
   * // Get one RecordPrescription
   * const recordPrescription = await prisma.recordPrescription.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RecordPrescriptionFindFirstArgs>(args?: Prisma.SelectSubset<T, RecordPrescriptionFindFirstArgs<ExtArgs>>): Prisma.Prisma__RecordPrescriptionClient<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RecordPrescription that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordPrescriptionFindFirstOrThrowArgs} args - Arguments to find a RecordPrescription
   * @example
   * // Get one RecordPrescription
   * const recordPrescription = await prisma.recordPrescription.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RecordPrescriptionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RecordPrescriptionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RecordPrescriptionClient<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RecordPrescriptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordPrescriptionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RecordPrescriptions
   * const recordPrescriptions = await prisma.recordPrescription.findMany()
   * 
   * // Get first 10 RecordPrescriptions
   * const recordPrescriptions = await prisma.recordPrescription.findMany({ take: 10 })
   * 
   * // Only select the `prescriptionId`
   * const recordPrescriptionWithPrescriptionIdOnly = await prisma.recordPrescription.findMany({ select: { prescriptionId: true } })
   * 
   */
  findMany<T extends RecordPrescriptionFindManyArgs>(args?: Prisma.SelectSubset<T, RecordPrescriptionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RecordPrescription.
   * @param {RecordPrescriptionCreateArgs} args - Arguments to create a RecordPrescription.
   * @example
   * // Create one RecordPrescription
   * const RecordPrescription = await prisma.recordPrescription.create({
   *   data: {
   *     // ... data to create a RecordPrescription
   *   }
   * })
   * 
   */
  create<T extends RecordPrescriptionCreateArgs>(args: Prisma.SelectSubset<T, RecordPrescriptionCreateArgs<ExtArgs>>): Prisma.Prisma__RecordPrescriptionClient<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RecordPrescriptions.
   * @param {RecordPrescriptionCreateManyArgs} args - Arguments to create many RecordPrescriptions.
   * @example
   * // Create many RecordPrescriptions
   * const recordPrescription = await prisma.recordPrescription.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RecordPrescriptionCreateManyArgs>(args?: Prisma.SelectSubset<T, RecordPrescriptionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RecordPrescriptions and returns the data saved in the database.
   * @param {RecordPrescriptionCreateManyAndReturnArgs} args - Arguments to create many RecordPrescriptions.
   * @example
   * // Create many RecordPrescriptions
   * const recordPrescription = await prisma.recordPrescription.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RecordPrescriptions and only return the `prescriptionId`
   * const recordPrescriptionWithPrescriptionIdOnly = await prisma.recordPrescription.createManyAndReturn({
   *   select: { prescriptionId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RecordPrescriptionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RecordPrescriptionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RecordPrescription.
   * @param {RecordPrescriptionDeleteArgs} args - Arguments to delete one RecordPrescription.
   * @example
   * // Delete one RecordPrescription
   * const RecordPrescription = await prisma.recordPrescription.delete({
   *   where: {
   *     // ... filter to delete one RecordPrescription
   *   }
   * })
   * 
   */
  delete<T extends RecordPrescriptionDeleteArgs>(args: Prisma.SelectSubset<T, RecordPrescriptionDeleteArgs<ExtArgs>>): Prisma.Prisma__RecordPrescriptionClient<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RecordPrescription.
   * @param {RecordPrescriptionUpdateArgs} args - Arguments to update one RecordPrescription.
   * @example
   * // Update one RecordPrescription
   * const recordPrescription = await prisma.recordPrescription.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RecordPrescriptionUpdateArgs>(args: Prisma.SelectSubset<T, RecordPrescriptionUpdateArgs<ExtArgs>>): Prisma.Prisma__RecordPrescriptionClient<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RecordPrescriptions.
   * @param {RecordPrescriptionDeleteManyArgs} args - Arguments to filter RecordPrescriptions to delete.
   * @example
   * // Delete a few RecordPrescriptions
   * const { count } = await prisma.recordPrescription.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RecordPrescriptionDeleteManyArgs>(args?: Prisma.SelectSubset<T, RecordPrescriptionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecordPrescriptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordPrescriptionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RecordPrescriptions
   * const recordPrescription = await prisma.recordPrescription.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RecordPrescriptionUpdateManyArgs>(args: Prisma.SelectSubset<T, RecordPrescriptionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RecordPrescriptions and returns the data updated in the database.
   * @param {RecordPrescriptionUpdateManyAndReturnArgs} args - Arguments to update many RecordPrescriptions.
   * @example
   * // Update many RecordPrescriptions
   * const recordPrescription = await prisma.recordPrescription.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RecordPrescriptions and only return the `prescriptionId`
   * const recordPrescriptionWithPrescriptionIdOnly = await prisma.recordPrescription.updateManyAndReturn({
   *   select: { prescriptionId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RecordPrescriptionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RecordPrescriptionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RecordPrescription.
   * @param {RecordPrescriptionUpsertArgs} args - Arguments to update or create a RecordPrescription.
   * @example
   * // Update or create a RecordPrescription
   * const recordPrescription = await prisma.recordPrescription.upsert({
   *   create: {
   *     // ... data to create a RecordPrescription
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RecordPrescription we want to update
   *   }
   * })
   */
  upsert<T extends RecordPrescriptionUpsertArgs>(args: Prisma.SelectSubset<T, RecordPrescriptionUpsertArgs<ExtArgs>>): Prisma.Prisma__RecordPrescriptionClient<runtime.Types.Result.GetResult<Prisma.$RecordPrescriptionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RecordPrescriptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordPrescriptionCountArgs} args - Arguments to filter RecordPrescriptions to count.
   * @example
   * // Count the number of RecordPrescriptions
   * const count = await prisma.recordPrescription.count({
   *   where: {
   *     // ... the filter for the RecordPrescriptions we want to count
   *   }
   * })
  **/
  count<T extends RecordPrescriptionCountArgs>(
    args?: Prisma.Subset<T, RecordPrescriptionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RecordPrescriptionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RecordPrescription.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordPrescriptionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RecordPrescriptionAggregateArgs>(args: Prisma.Subset<T, RecordPrescriptionAggregateArgs>): Prisma.PrismaPromise<GetRecordPrescriptionAggregateType<T>>

  /**
   * Group by RecordPrescription.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RecordPrescriptionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RecordPrescriptionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RecordPrescriptionGroupByArgs['orderBy'] }
      : { orderBy?: RecordPrescriptionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RecordPrescriptionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRecordPrescriptionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RecordPrescription model
 */
readonly fields: RecordPrescriptionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RecordPrescription.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RecordPrescriptionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  record<T extends Prisma.MedicalRecordDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MedicalRecordDefaultArgs<ExtArgs>>): Prisma.Prisma__MedicalRecordClient<runtime.Types.Result.GetResult<Prisma.$MedicalRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RecordPrescription model
 */
export interface RecordPrescriptionFieldRefs {
  readonly prescriptionId: Prisma.FieldRef<"RecordPrescription", 'Int'>
  readonly recordId: Prisma.FieldRef<"RecordPrescription", 'Int'>
  readonly medicationName: Prisma.FieldRef<"RecordPrescription", 'String'>
  readonly dosage: Prisma.FieldRef<"RecordPrescription", 'String'>
  readonly frequency: Prisma.FieldRef<"RecordPrescription", 'String'>
  readonly route: Prisma.FieldRef<"RecordPrescription", 'String'>
  readonly durationDays: Prisma.FieldRef<"RecordPrescription", 'Int'>
  readonly instructions: Prisma.FieldRef<"RecordPrescription", 'String'>
  readonly prescriptionStatus: Prisma.FieldRef<"RecordPrescription", 'String'>
  readonly isActive: Prisma.FieldRef<"RecordPrescription", 'String'>
  readonly prescribedAt: Prisma.FieldRef<"RecordPrescription", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"RecordPrescription", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RecordPrescription", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RecordPrescription findUnique
 */
export type RecordPrescriptionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionInclude<ExtArgs> | null
  /**
   * Filter, which RecordPrescription to fetch.
   */
  where: Prisma.RecordPrescriptionWhereUniqueInput
}

/**
 * RecordPrescription findUniqueOrThrow
 */
export type RecordPrescriptionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionInclude<ExtArgs> | null
  /**
   * Filter, which RecordPrescription to fetch.
   */
  where: Prisma.RecordPrescriptionWhereUniqueInput
}

/**
 * RecordPrescription findFirst
 */
export type RecordPrescriptionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionInclude<ExtArgs> | null
  /**
   * Filter, which RecordPrescription to fetch.
   */
  where?: Prisma.RecordPrescriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordPrescriptions to fetch.
   */
  orderBy?: Prisma.RecordPrescriptionOrderByWithRelationInput | Prisma.RecordPrescriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecordPrescriptions.
   */
  cursor?: Prisma.RecordPrescriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordPrescriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordPrescriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecordPrescriptions.
   */
  distinct?: Prisma.RecordPrescriptionScalarFieldEnum | Prisma.RecordPrescriptionScalarFieldEnum[]
}

/**
 * RecordPrescription findFirstOrThrow
 */
export type RecordPrescriptionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionInclude<ExtArgs> | null
  /**
   * Filter, which RecordPrescription to fetch.
   */
  where?: Prisma.RecordPrescriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordPrescriptions to fetch.
   */
  orderBy?: Prisma.RecordPrescriptionOrderByWithRelationInput | Prisma.RecordPrescriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RecordPrescriptions.
   */
  cursor?: Prisma.RecordPrescriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordPrescriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordPrescriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecordPrescriptions.
   */
  distinct?: Prisma.RecordPrescriptionScalarFieldEnum | Prisma.RecordPrescriptionScalarFieldEnum[]
}

/**
 * RecordPrescription findMany
 */
export type RecordPrescriptionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionInclude<ExtArgs> | null
  /**
   * Filter, which RecordPrescriptions to fetch.
   */
  where?: Prisma.RecordPrescriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RecordPrescriptions to fetch.
   */
  orderBy?: Prisma.RecordPrescriptionOrderByWithRelationInput | Prisma.RecordPrescriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RecordPrescriptions.
   */
  cursor?: Prisma.RecordPrescriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RecordPrescriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RecordPrescriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RecordPrescriptions.
   */
  distinct?: Prisma.RecordPrescriptionScalarFieldEnum | Prisma.RecordPrescriptionScalarFieldEnum[]
}

/**
 * RecordPrescription create
 */
export type RecordPrescriptionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionInclude<ExtArgs> | null
  /**
   * The data needed to create a RecordPrescription.
   */
  data: Prisma.XOR<Prisma.RecordPrescriptionCreateInput, Prisma.RecordPrescriptionUncheckedCreateInput>
}

/**
 * RecordPrescription createMany
 */
export type RecordPrescriptionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RecordPrescriptions.
   */
  data: Prisma.RecordPrescriptionCreateManyInput | Prisma.RecordPrescriptionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RecordPrescription createManyAndReturn
 */
export type RecordPrescriptionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * The data used to create many RecordPrescriptions.
   */
  data: Prisma.RecordPrescriptionCreateManyInput | Prisma.RecordPrescriptionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RecordPrescription update
 */
export type RecordPrescriptionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionInclude<ExtArgs> | null
  /**
   * The data needed to update a RecordPrescription.
   */
  data: Prisma.XOR<Prisma.RecordPrescriptionUpdateInput, Prisma.RecordPrescriptionUncheckedUpdateInput>
  /**
   * Choose, which RecordPrescription to update.
   */
  where: Prisma.RecordPrescriptionWhereUniqueInput
}

/**
 * RecordPrescription updateMany
 */
export type RecordPrescriptionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RecordPrescriptions.
   */
  data: Prisma.XOR<Prisma.RecordPrescriptionUpdateManyMutationInput, Prisma.RecordPrescriptionUncheckedUpdateManyInput>
  /**
   * Filter which RecordPrescriptions to update
   */
  where?: Prisma.RecordPrescriptionWhereInput
  /**
   * Limit how many RecordPrescriptions to update.
   */
  limit?: number
}

/**
 * RecordPrescription updateManyAndReturn
 */
export type RecordPrescriptionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * The data used to update RecordPrescriptions.
   */
  data: Prisma.XOR<Prisma.RecordPrescriptionUpdateManyMutationInput, Prisma.RecordPrescriptionUncheckedUpdateManyInput>
  /**
   * Filter which RecordPrescriptions to update
   */
  where?: Prisma.RecordPrescriptionWhereInput
  /**
   * Limit how many RecordPrescriptions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RecordPrescription upsert
 */
export type RecordPrescriptionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionInclude<ExtArgs> | null
  /**
   * The filter to search for the RecordPrescription to update in case it exists.
   */
  where: Prisma.RecordPrescriptionWhereUniqueInput
  /**
   * In case the RecordPrescription found by the `where` argument doesn't exist, create a new RecordPrescription with this data.
   */
  create: Prisma.XOR<Prisma.RecordPrescriptionCreateInput, Prisma.RecordPrescriptionUncheckedCreateInput>
  /**
   * In case the RecordPrescription was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RecordPrescriptionUpdateInput, Prisma.RecordPrescriptionUncheckedUpdateInput>
}

/**
 * RecordPrescription delete
 */
export type RecordPrescriptionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionInclude<ExtArgs> | null
  /**
   * Filter which RecordPrescription to delete.
   */
  where: Prisma.RecordPrescriptionWhereUniqueInput
}

/**
 * RecordPrescription deleteMany
 */
export type RecordPrescriptionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RecordPrescriptions to delete
   */
  where?: Prisma.RecordPrescriptionWhereInput
  /**
   * Limit how many RecordPrescriptions to delete.
   */
  limit?: number
}

/**
 * RecordPrescription without action
 */
export type RecordPrescriptionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RecordPrescription
   */
  select?: Prisma.RecordPrescriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RecordPrescription
   */
  omit?: Prisma.RecordPrescriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RecordPrescriptionInclude<ExtArgs> | null
}
